### ISSUE TITLE
How can I modify the scanner area?

### ISSUE THREAD

**Issue by burekas7** [juliansteenbakker/mobile_scanner#1003]
Hi,

Currently, the scanning area is the entire phone/camera screen.
I want to focus the scanner on a certain area so that only if the barcode is inside the area the scanner will check.

Is it possible?

**Comment by burekas7** [comment]
I found this example:
https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/lib/barcode_scanner_window.dart

I will check it.

**Comment by navaronbracke** [comment]
You should use the `scanWindow` parameter for that.
