### ISSUE TITLE
Black screen on Flutter Web and iOS

### ISSUE THREAD

**Issue by mklepaczko** [juliansteenbakker/mobile_scanner#101]
### What
- When trying to use scanner on Flutter web and IOS I get a black screen and scanner is not working.
- This issue is also mentioned in first comment of this tutorial: https://www.youtube.com/watch?v=Oaujc9-LagY

**Comment by Masishta** [comment]
I confirm this

**Comment by EricRode** [comment]
Are you using the current release from pub or the main branch from Github? @mklepaczko @Masishta

**Comment by Masishta** [comment]
> Are you using the current release from pub or the main branch from Github? @mklepaczko @Masishta

Current release from pub (version 1.0.0)

**Comment by EricRode** [comment]
Okay, then please try the main branch from Github because one of the recent PRs fixed this problem.
You can use the main branch by including 
mobile_scanner:
    git:
      url: https://github.com/juliansteenbakker/mobile_scanner

**Comment by Masishta** [comment]
Same issue with git branch

**Comment by mklepaczko** [comment]
Yes current from pub

Mkl
W dniu czw., 14.04.2022 o 09:45 EricRode ***@***.***>
napisał(a):

**Comment by EricRode** [comment]
Unfortunately I don't have an IOS device. 
Could you try to start the scanner on IOS and take a look at the console of the browser ?
Maybe the error is displayed there.

**Comment by mklepaczko** [comment]
Hello @EricRode ,

First of all thanks for your quick reply and your work on that pluggin!

I just used the pluggin from your main brach, the situation has somehow changed:
 - now on IOS it is requesting the camera usage acceptance, the red camera icon shows on Safari address bar (did not work before)
 - Then shows white scaffold page, and the image from the camera appears sometimes after clicking the screen.
 - The image appears after calling pop() on the screen for a small time before popping the screen.
 - I tried on an Android device, Huawei P30 pro, it does not request camera usage and the screen remains black.

The only errors I could catch from the Safari debugger are the following:

Loading app from service worker.
main.dart.js:21614 MobileScannerWeb: NotFoundError: Requested device not found
A MediaStreamTrack ended due to a capture failure

Mkl

**Comment by mklepaczko** [comment]
Hello,

update from today: my iphone 12 updated to IOS 15.4.1 and camera seems to work fine now.

On Android still not working, black screen and no camera request authorization. (Huawei P30 pro)

**Comment by amendezcabrera** [comment]
I think this error could be related to another one I found in Android when you try to reopen the MobileScanner widget. I posted an [question](https://stackoverflow.com/questions/71953303/error-in-mobile-scanner-flutter-library-when-reopening-the-qr-reader) in StackOverflow trying to find a solution because I couldn't after many tries.

**Comment by MB175** [comment]
can confirm, does not work in web / iOS and PWA

**Comment by MB175** [comment]
Strange enough, Debugging is working building isn't

**Comment by MB175** [comment]
> Okay, then please try the main branch from Github because one of the recent PRs fixed this problem.
> You can use the main branch by including
> mobile_scanner:
> git:
> url: https://github.com/juliansteenbakker/mobile_scanner

@EricRode 
Issue is also present in "^3.0.0-beta.2"

**Comment by juliansteenbakker** [comment]
Version 3.0.0-beta.4 updated the web framework. Can you please try again with that version, and comment if the issue still exists.

**Comment by elsenkarmaclub** [comment]
Hi @juliansteenbakker I still got the black screen on the web (chrome) using 3.0.0-beta.4. 
![image](https://user-images.githubusercontent.com/122256534/214796163-ba9de902-02a8-4081-baea-d1750bf2c0d7.png)

**Comment by MB175** [comment]
> Hi @juliansteenbakker I still got the black screen on the web (chrome) and iOS using 3.0.0-beta.4.
> ![image](https://user-images.githubusercontent.com/122256534/214796163-ba9de902-02a8-4081-baea-d1750bf2c0d7.png)

Chrome on iOS ? if so do u use a https connection otherwise the ServiceWorkers won't work. Chrome on iOS is just WebKit
