### ISSUE TITLE
iOS / MacOS wrongly map torchMode index 2 to "unavailable"

### ISSUE THREAD

**Issue by sharathguvvala** [juliansteenbakker/mobile_scanner#1033]
mobile_scanner: ^5.0.0

Torch state is by default unavailable and I am not able to turn on/off the flashlight, if i initialise the controller with torchEnabled as true, then I could turn it off/on. Is it not possible for torch be in off state and on enabling changing to on state.

```
class Scan extends StatefulWidget {
  const Scan({super.key});

  @override
  State<Scan> createState() => _ScanState();
}

class _ScanState extends State<Scan>
    with WidgetsBindingObserver {
  MobileScannerController cameraController = MobileScannerController();

  @override
  void initState() {
    super.initState();
    cameraController.start();
  }

  @override
  void dispose() async {
    super.dispose();
    await cameraController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          const SizedBox(
            height: 20,
          ), 
          ValueListenableBuilder(
            valueListenable: cameraController,
            builder: (context, state, child) {
              if (!state.isInitialized || !state.isRunning) {
                return const SizedBox.shrink();
              }
              switch (state.torchState) {
                case TorchState.off:
                  return IconButton(
                    icon: const Icon(
                      Icons.flash_off,
                      color: Colors.grey,
                    ),
                    iconSize: 32.0,
                    onPressed: () async {
                      await cameraController.toggleTorch();
                    },
                  );
                case TorchState.on:
                  return IconButton(
                    icon: const Icon(
                      Icons.flash_on,
                      color: Colors.yellow,
                    ),
                    iconSize: 32.0,
                    onPressed: () async {
                      await cameraController.toggleTorch();
                    },
                  );
                case TorchState.unavailable:
                  return const Icon(
                    Icons.no_flash,
                    color: Colors.black,
                  );
              }
            },
          ),
        ],
      ),
    );
  }
}
```

**Comment by MarioMuYao** [comment]
value = value.copyWith(
        availableCameras: viewAttributes.numberOfCameras,
        cameraDirection: effectiveDirection,
        isInitialized: true,
        isRunning: true,
        size: viewAttributes.size,
        // If the device has a flashlight, let the platform update the torch state.
        // If it does not have one, provide the unavailable state directly.
        torchState: viewAttributes.hasTorch ? null : TorchState.unavailable,
      );
      
MobileScannerState copyWith({
    int? availableCameras,
    CameraFacing? cameraDirection,
    MobileScannerException? error,
    bool? isInitialized,
    bool? isRunning,
    Size? size,
    TorchState? torchState,
    double? zoomScale,
  }) {
    return MobileScannerState(
      availableCameras: availableCameras ?? this.availableCameras,
      cameraDirection: cameraDirection ?? this.cameraDirection,
      error: error,
      isInitialized: isInitialized ?? this.isInitialized,
      isRunning: isRunning ?? this.isRunning,
      size: size ?? this.size,
      torchState: torchState ?? this.torchState,
      zoomScale: zoomScale ?? this.zoomScale,
    );
  }
    
    torchState == null ???

**Comment by sharathguvvala** [comment]
@MarioMuYao were you able to solve the issue? Is there any work around?

**Comment by MarioMuYao** [comment]
used mobile_scanner: ^4.0.1

In 5.0.0  when torchState == null  cannot set 
I try listen MobileScannerController and first set torch off,but it is not quite effective

**Comment by navaronbracke** [comment]
@sharathguvvala Initially the torch state is indeed `unavailable` since we do not know in advance if the selected camera supports a torch. When you call `start()` with `torchEnabled`, the controller tries to turn on the torch if there is one available. If you do not provide `torchEnabled: true` to the start method, you'll have to observe the value in the controller.

It is indeed not possible to turn on the torch before the camera is started, as the torch is connected to the active camera and turns off when the camera turns off.

**Comment by navaronbracke** [comment]
@sharathguvvala I tested the example app with both `torchEnabled: true` and `torchEnabled: false` on a device that has a torch for its camera and I was able to toggle the torch on/off in both cases.

Does the example app work for you?

**Comment by sharathguvvala** [comment]
@navaronbracke Is there any example that could be shared, I tried initialising the controller with `torchEnabled: false`, but it always goes to the unavailable state and not able to turn it on, torch will be available in my case as I am using it for ios device alone.

**Comment by navaronbracke** [comment]
You could try running one of the samples here https://github.com/juliansteenbakker/mobile_scanner/tree/master/example

So your ValueListenableBuilder in the sample above starts with `state.torchState` set to `TorchState.unavailable` and never changes on iOS? Could you try testing this on Android?

**Comment by sharathguvvala** [comment]
Yeah I followed the sample [here](https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/lib/scanner_button_widgets.dart#L126) by setting  `torchEnabled: false` in my controller
```
MobileScannerController cameraController = MobileScannerController(
    torchEnabled: false,
  );
```
 and the builder initially sets to `TorchState.unavailable` and the state never gets changed, I can't try on android (don't have android setup currently), testing on ios (17.4.1)

**Comment by navaronbracke** [comment]
@sharathguvvala Found the bug (I think). Is your camera on `auto` TorchMode on iOS?

We have the TorchMode enum map value `2` to `unavailable`. However, index 2 is `auto` on iOS (and probably also MacOS)

**Comment by sharathguvvala** [comment]
@navaronbracke Yes you are correct, my camera was on auto flash mode by default. But changing it to false and testing again didn't help, as it's again setting to `unavailable` state. 

Will there be a fix for this or any work around?

**Comment by navaronbracke** [comment]
@sharathguvvala Version 5.0.2 adds support for the `auto` torch mode on iOS / MacOS. Can you verify if this fix resolves your issue?

**Comment by sharathguvvala** [comment]
@navaronbracke I just tested `5.0.2`, the issue is resolved, thanks for the quick fix.
