### ISSUE TITLE
error... 5.0.1

### ISSUE THREAD

**Issue by GeonSeon** [juliansteenbakker/mobile_scanner#1040]
/pub.dev/mobile_scanner-5.0.1/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:34:45 Unresolved reference: YuvToRgbConverter
/pub.dev/mobile_scanner-5.0.1/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:97:52 Unresolved reference: data
pub.dev/mobile_scanner-5.0.1/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:100:48 Unresolved reference: data
pub.dev/mobile_scanner-5.0.1/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:110:43 Unresolved reference: YuvToRgbConverter
pub.dev/mobile_scanner-5.0.1/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:432:68 Unresolved reference: data
pub.dev/mobile_scanner-5.0.1/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:435:31 Type mismatch: inferred type is List<Unit> but List<Map<String, Any?>>? was expected

Is it possible to check once?

**Comment by Clon1998** [comment]
Seeing the same issue. -beta3 is working for me

**Comment by Clon1998** [comment]
Clearing the cache did the trick.
`dart pub cache clean  `

**Comment by navaronbracke** [comment]
Did you upgrade from an older version of mobile_scanner ? Does it reproduce after doing `flutter pub clean && flutter pub get` ?

**Comment by Clon1998** [comment]
> Did you upgrade from an older version of mobile_scanner ? Does it reproduce after doing `flutter pub clean && flutter pub get` ?

I was on 5.0.0-beta3. pub clean and clear cash did the trick for me.

**Comment by GeonSeon** [comment]
Thank you for your concern. It's going very well!
