### ISSUE TITLE
Why does the dart version need to be so new that it can't be updated at all, conflicts with other plugins, and then there are bugs in the existing version

### ISSUE THREAD

**Issue by 211277729** [juliansteenbakker/mobile_scanner#1045]
Why does the dart version need to be so new that it can't be updated at all, conflicts with other plugins, and then there are bugs in the existing version

**Comment by navaronbracke** [comment]
Could you clarify what dependency conflict you are getting? We only have a dependency on `web` for the new WASM compliant JS interop, which indeed required an upgrade of our minimum Flutter version.

> and then there are bugs in the existing version

What additional bugs are you seeing? Could you file issues for these?

**Comment by gigafunk** [comment]
I think he must be talking about the gradle AGP upgrade to 8.3.2 broke building on android last week, but not until we do a flutter clean from a working version.

**Comment by juliansteenbakker** [comment]
I have downgraded most versions of kotlin and gradle in order to be more compatible with current flutter versions. The minimum flutter version however can not be changed since this is required for the current web implementation. I will release a new version after some people have verified it.
