### ISSUE TITLE
Update MLKit to include privacy manifest

### ISSUE THREAD

**Issue by frederikstonge** [juliansteenbakker/mobile_scanner#1047]
Right now, running the script located here :
https://github.com/crasowas/app_store_required_privacy_manifest_analyser

Tells me that there are missing privacy manifest for MLKitCommon.
```bash
[0] NSPrivacyAccessedAPICategoryFileTimestamp:stat,NSURLContentModificationDateKey:./Pods/MLKitCommon/Frameworks/MLKitCommon.framework/MLKitCommon
[1] NSPrivacyAccessedAPICategorySystemBootTime:systemUptime:./Pods/MLKitCommon/Frameworks/MLKitCommon.framework/MLKitCommon
[2] NSPrivacyAccessedAPICategoryDiskSpace:NSFileSystemFreeSize:./Pods/MLKitCommon/Frameworks/MLKitCommon.framework/MLKitCommon
[3] NSPrivacyAccessedAPICategoryUserDefaults:NSUserDefaults:./Pods/MLKitCommon/Frameworks/MLKitCommon.framework/MLKitCommon
```

**Comment by navaronbracke** [comment]
Are you on version 5.0.0 of `mobile_scanner` ? This release includes an MLKit version that has a privacy manifest.

See 
https://github.com/juliansteenbakker/mobile_scanner/blob/master/ios/mobile_scanner.podspec#L18 and
https://developers.google.com/ml-kit/release-notes#ios-api-latest-versions

**Comment by frederikstonge** [comment]
Yes, 5.0.1. The sh script tells me that it is still missing. Let me check and confirm.

**Comment by navaronbracke** [comment]
@frederikstonge The `Podfile.lock` of our example app pulls in the following: (trimmed down version for readability)

Perhaps your Podfile.lock is out of date? Does it work if you delete `Podfile.lock` and `pod repo update && pod install` ?

```
PODS:
  - GoogleMLKit/BarcodeScanning (6.0.0):
    - GoogleMLKit/MLKitCore
    - MLKitBarcodeScanning (~> 5.0.0)
  - GoogleMLKit/MLKitCore (6.0.0):
    - MLKitCommon (~> 11.0.0)
  - MLImage (1.0.0-beta5)
  - MLKitBarcodeScanning (5.0.0):
    - MLKitCommon (~> 11.0)
    - MLKitVision (~> 7.0)
  - MLKitCommon (11.0.0):
  - MLKitVision (7.0.0):
    - GoogleToolboxForMac/Logger (< 5.0, >= 4.2.1)
    - "GoogleToolboxForMac/NSData+zlib (< 5.0, >= 4.2.1)"
    - GTMSessionFetcher/Core (< 4.0, >= 3.3.2)
    - MLImage (= 1.0.0-beta5)
    - MLKitCommon (~> 11.0)
  - mobile_scanner (5.0.2):
    - Flutter
    - GoogleMLKit/BarcodeScanning (~> 6.0.0)
```
