### ISSUE TITLE
Exception after phone locking

### ISSUE THREAD

**Issue by dalyhachicha** [juliansteenbakker/mobile_scanner#105]
after locking the phone (side power button),
exception:
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:mobile_scanner/src/mobile_scanner_controller.dart': Failed assertion: line 269 pos 12: 'hashCode == _controllerHashcode': MobileScannerController.startAsync called after MobileScannerController.dispose
package:mobile_scanner/src/mobile_scanner_controller.dart:269
E/flutter ( 3105): MobileScannerController methods should not be used after calling dispose

**Comment by juliansteenbakker** [comment]
Please check with latest version v3.0.0-beta.4
