### ISSUE TITLE
Examples not functional anymore

### ISSUE THREAD

**Issue by Telly86** [juliansteenbakker/mobile_scanner#1058]
Except for `barcode_scanner_simple` and `barcode_scanner_pageview` all examples give me the error:

'Generic Error: The scanner already started. Call stop() before calling start() again.'

**Comment by navaronbracke** [comment]
I see what the problem is. 
When we reverted the change to `autoStart`, the examples were not updated to use `autoStart: false` while they all use manual starts of the controller.

cc @juliansteenbakker

**Comment by dgugolf** [comment]
Example does not work at all after hot restart app, or close and open page again. Camera just do not shown but still can scan bar code.
