### ISSUE TITLE
Supported minimum iOS version is not correct in the pub.dev 

### ISSUE THREAD

**Issue by ydag** [juliansteenbakker/mobile_scanner#106]
In the [documentation](https://pub.dev/packages/mobile_scanner), the supported minimum iOS version is indicated as 11.

> iOS 11 and newer. Reason: MLKit for iOS requires at least iOS 11 and a [64bit device](https://developers.google.com/ml-kit/migration/ios).

But in the MLKit documentation it is iOS 10 or greater.

> ML Kit supports iOS version 10 or greater.

**Comment by shtreb** [comment]
@ydag you right. I had problem with build release version. After update minimal version to 11, app was built success.

@juliansteenbakker Please, update docs.

@ydag A lot of thanks for this information))

**Comment by juliansteenbakker** [comment]
Fixed in the doc, thanks.
