### ISSUE TITLE
barcode scanning not working when trying to scan a code present on top of image

### ISSUE THREAD

**Issue by sharathguvvala** [juliansteenbakker/mobile_scanner#1074]
I don't know if this is an issue, I am trying to scan a barcode which is placed on top of image, and its not detecting any code when scanned. The barcode has a different background, regardless of the image, a black box and margin is applied to the barcode, so I expected the scanning will work, is there any work around to this?

The image I am trying to scan is this

![image](https://github.com/juliansteenbakker/mobile_scanner/assets/76590740/d595a5be-c2fa-4f55-8ee4-2922e42b44ec)

**Comment by navaronbracke** [comment]
Is the barcode inverted? (So the white and black areas switched places)

It indeed does not scan for me as well.

**Comment by sharathguvvala** [comment]
Is there any way to know barcode is inverted or not?
I scanned with some other scanner apps, it worked there.

**Comment by navaronbracke** [comment]
I don't know of a way to figure that out. However, there is an [open PR](https://github.com/juliansteenbakker/mobile_scanner/pull/1071) (we still need to review it properly and give feedback)

Can you test with that PR's branch to see if it would fix this issue?

**Comment by sharathguvvala** [comment]
Yeah the barcode was inverted, it is fine if the package doesn't support. I have changed my implementation to show normal barcodes rather than inverted.
Thanks.
