### ISSUE TITLE
torchEnabledNotifier missing

### ISSUE THREAD

**Issue by SergeBerwert** [juliansteenbakker/mobile_scanner#1090]
in the latest version, I can't find torchEnabledNotifier which I used to update the button in my GUI, any recommendations on how to see if the torch is on or off?

Version: 5.1.1

This is how I did it:
```
IconButton(
        iconSize: 32.0,
        color: Colors.white,
        icon: ValueListenableBuilder(
           valueListenable: controller.torchEnabledNotifier,
           builder: (context, state, child) {
             switch (state as TorchState) {
               case TorchState.off:
                 return const Icon(Icons.flash_on, color: Colors.white);
               case TorchState.on:
                 return const Icon(Icons.flash_off, color: Colors.yellow);
             }
           },
        ),
        onPressed: () async {
          await controller.toggleTorch();        
        },
      );
```

**Comment by SergeBerwert** [comment]
Did find my answer: controller.value.torchState  tells me the state of the touch and by adding a listener I can detect changes.

**Comment by navaronbracke** [comment]
Yes, the new API uses a `ValueNotifier` which exposes a value. This value is an instance of `MobileScannerState`, which has the properties that you need.
