### ISSUE TITLE
support for barcode reading in specific regions

### ISSUE THREAD

**Issue by casvanluijtelaar** [juliansteenbakker/mobile_scanner#11]
I'm migrating a project from qr_code_scanner to this but I'm missing the support for searching in a specific camera area. I'd like use my custom overlay like show below and actually limit the scan area to any desired rect.

![54BD44A1-39FB-4D43-BAF1-8ED7C316ECE7](https://user-images.githubusercontent.com/67225314/155099542-5dbf55e3-e4af-42d1-9ec8-5431ea48e924.png)

**Comment by thamarakshan-pilla** [comment]
hi, i would like to implement this scan region too.
Is this feature currently being worked upon?
If not, i would really love to help out

**Comment by casvanluijtelaar** [comment]
> hi, i would like to implement this scan region too. Is this feature currently being worked upon? If not, i would really love to help out

I guess it's not so go for it ;)

**Comment by thamarakshan-pilla** [comment]
I have created PR for this feature.
Please check it out and approve it.
Also this is my first ever open source contribution soo thank you for this opportunity :)

**Comment by quiquegarcia** [comment]
> I have created PR for this feature. Please check it out and approve it. Also this is my first ever open source contribution soo thank you for this opportunity :)

Someone knows when this PR will be merged?

@thamarakshan-pilla where can we see your PR? maybe we can use a fork to test it

**Comment by wxyash** [comment]
+1, would love this.

**Comment by casvanluijtelaar** [comment]
It's being worked on [here](https://github.com/juliansteenbakker/mobile_scanner/pull/176), input is always helpful. the previous PR by thamarakshan-pilla is useless as it does not actually limit the scan area it just overlays some visuals.

**Comment by juliansteenbakker** [comment]
With version 3.0.0-beta.4 you can use an custom scanning area like shown in the example app: https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/lib/barcode_scanner_window.dart 

Please note that this is still a beta so there can be breaking changes in the near future.

**Comment by Ccmi** [comment]
Hi
ScanWindow is wrong when fit:BoxFit.cover. Areas other than the left and right sides of the designated area can still be identified;
