### ISSUE TITLE
TorchState not found

### ISSUE THREAD

**Issue by ds600** [juliansteenbakker/mobile_scanner#1111]
I just upgraded to Version 5.1.1 and am trying to access the torchstate of my controller:
```
  final MobileScannerController scannerController = MobileScannerController(
      facing: CameraFacing.back,
      torchEnabled: false,
      detectionSpeed: DetectionSpeed.noDuplicates,
      returnImage: false);

...
                icon: ValueListenableBuilder(
                  valueListenable: scannerController.torchState.value,

```

I get the following error:

> The getter 'torchState' isn't defined for the type 'MobileScannerController'.
> Try importing the library that defines 'torchState', correcting the name to the name of an existing getter, or defining a getter or field named 'torchState'

I havent seen anywhere in the changelogs, that this property has been removed, is that a bug?

**Comment by navaronbracke** [comment]
This was listed in the changelog: https://github.com/juliansteenbakker/mobile_scanner/blob/master/CHANGELOG.md#500-beta1

`The various ValueNotifiers for the camera state have been removed. Use the value of the MobileScannerController instead.`

So use `MobileScannerController.value.torchState` instead, as the controller is now a ValueNotifier.
