### ISSUE TITLE
[Bug] Mobile scanner not dispose on Web 

### ISSUE THREAD

**Issue by Trung15010802** [juliansteenbakker/mobile_scanner#1118]

**Comment by navaronbracke** [comment]
This is probably a duplicate of https://github.com/juliansteenbakker/mobile_scanner/issues/1087 ?

**Comment by Trung15010802** [comment]
> This is probably a duplicate of https://github.com/juliansteenbakker/mobile_scanner/issues/1087 ?

That's right
