### ISSUE TITLE
analyzeImage not work

### ISSUE THREAD

**Issue by wenchaosong** [juliansteenbakker/mobile_scanner#1132]
android ios are both not working, the return result is null

plugin version

mobile_scanner: ^5.1.1

**Comment by wenchaosong** [comment]
the details : 

1.if the QR code image is perfect, the result will be ok.

2.if the QR code image is not perfect (like blurry、scale), the result will be null
but, can use MobileScanner to scan with the same picture

**Comment by KhrisnaIndrawan** [comment]
You can try using unbundled version of the model. I dont know why, but it can read my blurry qr.

> To use the unbundled version of the MLKit Barcode-scanning, add the following line to your /android/gradle.properties file:
> 
> dev.steenbakker.mobile_scanner.useUnbundled=true

**Comment by wenchaosong** [comment]
ok, I don't test this deeply, this function is enhancement
