### ISSUE TITLE
Cannot round NaN excetion crushing the app

### ISSUE THREAD

**Issue by mkaladelfos** [juliansteenbakker/mobile_scanner#1134]
FATAL EXCEPTION: main
Cannot round NaN

FATAL EXCEPTION: main
E/AndroidRuntime( 8980): Process: com.example.app_name, PID: 8980
E/AndroidRuntime( 8980): java.lang.IllegalArgumentException: Cannot round NaN value.
E/AndroidRuntime( 8980): 	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:1165)
E/AndroidRuntime( 8980): 	at dev.steenbakker.mobile_scanner.MobileScanner.isBarcodeInScanWindow(MobileScanner.kt:177)
E/AndroidRuntime( 8980): 	at dev.steenbakker.mobile_scanner.MobileScanner.captureOutput$lambda$6$lambda$1(MobileScanner.kt:94)
E/AndroidRuntime( 8980): 	at dev.steenbakker.mobile_scanner.MobileScanner.$r8$lambda$WHeCA6JglANxIjeKXlTGAl6H0VI(Unknown Source:0)
E/AndroidRuntime( 8980): 	at dev.steenbakker.mobile_scanner.MobileScanner$$ExternalSyntheticLambda3.invoke(Unknown Source:8)
E/AndroidRuntime( 8980): 	at dev.steenbakker.mobile_scanner.MobileScanner.captureOutput$lambda$6$lambda$2(MobileScanner.kt:80)
E/AndroidRuntime( 8980): 	at dev.steenbakker.mobile_scanner.MobileScanner.$r8$lambda$FNQbW8g2ym_6Y4EZ1gdRVqQ6VqA(Unknown Source:0)
E/AndroidRuntime( 8980): 	at dev.steenbakker.mobile_scanner.MobileScanner$$ExternalSyntheticLambda14.onSuccess(Unknown Source:2)
E/AndroidRuntime( 8980): 	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
E/AndroidRuntime( 8980): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime( 8980): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 8980): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime( 8980): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime( 8980): 	at android.app.ActivityThread.main(ActivityThread.java:8762)
E/AndroidRuntime( 8980): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8980): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
E/AndroidRuntime( 8980): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
I/Process ( 8980): Sending signal. PID: 8980 SIG: 9
Lost connection to device.

probably an issue with function `isBarcodeInScanWindow` in MobileScanner.kt file

```
val left = (scanWindow[0] * imageWidth).roundToInt()
        val top = (scanWindow[1] * imageHeight).roundToInt()
        val right = (scanWindow[2] * imageWidth).roundToInt()
        val bottom = (scanWindow[3] * imageHeight).roundToInt()
```

this is where the error occurs

**Comment by mkaladelfos** [comment]
> Looks like it is indeed a problem there. I wonder why it is giving us NaN, but at least we should try not to crash and just indicate that the barcode is not in the scan window (since we cannot give an accurate result anyway)
> 
> Thanks for filing this bug! Do you have a clue why we could be getting NaN here?

My guess is that the values are not provided fast enough while building the widget. It can be reproduced by using the camera for a single scan and then disposing  or closing the camera and reopening it right away by rebuilding the widget using a hook. I use a gesture tap to scan the last barcode on the screen

**Comment by ramlaxmangroup** [comment]
I have the same issue occurred.

**Comment by calevgian100** [comment]
Same issue happening here. My workaround was to disable the 'open-camera' button for 1 or 2 seconds before enabling it again. So far this seems to give enough time to dispose the camera before opening it again.

**Comment by calevgian100** [comment]
Do you have a release date for this patch? My app is crashing on several android mobile devices.

**Comment by tyagnesh-mufin** [comment]
> I do not have a release date for this patch just yet. (I'm looking into if we can add some other fixes into it)
> 
> However, you could try depending on the commit itself, using a git dependency, as an interim solution.

I have same crash issue, Do you have a release date for this patch? otherwise i want to check some alternative package

**Comment by sagarehs** [comment]
I have same crash issue, Do you have a release date for this patch? otherwise i want to check some alternative package
