### ISSUE TITLE
Cannot build apk when i implementing the mobile_scanner dependency

### ISSUE THREAD

**Issue by Dzikry123** [juliansteenbakker/mobile_scanner#1159]
Hello i want to ask what is the compatible kotlin version for the mobile_scanner dependency ? 

i am using this version : `  mobile_scanner: ^5.1.1`

**Comment by navaronbracke** [comment]
We use Kotlin 1.7.22, Android Gradle Plugin 8.3.2 and Gradle 7.6.4

https://github.com/juliansteenbakker/mobile_scanner/blob/65bc14bb3930e27b48d917d3d645d0bef9bb1bb0/android/build.gradle#L4-L15

**Comment by Dzikry123** [comment]
Okay thank you for the answer :)
