### ISSUE TITLE
Update 5.2.0 made it Firebase incompatible

### ISSUE THREAD

**Issue by calevgian100** [juliansteenbakker/mobile_scanner#1160]
The current supported version of the package `web` for the Firebase packages in dart is `^0.5.1.`
This last mobile-scanner update made a bump to `web ^1.0.0`, so there is no way to use any Firebase service if we want to use the latest update of mobile-scanner. 
Downgrading to `^5.1.1` is not a solution as I need a fix for the NaN crash on android devices. 

<img width="1106" alt="Screenshot 2024-08-20 at 12 08 25 PM" src="https://github.com/user-attachments/assets/6f554e80-3c40-4e2b-8a7e-26975997bd9e">

**Comment by juliansteenbakker** [comment]
Can you please check if v5.2.1 fixes your problem?

**Comment by calevgian100** [comment]
> Can you please check if v5.2.1 fixes your problem?

Yes, it worked great. Thanks for the hard work!
