### ISSUE TITLE
'GTMDefines.h' file not found

### ISSUE THREAD

**Issue by shichunlei** [juliansteenbakker/mobile_scanner#1163]
Failed to build iOS app
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): 'GTMDefines.h' file not found
/Users/mac104/workspace/****/ios/Pods/GoogleToolboxForMac/Foundation/GTMNSData+zlib.h:19:8

**Comment by navaronbracke** [comment]
What version of `mobile_scanner` Are you using?
What is your Flutter version?
Did you run `pod install` ? (Maybe you need to recreate your Podfile.lock)

**Comment by shichunlei** [comment]
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.1.1 23B81 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)

mobile_scanner: ^5.2.1

**Comment by shichunlei** [comment]
It's a problem with the header file

I found GoogleToolboxForMac under ios/Pods/, and then changed the #import "GTMDefines.h" imported in the header of GTMLogger.h, GTMNSData+zlib.h, and GTMNSData+zlib.m under Foundation to #import <GTMDefines.h>. I solved this problem, but after I executed the “flutter clean” command, Pods became #import "GTMDefines.h" again. I still need to modify it manually. How can I do it?
![1](https://github.com/user-attachments/assets/ad15428a-529c-4e07-89e3-c5df60399e93)
![2](https://github.com/user-attachments/assets/835ccf66-6d05-48fa-9c2a-3ab1e59a5ff6)

**Comment by navaronbracke** [comment]
You will have to raise an issue on the MLKit issue tracker. MLKit is one of our dependencies, and we are currently on the latest version of MLKit for iOS

**Comment by Henrydykee** [comment]
Lexical or Preprocessor Issue (Xcode): 'GTMDefines.h' file not found

Lexical or Preprocessor Issue (Xcode): 'GTMDefines.h' file not found
gettting this error too
