### ISSUE TITLE
How to set default camera when MobileScanner open

### ISSUE THREAD

**Issue by vanhoa28** [juliansteenbakker/mobile_scanner#1164]
Dear developers team,

I am using mobile_scanner: ^5.2.1,  when scanner start on a device with multiple camera lens (my case: iPhone 12 Pro Max), the camera preview has been jerk for a few milliseconds (you can see in my attachment).I think it happened because of choosing camera lens issue. Can I set default camera on MobileScanner?

Thanks for your attention.

https://github.com/user-attachments/assets/b6b4418f-123d-4202-8b7e-d0e7ac83f31a

**Comment by navaronbracke** [comment]
Currently you can only use "front" or "back" as camera selector. We probably need a better API for providing the available camera's. However, how that should look API-wise is something to be looked at. (since there might be differences between Android / iOS / MacOS and web)
