### ISSUE TITLE
Property torchState of MobileScannerController class disappeared in v5.0.0

### ISSUE THREAD

**Issue by VeryazovSergey** [juliansteenbakker/mobile_scanner#1167]
Hello! I did not found any explanation why this property disappeared. Last presence in v4.0.1
But TorchState enum still exists. What can be used instead now?
Android version.

**Comment by navaronbracke** [comment]
From version 5.0.0 onwards, the MobileScannerController now implements `ValueNotifier`.
The torch state is present in the `value` of the controller.

```dart
final MobileScannerController controller = MobileScannerController();

final TorchState torchState = controller.value.torchState;
```

This was mentioned in the changelog, although we did not write a migration guide to move from v4 to v5.

**Comment by navaronbracke** [comment]
I added an issue for writing a proper migration guide in #1168 so that issues like this can be addressed with docs instead. Thank you for reporting this issue!

**Comment by VeryazovSergey** [comment]
Ok. Thank you for clarifications. Now I see that this was mentioned under the sentence "The various ValueNotifiers for the camera state have been removed. Use the value of the MobileScannerController instead". I just did not realize that _tourchState_ goes there. Finally did the migration. Thanks!
