### ISSUE TITLE
Exception when scanning WIFI QR code with encryption type set to SAE (iOS only)

### ISSUE THREAD

**Issue by richirisu** [juliansteenbakker/mobile_scanner#1172]
I encountered a problem when scanning a wifi QR code with the encryption type set to "SAE". First of all, I want to point out that "SAE" is not officially defined as an encryption type. To my knowledge it's only "nopass", "WEP", and "WPA".

That aside, when scanning a wifi QR code with "SAE" as encryption type, then the underlying ML Kit returns an otherwise undocumented value of 4 on iOS. As such, when converting the raw value to its enum value, an argument error is raised.

https://github.com/juliansteenbakker/mobile_scanner/blob/65bc14bb3930e27b48d917d3d645d0bef9bb1bb0/lib/src/enums/encryption_type.dart#L17-L30

On Android, however, ML Kit returns a value of 1 (which I think is sufficient in this case).

According to the documentation of ML Kit, there is no official value defined for 4. The same is true for the Android docs.

https://developers.google.com/ml-kit/reference/ios/mlkitbarcodescanning/api/reference/Constants

```objectivec
static const MLKBarcodeWiFiEncryptionType MLKBarcodeWiFiEncryptionTypeUnknown = 0
static const MLKBarcodeWiFiEncryptionType MLKBarcodeWiFiEncryptionTypeOpen = 1
static const MLKBarcodeWiFiEncryptionType MLKBarcodeWiFiEncryptionTypeWPA = 2
static const MLKBarcodeWiFiEncryptionType MLKBarcodeWiFiEncryptionTypeWEP = 3
```

I have experimented a little, and it seems that 4 is only returned for "SAE" and no other letter combinations, e.g. "XXX".

**WEP**

<img src="https://github.com/user-attachments/assets/2aafc343-4a44-4a14-8aad-374071f2295d" width="25%">

`WIFI:T:WEP;S:SSID;P:PASSWORD;;`

**WPA**

<img src="https://github.com/user-attachments/assets/ffcc1b74-4ca0-4298-90dd-c780c1155bc3" width="25%">

`WIFI:T:WPA;S:SSID;P:PASSWORD;;`

**SAE**

<img src="https://github.com/user-attachments/assets/f0c48fe8-3792-44f5-97d4-32115ac1d5ed" width="25%">

`WIFI:T:SAE;S:SSID;P:PASSWORD;;`

**XXX**

<img src="https://github.com/user-attachments/assets/166931bd-ba90-461b-9364-0a2d27541cc2" width="25%">

`WIFI:T:XXX;S:SSID;P:PASSWORD;;`

I got the following results on Android and on iOS:

| Raw | Android  | iOS |
| --- | --- | --- |
| WEP | 3 | 3 |
| WPA | 2 | 2 |
| SAE | 1 | 4 |
| XXX | 1 | 1 |

I am not sure how to solve this problem, but currently there is no way to catch the error from the Flutter side other than listing for fatal error. Maybe open an issue for the ML Kit development team? Otherwise, I wouldn't mind having 4 converted to none/unknown.

Lastly, I wonder if there are more undocumented values beyond 4...

**Comment by navaronbracke** [comment]
Interesting observations! In this case, we should support `MLKBarcodeWiFiEncryptionTypeUnknown` and fall back to that for unrecognized values.

**Comment by richirisu** [comment]
Hey, thanks for the super fast fix. Very much appreciated.
