### ISSUE TITLE
Can't recognize ISBN barcode 

### ISSUE THREAD

**Issue by hoangduchuu** [juliansteenbakker/mobile_scanner#1176]
Cannot scan barcode with ISBN format,
It can be scanned with qr_code_scanner, but this library cannot,
Some sample codes I attach below

![image](https://github.com/user-attachments/assets/a18fa0e5-3067-4946-bdbf-349adf4ae9f0)
![image](https://github.com/user-attachments/assets/9720fe42-cce0-4150-aab2-e582846c249e)
<img width="641" alt="image" src="https://github.com/user-attachments/assets/f55a0212-6641-4b93-a6c9-2569e4535bf4">

**Comment by navaronbracke** [comment]
If I test this with my Android device, I can scan all 3 images properly. What device are you testing this on?

**Comment by hoangduchuu** [comment]
> If I test this with my Android device, I can scan all 3 images properly. What device are you testing this on?

@navaronbracke We test on the iPhone device

**Comment by navaronbracke** [comment]
@hoangduchuu I tested this on mobile_scanner 5.2.3 and it does detect these barcodes also on iPhone.

I do see the following, though:

`5060198641183` is detected as `BarcodeType.product`
`9780760378045` is detected as `BarcodeType.isbn`
`9780593076118` is detected as `BarcodeType.isbn`

So MLKit does not detect that first one as an ISBN barcode.

**Comment by Morpa** [comment]
I was having this same kind of problem after inserting this:
` @override
  void initState() {
    super.initState();
    const scriptUrl = 'https://unpkg.com/@zxing/library@latest';

    if (kIsWeb) {
      MobileScannerPlatform.instance.setBarcodeLibraryScriptUrl(scriptUrl);
    }
  }
  }`

it worked perfectly
