### ISSUE TITLE
android.permission.READ_MEDIA_IMAGES/READ_MEDIA_VIDEO is required by mobile_scanner

### ISSUE THREAD

**Issue by lokalathlet** [juliansteenbakker/mobile_scanner#1191]
I following declaration must be declared in Google Play Console, because mobile_scanner uses these permissions.
Photo and video permissions. Why these permissions are required? Any experiences how to fix this issue.

Let us know about your app's core functionality to help us understand whether it is eligible to use photo and video permissions. [Learn more](https://support.google.com/googleplay/android-developer/answer/14115180)
Why this impacts your app
One or more of your app bundles or APKs includes the Photo and video permissions in its manifest
Policy declarations that require your attention are shown here. Fix any issues and complete the declarations before the relevant deadlines.

Details on Google Play's Photo and Video Permissions policy:
To further support protecting users’ privacy, we [introduced policy](https://support.google.com/googleplay/android-developer/answer/13986130) to limit the scope of how broad access to photos and videos can be acquired on Google Play. Only apps with a need for broad access to photos will be allowed to maintain the READ_MEDIA_IMAGES and READ_MEDIA_VIDEO permissions. Apps with a one-time or limited use of photo and video files are requested to use a system picker such as the [Android photo picker](https://android-developers.googleblog.com/2023/04/photo-picker-everywhere.html).
original link
https://support.google.com/googleplay/android-developer/answer/14115180

**Comment by lokalathlet** [comment]
Possibly find a solution for my problem. I have added tools:node="remove" to my AndroidManifest.xml file
`
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"...

<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" tools:node="remove"//>
<uses-permission android:name="android.permission.READ_MEDIA_VIDEO" `tools:node="remove"//>`
`

**Comment by navaronbracke** [comment]
Are you referring to the AndroidManifest of our _example_ app?

Because the plugin itself only requires camera permission. See https://github.com/juliansteenbakker/mobile_scanner/blob/master/android/src/main/AndroidManifest.xml

**Comment by jgaviriadev** [comment]
Yes, Google play is showing this issue when using this or I don't know if it's specifically this package, but it seems like it. Here is the warning: We found that your app does not comply with the way READ_MEDIA_IMAGES/READ_MEDIA_VIDEO permissions are allowed to be used.  @navaronbracke

**Comment by navaronbracke** [comment]
@jgaviriadev This is not an issue with the `mobile_scanner` package, but rather with one of your other dependencies.

For example, the `mobile_scanner` example app has the following permissions (this can be viewed in Android Studio when selecting the Manifest.xml and then clicking on the `Merged Manifest` button at the bottom)

![Screenshot 2024-10-31 at 19 12 23](https://github.com/user-attachments/assets/107975a5-8beb-493b-a735-af9b1cd4b53c)

_If_ you have that `READ_MEDIA_IMAGES/READ_MEDIA_VIDEO` permission in your app, then the merged manifest view will show you from where it is coming. Can you provide a screenshot of your merged manifest to verify?

**Comment by jgaviriadev** [comment]
Hi, @navaronbracke my app have this before generating the apk
![image](https://github.com/user-attachments/assets/cc4b3f11-0502-40ff-b287-9f8e4ba0f157)

But after I generate it, if I check the apk with the aapt tool, those permissions appear
![image](https://github.com/user-attachments/assets/90e7ff7c-e2cd-421a-86c2-c797a4d55590)

I can't do the same as you because I use vscode, I don't use android studio

**Comment by navaronbracke** [comment]
Well, you will need to provide evidence of what is inserting those permissions, and you can only see that with the Merged Manifest view in Android Studio. Android Studio is required for building Flutter apps on Android, so I wonder why you do not use it?

What is the output of `flutter doctor -v` ? Does it list Android Studio as not installed?
Also, those screenshots seem to be incomplete.

**Comment by jgaviriadev** [comment]
@navaronbracke Thanks for your help, the package in my case that imports these permissions (READ_MEDIA_IMAGES and READ_MEDIA_VIDEO) is open_filex: ^4.5.0. Solved

**Comment by navaronbracke** [comment]
Glad you got it sorted! I'm going to close this issue now, as it is evidence that this is not related to `mobile_scanner`.
