### ISSUE TITLE
iOS Pods version GoogleDataTransport

### ISSUE THREAD

**Issue by matovnikov** [juliansteenbakker/mobile_scanner#1193]
Hello!

[!] CocoaPods could not find compatible versions for pod "Firebase/Analytics":
  In Podfile:
```
    Firebase/Analytics

    firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 11.3.2, which depends on
      Firebase/Analytics (= 11.0.0)
```

CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
```
    firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 15.1.2, which depends on
      Firebase/Messaging (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseMessaging (~> 11.0.0) was resolved to 11.0.0, which depends on
          GoogleDataTransport (~> 10.0)
```

```
    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.3, which depends on
      GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
        MLKitBarcodeScanning (~> 5.0.0) was resolved to 5.0.0, which depends on
          MLKitCommon (~> 11.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1)
```

**Comment by leekang8277** [comment]
Please solve it quickly 😭😭😭
<img width="953" alt="image" src="https://github.com/user-attachments/assets/3dff3263-ba28-4934-9bd0-f34e60fa13ab">

**Comment by aelahmar** [comment]
Facing same issue here

**Comment by kyleorin** [comment]
same here

**Comment by limsocheat** [comment]
I have same issue.

**Comment by aelahmar** [comment]
After further investigation, I can confirm that the issue is not with the library itself but with the latest update of `MLKitCommon 11.0.0`, which supports `>= GoogleDataTransport 9.4.1, < 10.0`.

**Reference:**
[ML Kit Release Notes](https://developers.google.com/ml-kit/release-notes#expandable-2)

**Comment by amonizaone** [comment]
I Fixed issue 
overide pod file

$FirebaseSDKVersion = '10.29.0'

**Comment by kyleorin** [comment]
> I Fixed issue 
> 
> overide pod file
> 
> 
> 
> $FirebaseSDKVersion = '10.29.0'
> 
> 

@amonizaone would you mind slightly elaborating on this?

thanks,

**Comment by matovnikov** [comment]
> I Fixed issue overide pod file
> 
> $FirebaseSDKVersion = '10.29.0'

Thank you!

**Comment by matovnikov** [comment]
> > I Fixed issue
> > overide pod file
> > $FirebaseSDKVersion = '10.29.0'
> 
> @amonizaone would you mind slightly elaborating on this?
> 
> thanks,

In ios/Podfile:

<img width="419" alt="Снимок экрана 2024-09-26 в 10 29 14" src="https://github.com/user-attachments/assets/0f0f673c-ebb5-4be9-a1c3-52333b5474c1">

**Comment by EArminjon** [comment]
The real solution is not to override FirebaseSDKVersion but to just downgrade your firebase version from pubspec.yaml...

```yaml
  firebase_core: 3.2.0
  firebase_analytics: 11.2.0
  firebase_crashlytics: 4.0.3
  firebase_performance: 0.10.0+3
  firebase_remote_config: 5.0.3
```

**Comment by AbdelQuddous** [comment]
`  firebase_core: 3.3.0
firebase_remote_config: ^5.0.3
mobile_scanner: ^5.2.3`

These versions work great with me..
