### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by divyanshpatidar85** [juliansteenbakker/mobile_scanner#1194]
**Dear mobile_scanner package creator,**
I'm developing a Flutter application and I'm interested in integrating barcode scanning functionality using your mobile_scanner package. Could you provide a step-by-step guide on how to properly implement and initialize the MobileScanner widget in a typical Flutter app? Specifically, I'd appreciate insights on:

The recommended way to set up the **MobileScannerController**
Best practices for handling barcode detection events
How to manage the scanner's lifecycle in conjunction with the app's lifecycle
Any common pitfalls or performance considerations to be aware of

Thank you for your time and for creating this useful package."

i am using this code

lass MobileScannerMayBe extends StatefulWidget {
  const MobileScannerMayBe({super.key});

  @override
  State<MobileScannerMayBe> createState() => _MobileScannerMayBeState();
}

class _MobileScannerMayBeState extends State<MobileScannerMayBe> with WidgetsBindingObserver {
  final MobileScannerController controller = MobileScannerController(
  // required options for the scanner
);

   StreamSubscription<Object?>? _subscription;
  @override
  Widget build(BuildContext context) {
    return  Scaffold(
      body:MobileScanner(
        controller:controller,
      ),
    );
  }
   @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
   
    if (!controller.value.isInitialized) {
      return;
    }

    switch (state) {
      case AppLifecycleState.detached:
      case AppLifecycleState.hidden:
      case AppLifecycleState.paused:
        return;
      case AppLifecycleState.resumed:
        
        _subscription = controller.barcodes.listen(_handleBarcode);

        unawaited(controller.start());
      case AppLifecycleState.inactive:
       
        unawaited(_subscription?.cancel());
        _subscription = null;
        unawaited(controller.stop());
    }
  }

void _handleBarcode(BarcodeCapture capture) {

    print('Scanned barcode: ${capture.toString()}');
  }

void initState() {
  super.initState();

  WidgetsBinding.instance.addObserver(this);

_subscription = controller.barcodes.listen((capture) {
    _handleBarcode(capture);
  });

  unawaited(controller.start());
}

}

**Comment by navaronbracke** [comment]
We have examples in https://github.com/juliansteenbakker/mobile_scanner/tree/master/example

which includes an example of managing the lifecycle of the scanner.

**Comment by divyanshpatidar85** [comment]
thanks for helping me
