### ISSUE TITLE
blocking crashlytics update

### ISSUE THREAD

**Issue by thomasklaush** [juliansteenbakker/mobile_scanner#1195]
![image](https://github.com/user-attachments/assets/c83b1b84-fbb3-44c8-ac58-a69ba3e5655a)

**Comment by EArminjon** [comment]
Duplicate of https://github.com/juliansteenbakker/mobile_scanner/issues/1165

I think you can keep old firebase versions for the moment.

**Comment by navaronbracke** [comment]
This is a duplicate of #1165 as mentioned above.
