### ISSUE TITLE
App Crashes if multiple Qr codes are included in the viewport of scanner screen works absolutely fine with single qr codes though

### ISSUE THREAD

**Issue by jaskiratAtNexG** [juliansteenbakker/mobile_scanner#120]
https://user-images.githubusercontent.com/95342622/166425101-87b3ae4d-69c6-4f61-9193-695b492f51ed.mp4

**Comment by jaskiratAtNexG** [comment]
Closing this issue as i have figured out that onDetect method is called again and again on detection of multiple qrcodes in a single frame so to handle the code in a way that onDetect function body runs one time only.

**Comment by jaskiratAtNexG** [comment]
hi you can use this stackoverflow https://stackoverflow.com/questions/60357361/create-widget-with-transparent-hole-inside for reference

**Comment by nehal076** [comment]
> hi you can use this stackoverflow https://stackoverflow.com/questions/60357361/create-widget-with-transparent-hole-inside for reference

Thanks and you also used a scanning animation (blue color). How you did that?

**Comment by jaskiratAtNexG** [comment]
https://play.google.com/store/apps/details?id=com.flutter.gaurav_tantuway.flutter_animation_gallery hi please refer this application on playstore refer "Loop Animations" -> "Floating Icon Animation"

**Comment by RikkeiLamLva** [comment]
another ideal for this solution, im getting a same problem

**Comment by jaskiratAtNexG** [comment]
> another ideal for this solution, im getting a same problem

what problem are you getting?
