### ISSUE TITLE
CocoaPods could not find compatible versions for pod "GoogleDataTransport"

### ISSUE THREAD

**Issue by KalybosPro** [juliansteenbakker/mobile_scanner#1200]
[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
    firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 15.1.3, which depends on
      Firebase/Messaging (= 11.2.0) was resolved to 11.2.0, which depends on
        FirebaseMessaging (~> 11.2.0) was resolved to 11.2.0, which depends on
          GoogleDataTransport (~> 10.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.3, which depends on
      GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
        GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
          MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1)

**Comment by alunmvs** [comment]
Same case happen on my projects

**Comment by aazgersky** [comment]
Faced with same problem

**Comment by yeras-is** [comment]
Same

**Comment by Mr-Nadyar** [comment]
i get same

**Comment by yeras-is** [comment]
Ducplicate of https://github.com/juliansteenbakker/mobile_scanner/issues/1182

**Comment by navaronbracke** [comment]
This is a duplicate of #1182
