### ISSUE TITLE
autoStart doesn't seem to do anything

### ISSUE THREAD

**Issue by jameschristianw** [juliansteenbakker/mobile_scanner#1207]
I want to open the scanner but not automatically start scanning, so I set autoStart to false, but it seems to do nothing until I look into the code and autoStart isn't used anywhere

**Comment by navaronbracke** [comment]
What version of mobile_scanner are you using?

It is used here https://github.com/juliansteenbakker/mobile_scanner/blob/02e4c66eb645ccfd8072cfcf12f66d3274e1f569/lib/src/mobile_scanner.dart#L260

**Comment by jameschristianw** [comment]
i'm using 5.2.3
oh i see.. i think i misunderstood the autoStart means, didn't check mobile_scanner.dart part

while we're here, is there a way to pause detection without turning camera off?

**Comment by navaronbracke** [comment]
You can pause the stream subscription for the barcode stream.

**Comment by jameschristianw** [comment]
thanks that helps a lot. I do have another question but, i think i'll open another issue
