### ISSUE TITLE
xArchive broken on iOS

### ISSUE THREAD

**Issue by sthefanoss** [juliansteenbakker/mobile_scanner#1209]
This lib broke my iOS archive on Flutter 3.24.3.

When it is removed, I can archive normally. 

I'll try to do the changes proposed by [ml_kid](https://pub.dev/packages/google_ml_kit) doc. If it works, I can open a PR here to improve docs.

Otherwise you guys should do it, since there is nothing in the changelog proposing iOS changes.

Thanks for your time.

**Comment by navaronbracke** [comment]
You probably mean doing the following?

```
Since ML Kit does not support 32-bit architectures (i386 and armv7), you need to exclude armv7 architectures in Xcode in order to run flutter build ios or flutter build ipa. More info [here](https://developers.google.com/ml-kit/migration/ios).

Go to Project > Runner > Building Settings > Excluded Architectures > Any SDK > armv7
```

If you can open a pull request with the required changes, that would be appreciated. Otherwise I can take a look, too.

**Comment by navaronbracke** [comment]
@sthefanoss I think I can make this work. I'll publish a fix in v6.0.1 shortly.

**Comment by sthefanoss** [comment]
Hi @navaronbracke,

Thank you for your prompt response. Yesterday, I attempted to run my app with the changes specified in mlk_kit, but unfortunately, it didn't build successfully.

Today, I have updated the library to version 6.0.1, and now I'm encountering the following error: <img width="473" alt="image" src="https://github.com/user-attachments/assets/02fdc79c-22b5-4969-96f7-ae6d24d95fef">

I understand this may not be your direct responsibility anymore, but I haven't been able to find a solution so far. Once I do, I'll be sure to update this thread.

Thanks again for your assistance!

**Comment by navaronbracke** [comment]
Hmm, can you run this command in verbose mode and provide the logs here? I want to see which shell script is failing, with an argument list that is apparently too long.

**Comment by navaronbracke** [comment]
Hmm, is the full command as a whole too long? I found https://stackoverflow.com/questions/53226087/error-unable-to-spawn-process-argument-list-too-long-in-xcode-build#:~:text=This%20is%20basically%20due%20to,Try%20renaming%20your%20project.

**Comment by sthefanoss** [comment]
@navaronbracke thanks for your time, again!

I tried everything, but the archive still keeps failing. It might be a problem with our project.

Someday in the future, I'll try it again. For now, I'll use an alternative library.

**Comment by navaronbracke** [comment]
No problem! If you do find the reason, feel free to report it back here.

**Comment by danilkharlan** [comment]
@sthefanoss Helllo!
How you fixed it?I have the same problem

thanks in advance

**Comment by danilkharlan** [comment]
@navaronbracke Unfortunately I have the same issue

**Comment by danilkharlan** [comment]
upd:I dont know the source if issue,but upgrading to unstable mobile_scanner: 7.0.0-beta.4 helped me

**Comment by sthefanoss** [comment]
@danilkharlan I changed the lib to `flutter_barcode_scanner` at the time. But only for a workaround, since `mobile_scanner` works better. 

But now I may wait for `mobile_scanner: 7.0.0` release to undo.

Anyways, @navaronbracke feel free to close this now on when the 7.0.0 release comes out.

**Comment by navaronbracke** [comment]
@sthefanoss You could use the beta version already? The latest one is https://pub.dev/packages/mobile_scanner/versions/7.0.0-beta.4
