### ISSUE TITLE
onDetect does not handle barcode errors

### ISSUE THREAD

**Issue by AhmadFikriAS** [juliansteenbakker/mobile_scanner#1210]
I get this error when using any emulator and the emulator stops when starting the mobile scanner but for my original device there are no problems. Why is that? this happened after updating to version 6.0.0 from version 5.2.0

Mobile_scanner ^6.0.0

<img width="621" alt="image" src="https://github.com/user-attachments/assets/56166684-214b-4815-8e49-806c2f3f4b67">

![cscxxcxc](https://github.com/user-attachments/assets/e106f617-977f-495c-9f55-c7fc7d1421ee)

**Comment by navaronbracke** [comment]
`MOBILE_SCANNER_BARCODE_ERROR` is reported when an error occurred when something when wrong during the processing of a barcode. This is a change that we introduced in version 6.0.0, to align the error codes. (these used to be strings that all had `MobileScanner` as error code, which was not helpful)

I see you are using `onDetect`, which is documented to not handle these kinds of errors.
I do also see that the `onDetect` usage does not handle the errors, but instead leaves them as unhandled, which is undesired. That is a bug.

See https://github.com/juliansteenbakker/mobile_scanner/blob/master/lib/src/mobile_scanner.dart#L36-L44

**Comment by navaronbracke** [comment]
I will release a fix for this in a moment.
