### ISSUE TITLE
IOS higher minimum deployment target

### ISSUE THREAD

**Issue by anchao-lu** [juliansteenbakker/mobile_scanner#1212]
```
[!] CocoaPods could not find compatible versions for pod "mobile_scanner":
  In Podfile:
    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`)

Specs satisfying the `mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`)` dependency were found, but they required a higher minimum deployment target.
```
Can the minimum deployment target be downgraded? Maybe iOS12 or iOS13

**Comment by navaronbracke** [comment]
This is a requirement for MLKit v7.0.0

See https://developers.google.com/ml-kit/release-notes#improvements

**Comment by Okladnoj** [comment]
However, I encountered this error again as well – thanks for the link – but I don’t understand what needs to be done to make the project run?

**Comment by navaronbracke** [comment]
You need to update the minimum deployment target of your iOS app to iOS 15.5.0 or higher.

You can do that in XCode. Also you might need to override it in your podfile (so that your dependencies are also using that minimum version): https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/ios/Podfile#L40-L46

**Comment by anchao-lu** [comment]
> You need to update the minimum deployment target of your iOS app to iOS 15.5.0 or higher.
> 
> You can do that in XCode. Also you might need to override it in your podfile (so that your dependencies are also using that minimum version): https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/ios/Podfile#L40-L46

Yes, But My app have to support iOS12.

**Comment by zunjae** [comment]
> > You need to update the minimum deployment target of your iOS app to iOS 15.5.0 or higher.
> > You can do that in XCode. Also you might need to override it in your podfile (so that your dependencies are also using that minimum version): https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/ios/Podfile#L40-L46
> 
> Yes, But My app have to support iOS12.

You'll have to downgrade this library or find another one. iOS12 is very old!

**Comment by kevinhikaruevans** [comment]
You can use `mobile_scanner: ^7.0.0-beta.3` or 7.0.0 once it's released. This will bring the minimum ios version back down to ios 12.
