### ISSUE TITLE
`errorBuilder` only gets called once on iOS simulator on `6.0.1`

### ISSUE THREAD

**Issue by hmendez-figure** [juliansteenbakker/mobile_scanner#1223]
Hello, It seems that `errorBuilder` is only run once when running on iOS simulator (didn't test on Android yet).

We use the `errorbuilder` to show user permission errors but also to show workaround (copy/paste value instead of scanning) when developing on simulator. I believe this was working previously.

**Comment by nirmal-kc** [comment]
Same issue

**Comment by navaronbracke** [comment]
Do you encounter this with the example app?

Since the iOS Simulator does not have a camera (it is not emulated like the fake viewfinder on the Android emulator)
it is expected behavior that the errorBuilder is called only once, with the `unsupported` error code.

**Comment by hmendez-figure** [comment]
Yes, same on example app. I didn't think that was the intended behavior. Ok thanks! We'll add a workaround.
