### ISSUE TITLE
Prevent not reading the same qrcode multiple times

### ISSUE THREAD

**Issue by marcoprodata** [juliansteenbakker/mobile_scanner#1227]
Dear,

I create a widget with this controller:

final MobileScannerController controller = MobileScannerController(
    formats: const [BarcodeFormat.qrCode],
    detectionSpeed: DetectionSpeed.noDuplicates,
  );

and using in MobileScanner widget like this:
MobileScanner(
              fit: BoxFit.contain,
              controller: controller,
              scanWindow: scanWindow,
              onDetect: (barcodes) {
                if (mounted) {
                  final Barcode? barcode = barcodes.barcodes.firstOrNull;
                  widget.onScanned(barcode?.rawValue.toString() ?? "");
                }
              },
              errorBuilder: (context, error, child) {
                return ScannerErrorWidget(error: error);
              },
              overlayBuilder: (context, constraints) {
                return Padding(
                  padding: const EdgeInsets.only(top: 76.0, left: 20, right: 20),
                  child: Align(
                    alignment: Alignment.topCenter,
                    child: Column(
                      children: [
                        Icon(
                          Icons.qr_code, // Ícone de QR Code nativo do Flutter
                          size: 25, // Tamanho do ícone
                          color: Colors.grey[300], // Cor do ícone
                        ),
                        const SizedBox(height: 8),
                        const Text(
                          "Aponte a camera para o QR Code para realizar a leitura",
                          overflow: TextOverflow.fade,
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 16,
                          ),
                        ),
                      ],
                    ),
                  ),
                );
              },
            )

My goal is to read the qrcode by closing the window, returning the content of the qrcode, but sometimes it reads the same qrcode more than once, and then executes the command that closes the widget window, and ends up closing the previous window .
How to prevent him from duplicating the reading, as soon as he reads the first one, if the next reading is the same he ignores it?

Sorry for my bad english.

**Comment by navaronbracke** [comment]
We have a no duplicates mode, but that mode seems to have some issues at the moment.
(see https://github.com/juliansteenbakker/mobile_scanner/issues/1079)

You could keep the scanned barcodes in a Set?

**Comment by marcoprodata** [comment]
Ok, I will use a variable to avoid this situation.

**Comment by navaronbracke** [comment]
I'll be closing this issue then. We can do further tracking in #1079 for the actual bug.
