### ISSUE TITLE
[Android] Scanned barcode position is off

### ISSUE THREAD

**Issue by Jan-Rzepiszczak-Notime** [juliansteenbakker/mobile_scanner#1237]
Hi!
I'm trying to draw an overlay on detected barcodes. While on iOS it works perfectly, on Android the position of the barcode / qr code doesn't match the location on the preview. This effect is there only if I'm not changing the `cameraResolution` property on the Controller. After changing (even to the default one, so 640×480), the position is correct, but then there is a bug with invalid aspect ratio of the preview (Preview is slightly compressed vertically). 
I tested it on Sony Xperia 1 and Samsung Galaxy S22 with the same results.

Result on Android
<img width="363" alt="image" src="https://github.com/user-attachments/assets/60fcca79-e0a9-4f70-92a5-221d4e7b65a9">

Result on Android while setting cameraResoultion (QR code looks more like rectangle than square)
<img width="362" alt="image" src="https://github.com/user-attachments/assets/89166929-51be-4c05-a73d-98e5e11a498c">

Version of mobile_scanner: 6.0.2

Code sample:

```dart
//
class ScannerCubit extends Cubit<ScannerState> {
 final ms.MobileScannerController controller = ms.MobileScannerController(
    detectionTimeoutMs: detectionTimeout.inMilliseconds,
    formats: [ms.BarcodeFormat.qrCode, ms.BarcodeFormat.code128],
    //cameraResolution: const Size(640, 480), // setting this to any value breaks the aspect ratio of the preview but the qr code position is correct
  );
// rest of the code is removed for the clarity
}
```
```dart
class BarcodesOverlay extends StatelessWidget {
  const BarcodesOverlay({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<ScannerCubit, ScannerState>(
      builder: (_, state) {
        return LayoutBuilder(
          builder: (_, constraints) {
            if (state is ScannerActive) {
              final widgetSize = constraints.biggest;
              final scale = widgetSize.width / state.referenceSize.width; // referenceSize is the BarcodeCapture.size
              final previewHeight = state.referenceSize.height * scale;
              final heightDiff = previewHeight - widgetSize.height;

              return Stack(
                children: state.barcodes.map((barcode) {
                  return _BarcodeOverlay(
                    key: ValueKey(barcode.value),
                    barcodeValue: barcode.value.value,
                    points: barcode.position //position is the Barcode.corners
                        .map(
                          (point) => _mapPosition(point, scale, heightDiff),
                        )
                        .toList(),
                  );
                }).toList(),
              );
            } else {
              return const SizedBox();
            }
          },
        );
      },
    );
  }

  Offset _mapPosition(Offset original, double scale, double heightDiff) {
    return Offset(
      original.dx * scale,
      original.dy * scale - heightDiff / 2,
    );
  }
}

// rest of the code is removed for the clarity
```

**Comment by navaronbracke** [comment]
Hmm, interesting. I know we have a bug for Android, where the corners are reported in the wrong order:

https://github.com/juliansteenbakker/mobile_scanner/issues/1183#issuecomment-2396165642

What are the reported barcode capture size, barcode size & corners?

**Comment by Jan-Rzepiszczak-Notime** [comment]
It seems to be the same problem, the portrait orientation causes the position of the coordinates to be reversed.
