### ISSUE TITLE
Unable to Make MobileScanner Camera Preview Full-Screen

### ISSUE THREAD

**Issue by MalinthaSamarasinghe** [juliansteenbakker/mobile_scanner#1250]
I'm currently working on implementing a barcode scanning feature for my Flutter application using the mobile_scanner package. However, I face challenges displaying the camera view in full screen while incorporating a custom overlay similar to the attached screenshot. I cannot make the camera preview fit the full screen as intended. I have tried several approaches, including wrapping the scanner widgets, but none seem to work correctly.

Could you kindly guide me on:

1. How to ensure the camera preview occupies the entire screen.
2. Any specific configuration or widget structure required to achieve a full-screen camera view with the mobile_scanner package.

I appreciate your time and support. Please let me know if you need further details or clarification.
![Barcode Scanning Screen](https://github.com/user-attachments/assets/5bd59661-309e-4a99-ac2a-690f669bcf87)

**Comment by navaronbracke** [comment]
What exactly isn't working? You can probably do this by putting the MobileScanner widget in  a stack with StackFit.expand ?

**Comment by MalinthaSamarasinghe** [comment]
Thank you for your suggestion.

I tried using Stack with StackFit.expand and placed the MobileScanner widget inside it. However, the camera preview does not cover the full screen as expected. I also experimented with all available BoxFit options for the fit property, but the preview still leaves blank spaces at the top and bottom (as shown in the attached screenshot).

Here is the code I used:

`@override`
`Widget build(BuildContext context) {`
`  return Stack(`
`    fit: StackFit.expand,`
`    children: [`
`      MobileScanner(`
`        onDetect: _handleBarcode,`
`        fit: BoxFit.cover, // Tried other BoxFit values as well`
`      ),`
`    ],`
`  );`
`}`

Could you kindly provide a simple working example to achieve a truly full-screen camera preview that fits the entire screen, including the areas marked in the screenshot? Thank you!

![Scan](https://github.com/user-attachments/assets/17ae31e3-8ed4-47f8-b675-adfedcd1644e)

**Comment by MalinthaSamarasinghe** [comment]
After testing on a real device, the camera preview works perfectly fine and occupies the full screen as expected. It seems the issue I encountered was specific to the emulator, not the actual functionality of the package.

For other developers facing similar behavior in an emulator:

The emulator's camera simulation often doesn't render properly or as expected for full-screen previews, likely due to how it handles the camera hardware abstraction. This discrepancy is not uncommon, as emulators don't perfectly replicate real device hardware behavior.

If you're experiencing similar issues, I highly recommend testing on a real device to verify the actual behavior.

Thanks again for your guidance!

**Comment by navaronbracke** [comment]
@MalinthaSamarasinghe Yes your observation is correct. The Android emulator only provides a "fake" viewfinder for the camera (the scene with the wood furniture) and the iOS Simulator doesn't even support a camera (since it is a simulator, not an emulator) and so reports no available cameras. Because of that, the plugin will return the "unsupported" state on the iOS Simulator.
