### ISSUE TITLE
Create Barcode instance from rawValue

### ISSUE THREAD

**Issue by md-rifatkhan** [juliansteenbakker/mobile_scanner#1251]
Sorry for creating issue, is it possible to Create Barcode instance from raw Value? or any parse raw Value method?

**Comment by navaronbracke** [comment]
The `mobile_scanner` package already provides Barcode instances to use. These include their raw value.
Do you need to create a `Barcode` directly from a string? You could do that by using the `Barcode` constructor?

**Comment by navaronbracke** [comment]
You can do `Barcode(rawValue: someString)`

**Comment by md-rifatkhan** [comment]
> You can do `Barcode(rawValue: someString)`

Thanks, but the value is not assigned to its type. Barcode scanners automatically assign the value to its appropriate type—do I need to assign it manually here?

 void createBarcodeFromString() {
    Barcode barcode = const Barcode(rawValue: "https://google.com");
    print("Raw ${barcode.rawValue}");
    print("Url ${barcode.url!.url}"); // Null
  }

Sorry for taking up your time, and thanks for your help!

**Comment by navaronbracke** [comment]
If you want to manually create the `Barcode` instances, using the `Barcode` constructor, then yes you will need to assign all fields manually.

See https://github.com/juliansteenbakker/mobile_scanner/blob/master/lib/src/objects/barcode.dart#L19-L36 for all the properties that the constructor accepts. All fields are final, so any fields you pass to the constructor end up directly in the class fields.
