### ISSUE TITLE
When i run get this error in IOS

### ISSUE THREAD

**Issue by dineshMadvise** [juliansteenbakker/mobile_scanner#1253]
Could not build the precompiled application for the device.
Error (Xcode): Undefined symbol: swift_FORCELOAD$_swift_Builtin_float
Error (Xcode): Undefined symbol: swift_FORCELOAD$_swift_errno
Error (Xcode): Undefined symbol: swift_FORCELOAD$_swift_math
Error (Xcode): Undefined symbol: swift_FORCELOAD$_swift_signal
Error (Xcode): Undefined symbol: swift_FORCELOAD$_swift_stdio
Error (Xcode): Undefined symbol: swift_FORCELOAD$_swift_time
Error (Xcode): Undefined symbol: swift_FORCELOAD$_swiftsys_time
Error (Xcode): Undefined symbol: swift_FORCELOAD$_swiftunistd
Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Flutter Version : 3.22.0
Dart Version : 3.4.0
mobile_scanner Package version : 6.0.2

**Comment by navaronbracke** [comment]
What version of XCode are you using? Neither of these errors point to mobile_scanner itself.

**Comment by dineshMadvise** [comment]
Tnx. for support now its solved
