### ISSUE TITLE
Any ETA for major 7.0 release

### ISSUE THREAD

**Issue by yauhenuzum** [juliansteenbakker/mobile_scanner#1257]
Hi!

When can expect major stable release for 7.0?

Thanks!

**Comment by navaronbracke** [comment]
Currently you can already depend on the beta releases for version 7.

When version 7 is out of beta depends on how much time we have for fixing the remaining bugs / work items.

I do not have a release ETA yet. I would have to consult with Julian on this, but he is currently off on holiday for the rest of the year.

**Comment by yauhenuzum** [comment]
Oh...okay

Thanks for ypdate
