### ISSUE TITLE
iOS black screen error:No camera found or failed to open camera!

### ISSUE THREAD

**Issue by MiniOcean404** [juliansteenbakker/mobile_scanner#126]
Device version: Simulator ios15.4
flutter: iOS 2.10.5
error info : iOS black screen error:No camera found or failed to open camera!

It was good before, but today I tried it and the screen went black 。

web： no problem
android: no problem

**Comment by shijia2118** [comment]
我遇到了同样的问题，请问您是怎么解决的？
