### ISSUE TITLE
How to use it on the web？ Where is the scriptURL

### ISSUE THREAD

**Issue by mimimiaomiao1** [juliansteenbakker/mobile_scanner#1263]
Where is the scriptURL

<img width="851" alt="image" src="https://github.com/user-attachments/assets/e8ff9058-2ac6-41e7-a44a-b68f837d4243" />

**Comment by navaronbracke** [comment]
The barcode scanner library script is loaded automatically on the web.

The default url is defined here: https://github.com/juliansteenbakker/mobile_scanner/blob/master/lib/src/web/zxing/zxing_barcode_reader.dart#L55

`setBarcodeLibraryScriptUrl()` is only needed for people who are running into firewall / proxy issues, where the default url might not be available to be loaded over the network. The script url also provides a way to load the script from a local asset, that is bundled with the hosted website, if that is preferred.
