### ISSUE TITLE
[iOS][crash] -[MLKITx_GIPPseudonymousIDStore initializeStorage] Shared App Groups unavailable

### ISSUE THREAD

**Issue by yupengyang** [juliansteenbakker/mobile_scanner#128]
information: 
Platform: iOS,
os version: iOS 15,
flutter version: 2.10.3

App crash follow these steps:
1. open scanner page and request camera permission.
2. choose 'No' for permission alert
3. go to settings and open camera permission
4. back to app page, then crash with this message
-[MLKITx_GIPPseudonymousIDStore initializeStorage] Shared App Groups unavailable

**Comment by MiniOcean404** [comment]
兄弟，你是Mac虚拟机吗，我这打开之后并不能打开摄像头，权限也给了

**Comment by iulian0512** [comment]
same issue on iphone 12 physical device ios 15

**Comment by rokk4** [comment]
same issue on iPhone 13, iOS 15.6

**Comment by juliansteenbakker** [comment]
Im closing this because im cleaning out the issues. If this is still a problem please comment.
