### ISSUE TITLE
Could not run flutter build ios after using this package. Please help with this issue 

### ISSUE THREAD

**Issue by getrajan** [juliansteenbakker/mobile_scanner#132]
<img width="963" alt="Screen Shot 2022-05-13 at 23 29 52" src="https://user-images.githubusercontent.com/45525480/168338981-84ee6f18-d6c0-4894-bdf2-7673e2d29d11.png">
<img width="948" alt="Screen Shot 2022-05-13 at 23 30 07" src="https://user-images.githubusercontent.com/45525480/168339020-9d5421eb-03aa-4a0c-891f-3211b533193b.png">

**Comment by teolemon** [comment]
Hey @getrajan have you had a look at the following solution: 
https://github.com/flutter/flutter/issues/50711

**Comment by juliansteenbakker** [comment]
Im closing this because im cleaning out the issues. If this is still a problem please comment.
