### ISSUE TITLE
Unable to scan same qr again

### ISSUE THREAD

**Issue by jbm0101** [juliansteenbakker/mobile_scanner#134]
### What
- The problem I'm having is that i'm sending the scanned result to another screen, but when i get back to the scanner by pressing back button of navigation it just simply won't scan the same qr. though it works fine with other new qr.
[issue.txt](https://github.com/juliansteenbakker/mobile_scanner/files/8692147/issue.txt)

Please help.

**Comment by jbm0101** [comment]
And yes when i turened allowDuplicates on it is pushing infinite screens on navigation stack.

**Comment by bostaginting** [comment]
same problem here, I temporary resolve it by using push (not pop navigate) the page to the scan page again, so the scan page will rebuild again.

**Comment by juliansteenbakker** [comment]
You still need to set `allowDuplicates` to true, however you will manually need to restrict the navigator pushed with something like this:
```dart
                onDetect: (barcode, args) {
                  if (this.barcode != barcode.rawValue) {
                   this.barcode = barcode.rawValue;
                    // Push to new screen
                  }
                },
```
And when you pop back to this screen you need to set this.barcode to null or something else.

**Comment by mofukommit** [comment]
I've got a solution for my problem: 
I was trying to navigate to a new page with data from a QR-Code, but in background when `allowDublicates: true` it was opening multiple Pages. With `allowDublicates: false` it was opening a Page once, but you were not able to scan this code again, which makes in production no sense. 

So this is my solution like @juliansteenbakker already mentioned: 
After `onDetect:` I am navigating to an individual Page which returns a bool.

`onDetect: (barcode, args) async {
        dynamic result;
        if (this.barcode != barcode.rawValue) {
          this.barcode = barcode.rawValue;
          try {
            await controller.stop();
            setState(() {
              final data = getID(barcode.rawValue);
                result = Navigator.pushNamed(
                    context, '/PupilCheck', arguments: {
                  'pupilID': data.pupilID,
                });
            });
          } on Exception catch (e) {
            print(e);
          };
          if (await result == true) {
            controller.start();
            isStarted = false;
           this.barcode = null;
          }
        }
      }
    ),
`

Hopefully it helps!

**Comment by nomoruyi** [comment]
There should be an integrated way to activate/deactivate the ability to rescan a qr-code, as well as an option to set a timer between rescans

**Comment by juliansteenbakker** [comment]
Since there has been lots of updates, please check with latest version 3.0.0-beta.4 and comment if this issue still exists.
