### ISSUE TITLE
UI - add border and overplay camera like previous qr_scanner

### ISSUE THREAD

**Issue by Jayden62** [juliansteenbakker/mobile_scanner#135]
### What
Please add border and overplay camera like previous qr_scanner. Thanks

**Comment by teolemon** [comment]
@Jayden62 can you provide a screenshot to clarify what you mean ?

**Comment by juliansteenbakker** [comment]
This has been added in version 3.0.0-beta.4. Please see https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/lib/barcode_scanner_window.dart
