### ISSUE TITLE
Getting Blank screen while scan in flutter web +  IOS

### ISSUE THREAD

**Issue by ANKIT2364** [juliansteenbakker/mobile_scanner#141]
I am not unable to scan in ios + flutter web. thanks.

**Comment by iulian0512** [comment]
same issue on ios 15 with flutter 3.0

**Comment by Hardik3143** [comment]
same issue here but first time close scan screen while scan in flutter web + IOS

**Comment by shijia2118** [comment]
same issue on IOS 15.4.1 with Flutter 2.10.5

**Comment by juliansteenbakker** [comment]
Im closing this because im cleaning out the issues. If this is still a problem please comment.
