### ISSUE TITLE
Null check performed on type which excludes null

### ISSUE THREAD

**Issue by username-taken-already** [juliansteenbakker/mobile_scanner#142]
Upgrading to Flutter 3.0 generates the following two new warning messages. Suggest removing the Null checks to resolve the warning messages.

mobile_scanner-1.1.0/lib/src/mobile_scanner.dart:50:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null. 

lib/src/widgets/binding.dart -> WidgetsBinding.instance?.addObserver(this);

mobile_scanner-1.1.0/lib/src/mobile_scanner.dart:134:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.

lib/src/widgets/binding.dart -> WidgetsBinding.instance?.removeObserver(this);

**Comment by quiquegarcia** [comment]
Confirmed

**Comment by juliansteenbakker** [comment]
This is fixed and will be released asap
