### ISSUE TITLE
cannot scan when move to mobile scanner page from mobile scanner page.

### ISSUE THREAD

**Issue by muxacarin** [juliansteenbakker/mobile_scanner#147]
We use this package at 2 page, and can move from one page to another.

When user is at QRScanPage1, and move to QRScanPage2, onDetect callback is not Working. Cameca Preview is working normaly. 

below is Debug log of flutter When page move.

Sorry for short english. English is not my first language :(

`D/ViewRootImpl@7473793[MainActivity](13833): ViewPostIme pointer 0
D/ViewRootImpl@7473793[MainActivity](13833): ViewPostIme pointer 1
D/DeferrableSurface(13833): Surface created[total_surfaces=1, used_surfaces=0](androidx.camera.core.SurfaceRequest$2@8fc2590}
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
I/chatty  (13833): uid=10300(com.pinokiolab.tipawallet) identical 1 line
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/DeferrableSurface(13833): Surface created[total_surfaces=2, used_surfaces=0](androidx.camera.core.impl.ImmediateSurface@43076af}
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Use case androidx.camera.core.Preview-8b21626e-3643-4670-b36a-540b07bc766730820279 ACTIVE
D/UseCaseAttachState(13833): Active and attached use case: [] for camera: 0
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
I/LOG     (13833): Analyzer: 640x480
I/LOG     (13833): Preview: 1440x1080
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Use case androidx.camera.core.ImageAnalysis-04459f8f-65f9-47ba-9c19-15cff58eccf310517284 ACTIVE
D/UseCaseAttachState(13833): Active and attached use case: [] for camera: 0
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Use cases [androidx.camera.core.Preview-8b21626e-3643-4670-b36a-540b07bc766730820279, androidx.camera.core.ImageAnalysis-04459f8f-65f9-47ba-9c19-15cff58eccf310517284] now ATTACHED
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/UseCaseAttachState(13833): All use case: [androidx.camera.core.Preview-8b21626e-3643-4670-b36a-540b07bc766730820279, androidx.camera.core.ImageAnalysis-04459f8f-65f9-47ba-9c19-15cff58eccf310517284] for camera: 0
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/UseCaseAttachState(13833): Active and attached use case: [androidx.camera.core.Preview-8b21626e-3643-4670-b36a-540b07bc766730820279, androidx.camera.core.ImageAnalysis-04459f8f-65f9-47ba-9c19-15cff58eccf310517284] for camera: 0
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Resetting Capture Session
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Releasing session in state INITIALIZED
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Attempting to force open the camera.
D/CameraStateRegistry(13833): tryOpenCamera(Camera@af7ff82[id=0]) [Available Cameras: 1, Already Open: false (Previous state: CLOSED)] --> SUCCESS
D/CameraStateRegistry(13833): Recalculating open cameras:
D/CameraStateRegistry(13833): Camera                                       State
D/CameraStateRegistry(13833): -------------------------------------------------------------------
D/CameraStateRegistry(13833): Camera@9468685[id=1]                         UNKNOWN
D/CameraStateRegistry(13833): Camera@af7ff82[id=0]                         OPENING
D/CameraStateRegistry(13833): -------------------------------------------------------------------
D/CameraStateRegistry(13833): Open count: 1 (Max allowed: 1)
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Opening camera.
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Transitioning camera internal state: INITIALIZED --> OPENING
D/CameraStateMachine(13833): New public camera state CameraState{type=OPENING, error=null} from OPENING and null
D/CameraStateMachine(13833): Publishing new public camera state CameraState{type=OPENING, error=null}
D/UseCaseAttachState(13833): All use case: [androidx.camera.core.Preview-8b21626e-3643-4670-b36a-540b07bc766730820279, androidx.camera.core.ImageAnalysis-04459f8f-65f9-47ba-9c19-15cff58eccf310517284] for camera: 0
E/Camera_APM : (13833): [APM]APM's Thread is started
E/Camera_APM : (13833): [APM] This app is forground app
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Use case androidx.camera.core.Preview-8b21626e-3643-4670-b36a-540b07bc766730820279 ACTIVE
D/UseCaseAttachState(13833): Active and attached use case: [androidx.camera.core.Preview-8b21626e-3643-4670-b36a-540b07bc766730820279, androidx.camera.core.ImageAnalysis-04459f8f-65f9-47ba-9c19-15cff58eccf310517284] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Use case androidx.camera.core.ImageAnalysis-04459f8f-65f9-47ba-9c19-15cff58eccf310517284 ACTIVE
D/UseCaseAttachState(13833): Active and attached use case: [androidx.camera.core.Preview-8b21626e-3643-4670-b36a-540b07bc766730820279, androidx.camera.core.ImageAnalysis-04459f8f-65f9-47ba-9c19-15cff58eccf310517284] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Issue capture request
D/UseCaseAttachState(13833): Active and attached use case: [androidx.camera.core.Preview-8b21626e-3643-4670-b36a-540b07bc766730820279, androidx.camera.core.ImageAnalysis-04459f8f-65f9-47ba-9c19-15cff58eccf310517284] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} CameraDevice.onOpened()
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Transitioning camera internal state: OPENING --> OPENED
D/CameraStateRegistry(13833): Recalculating open cameras:
D/CameraStateRegistry(13833): Camera                                       State
D/CameraStateRegistry(13833): -------------------------------------------------------------------
D/CameraStateRegistry(13833): Camera@9468685[id=1]                         UNKNOWN
D/CameraStateRegistry(13833): Camera@af7ff82[id=0]                         OPEN
D/CameraStateRegistry(13833): -------------------------------------------------------------------
D/CameraStateRegistry(13833): Open count: 1 (Max allowed: 1)
D/CameraStateMachine(13833): New public camera state CameraState{type=OPEN, error=null} from OPEN and null
D/CameraStateMachine(13833): Publishing new public camera state CameraState{type=OPEN, error=null}
D/UseCaseAttachState(13833): All use case: [androidx.camera.core.Preview-8b21626e-3643-4670-b36a-540b07bc766730820279, androidx.camera.core.ImageAnalysis-04459f8f-65f9-47ba-9c19-15cff58eccf310517284] for camera: 0
D/UseCaseAttachState(13833): Active and attached use case: [androidx.camera.core.Preview-8b21626e-3643-4670-b36a-540b07bc766730820279, androidx.camera.core.ImageAnalysis-04459f8f-65f9-47ba-9c19-15cff58eccf310517284] for camera: 0
D/SyncCaptureSessionBase(13833): [androidx.camera.camera2.internal.SynchronizedCaptureSessionBaseImpl@270e131] getSurface...done
D/CaptureSession(13833): Opening capture session.
D/DeferrableSurface(13833): New surface in use[total_surfaces=2, used_surfaces=1](androidx.camera.core.SurfaceRequest$2@8fc2590}
D/DeferrableSurface(13833): use count+1, useCount=1 androidx.camera.core.SurfaceRequest$2@8fc2590
D/DeferrableSurface(13833): New surface in use[total_surfaces=2, used_surfaces=2](androidx.camera.core.impl.ImmediateSurface@43076af}
D/DeferrableSurface(13833): use count+1, useCount=1 androidx.camera.core.impl.ImmediateSurface@43076af
D/CaptureSession(13833): Attempting to send capture request onConfigured
D/CaptureSession(13833): Issuing request for session.
D/CaptureSession(13833): Issuing capture request.
D/CaptureSession(13833): CameraCaptureSession.onConfigured() mState=OPENED
D/CaptureSession(13833): CameraCaptureSession.onReady() OPENED
D/TransportRuntime.SQLiteEventStore(13833): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(13833): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/TransportRuntime.SQLiteEventStore(13833): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(13833): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/TransportRuntime.SQLiteEventStore(13833): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(13833): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/TransportRuntime.SQLiteEventStore(13833): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(13833): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/TransportRuntime.SQLiteEventStore(13833): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(13833): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/TransportRuntime.SQLiteEventStore(13833): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(13833): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/ViewRootImpl@7473793[MainActivity](13833): ViewPostIme pointer 0
D/ViewRootImpl@7473793[MainActivity](13833): ViewPostIme pointer 1
D/DeferrableSurface(13833): surface closed,  useCount=1 closed=true androidx.camera.core.SurfaceRequest$2@8fc2590
D/DeferrableSurface(13833): surface closed,  useCount=1 closed=true androidx.camera.core.impl.ImmediateSurface@43076af
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Use cases [androidx.camera.core.Preview-8b21626e-3643-4670-b36a-540b07bc766730820279, androidx.camera.core.ImageAnalysis-04459f8f-65f9-47ba-9c19-15cff58eccf310517284] now DETACHED for camera
D/UseCaseAttachState(13833): All use case: [] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Resetting Capture Session
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Releasing session in state OPENED
D/UseCaseAttachState(13833): Active and attached use case: [] for camera: 0
D/UseCaseAttachState(13833): Active and attached use case: [] for camera: 0
E/BufferQueueProducer(13833): [SurfaceTexture-0-13833-42] queueBuffer: BufferQueue has been abandoned
I/olab.tipawalle(13833): Background concurrent copying GC freed 138537(4MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 7MB/14MB, paused 157us total 106.653ms
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Closing camera.
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Transitioning camera internal state: OPENED --> CLOSING
D/CameraStateRegistry(13833): Recalculating open cameras:
D/CameraStateRegistry(13833): Camera                                       State
D/CameraStateRegistry(13833): -------------------------------------------------------------------
D/CameraStateRegistry(13833): Camera@9468685[id=1]                         UNKNOWN
D/CameraStateRegistry(13833): Camera@af7ff82[id=0]                         CLOSING
D/CameraStateRegistry(13833): -------------------------------------------------------------------
D/CameraStateRegistry(13833): Open count: 1 (Max allowed: 1)
D/CameraStateMachine(13833): New public camera state CameraState{type=CLOSING, error=null} from CLOSING and null
D/CameraStateMachine(13833): Publishing new public camera state CameraState{type=CLOSING, error=null}
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Resetting Capture Session
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Releasing session in state CLOSING
D/CaptureSession(13833): onSessionFinished()
E/BufferQueueProducer(13833): [SurfaceTexture-0-13833-42] queueBuffer: BufferQueue has been abandoned
D/DeferrableSurface(13833): Surface created[total_surfaces=3, used_surfaces=2](androidx.camera.core.SurfaceRequest$2@70f4329}
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
I/chatty  (13833): uid=10300(com.pinokiolab.tipawallet) identical 1 line
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/DeferrableSurface(13833): Surface created[total_surfaces=4, used_surfaces=2](androidx.camera.core.impl.ImmediateSurface@525bfdc}
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
I/LOG     (13833): Analyzer: 640x480
I/LOG     (13833): Preview: 1440x1080
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/DeferrableSurface(13833): surface closed,  useCount=0 closed=true androidx.camera.core.SurfaceRequest$2@70f4329
D/DeferrableSurface(13833): Surface terminated[total_surfaces=3, used_surfaces=2](androidx.camera.core.SurfaceRequest$2@70f4329}
D/DeferrableSurface(13833): surface closed,  useCount=0 closed=true androidx.camera.core.impl.ImmediateSurface@525bfdc
D/DeferrableSurface(13833): Surface terminated[total_surfaces=2, used_surfaces=2](androidx.camera.core.impl.ImmediateSurface@525bfdc}
D/DeferrableSurface(13833): Surface created[total_surfaces=3, used_surfaces=2](androidx.camera.core.SurfaceRequest$2@2c6d80c}
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
E/BufferQueueProducer(13833): [SurfaceTexture-0-13833-42] queueBuffer: BufferQueue has been abandoned
D/DeferrableSurface(13833): Surface created[total_surfaces=4, used_surfaces=2](androidx.camera.core.impl.ImmediateSurface@21fb85b}
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
I/LOG     (13833): Analyzer: 640x480
I/LOG     (13833): Preview: 1440x1080
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/CameraOrientationUtil(13833): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
E/BufferQueueProducer(13833): [SurfaceTexture-0-13833-42] queueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(13833): [SurfaceTexture-0-13833-42] queueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(13833): [SurfaceTexture-0-13833-42] queueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(13833): [SurfaceTexture-0-13833-42] queueBuffer: BufferQueue has been abandoned
D/UseCaseAttachState(13833): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Use case androidx.camera.core.Preview-40b9e0d2-0eca-444b-8c3e-2c9f43152267206211415 ACTIVE
D/UseCaseAttachState(13833): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Use case androidx.camera.core.ImageAnalysis-52ae155a-bfc1-41eb-8864-caa7e1ffdadf203079981 ACTIVE
D/UseCaseAttachState(13833): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Use cases [androidx.camera.core.Preview-40b9e0d2-0eca-444b-8c3e-2c9f43152267206211415, androidx.camera.core.ImageAnalysis-52ae155a-bfc1-41eb-8864-caa7e1ffdadf203079981] now ATTACHED
D/UseCaseAttachState(13833): All use case: [androidx.camera.core.Preview-40b9e0d2-0eca-444b-8c3e-2c9f43152267206211415, androidx.camera.core.ImageAnalysis-52ae155a-bfc1-41eb-8864-caa7e1ffdadf203079981] for camera: 0
D/UseCaseAttachState(13833): Active and attached use case: [androidx.camera.core.Preview-40b9e0d2-0eca-444b-8c3e-2c9f43152267206211415, androidx.camera.core.ImageAnalysis-52ae155a-bfc1-41eb-8864-caa7e1ffdadf203079981] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Resetting Capture Session
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Releasing session in state CLOSING
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Transitioning camera internal state: CLOSING --> REOPENING
D/CameraStateRegistry(13833): Recalculating open cameras:
D/CameraStateRegistry(13833): Camera                                       State
D/CameraStateRegistry(13833): -------------------------------------------------------------------
D/CameraStateRegistry(13833): Camera@9468685[id=1]                         UNKNOWN
D/CameraStateRegistry(13833): Camera@af7ff82[id=0]                         OPENING
D/CameraStateRegistry(13833): -------------------------------------------------------------------
D/CameraStateRegistry(13833): Open count: 1 (Max allowed: 1)
D/CameraStateMachine(13833): New public camera state CameraState{type=OPENING, error=null} from OPENING and null
D/CameraStateMachine(13833): Publishing new public camera state CameraState{type=OPENING, error=null}
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Use case androidx.camera.core.Preview-40b9e0d2-0eca-444b-8c3e-2c9f43152267206211415 ACTIVE
D/UseCaseAttachState(13833): Active and attached use case: [androidx.camera.core.Preview-40b9e0d2-0eca-444b-8c3e-2c9f43152267206211415, androidx.camera.core.ImageAnalysis-52ae155a-bfc1-41eb-8864-caa7e1ffdadf203079981] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Use case androidx.camera.core.ImageAnalysis-52ae155a-bfc1-41eb-8864-caa7e1ffdadf203079981 ACTIVE
D/UseCaseAttachState(13833): Active and attached use case: [androidx.camera.core.Preview-40b9e0d2-0eca-444b-8c3e-2c9f43152267206211415, androidx.camera.core.ImageAnalysis-52ae155a-bfc1-41eb-8864-caa7e1ffdadf203079981] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Issue capture request
D/UseCaseAttachState(13833): Active and attached use case: [androidx.camera.core.Preview-40b9e0d2-0eca-444b-8c3e-2c9f43152267206211415, androidx.camera.core.ImageAnalysis-52ae155a-bfc1-41eb-8864-caa7e1ffdadf203079981] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Use cases [androidx.camera.core.Preview-40b9e0d2-0eca-444b-8c3e-2c9f43152267206211415, androidx.camera.core.ImageAnalysis-52ae155a-bfc1-41eb-8864-caa7e1ffdadf203079981] now DETACHED for camera
D/UseCaseAttachState(13833): All use case: [] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Resetting Capture Session
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Releasing session in state REOPENING
D/UseCaseAttachState(13833): Active and attached use case: [] for camera: 0
D/UseCaseAttachState(13833): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Closing camera.
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Transitioning camera internal state: REOPENING --> CLOSING
D/CameraStateRegistry(13833): Recalculating open cameras:
D/CameraStateRegistry(13833): Camera                                       State
D/CameraStateRegistry(13833): -------------------------------------------------------------------
D/CameraStateRegistry(13833): Camera@9468685[id=1]                         UNKNOWN
D/CameraStateRegistry(13833): Camera@af7ff82[id=0]                         CLOSING
D/CameraStateRegistry(13833): -------------------------------------------------------------------
D/CameraStateRegistry(13833): Open count: 1 (Max allowed: 1)
D/CameraStateMachine(13833): New public camera state CameraState{type=CLOSING, error=null} from CLOSING and null
D/CameraStateMachine(13833): Publishing new public camera state CameraState{type=CLOSING, error=null}
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Use case androidx.camera.core.Preview-fda3b65a-6a11-438e-8232-2b7704a25e8159650019 ACTIVE
D/UseCaseAttachState(13833): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Use case androidx.camera.core.ImageAnalysis-85c782c2-456b-4fcb-a817-ca44aab5f5b645333984 ACTIVE
D/UseCaseAttachState(13833): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Use cases [androidx.camera.core.Preview-fda3b65a-6a11-438e-8232-2b7704a25e8159650019, androidx.camera.core.ImageAnalysis-85c782c2-456b-4fcb-a817-ca44aab5f5b645333984] now ATTACHED
D/UseCaseAttachState(13833): All use case: [androidx.camera.core.Preview-fda3b65a-6a11-438e-8232-2b7704a25e8159650019, androidx.camera.core.ImageAnalysis-85c782c2-456b-4fcb-a817-ca44aab5f5b645333984] for camera: 0
D/UseCaseAttachState(13833): Active and attached use case: [androidx.camera.core.Preview-fda3b65a-6a11-438e-8232-2b7704a25e8159650019, androidx.camera.core.ImageAnalysis-85c782c2-456b-4fcb-a817-ca44aab5f5b645333984] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Resetting Capture Session
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Releasing session in state CLOSING
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Transitioning camera internal state: CLOSING --> REOPENING
D/CameraStateRegistry(13833): Recalculating open cameras:
D/CameraStateRegistry(13833): Camera                                       State
D/CameraStateRegistry(13833): -------------------------------------------------------------------
D/CameraStateRegistry(13833): Camera@9468685[id=1]                         UNKNOWN
D/CameraStateRegistry(13833): Camera@af7ff82[id=0]                         OPENING
D/CameraStateRegistry(13833): -------------------------------------------------------------------
D/CameraStateRegistry(13833): Open count: 1 (Max allowed: 1)
D/CameraStateMachine(13833): New public camera state CameraState{type=OPENING, error=null} from OPENING and null
D/CameraStateMachine(13833): Publishing new public camera state CameraState{type=OPENING, error=null}
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Use case androidx.camera.core.Preview-fda3b65a-6a11-438e-8232-2b7704a25e8159650019 ACTIVE
D/UseCaseAttachState(13833): Active and attached use case: [androidx.camera.core.Preview-fda3b65a-6a11-438e-8232-2b7704a25e8159650019, androidx.camera.core.ImageAnalysis-85c782c2-456b-4fcb-a817-ca44aab5f5b645333984] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Use case androidx.camera.core.ImageAnalysis-85c782c2-456b-4fcb-a817-ca44aab5f5b645333984 ACTIVE
D/UseCaseAttachState(13833): Active and attached use case: [androidx.camera.core.Preview-fda3b65a-6a11-438e-8232-2b7704a25e8159650019, androidx.camera.core.ImageAnalysis-85c782c2-456b-4fcb-a817-ca44aab5f5b645333984] for camera: 0
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Issue capture request
D/UseCaseAttachState(13833): Active and attached use case: [androidx.camera.core.Preview-fda3b65a-6a11-438e-8232-2b7704a25e8159650019, androidx.camera.core.ImageAnalysis-85c782c2-456b-4fcb-a817-ca44aab5f5b645333984] for camera: 0
D/DeferrableSurface(13833): use count-1,  useCount=0 closed=true androidx.camera.core.SurfaceRequest$2@8fc2590
D/DeferrableSurface(13833): Surface no longer in use[total_surfaces=4, used_surfaces=1](androidx.camera.core.SurfaceRequest$2@8fc2590}
D/DeferrableSurface(13833): Surface terminated[total_surfaces=3, used_surfaces=1](androidx.camera.core.SurfaceRequest$2@8fc2590}
D/DeferrableSurface(13833): use count-1,  useCount=0 closed=true androidx.camera.core.impl.ImmediateSurface@43076af
D/DeferrableSurface(13833): Surface no longer in use[total_surfaces=3, used_surfaces=0](androidx.camera.core.impl.ImmediateSurface@43076af}
D/DeferrableSurface(13833): Surface terminated[total_surfaces=2, used_surfaces=0](androidx.camera.core.impl.ImmediateSurface@43076af}
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} CameraDevice.onClosed()
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Attempting to open the camera.
D/CameraStateRegistry(13833): tryOpenCamera(Camera@af7ff82[id=0]) [Available Cameras: 0, Already Open: true (Previous state: OPENING)] --> SUCCESS
D/CameraStateRegistry(13833): Recalculating open cameras:
D/CameraStateRegistry(13833): Camera                                       State
D/CameraStateRegistry(13833): -------------------------------------------------------------------
D/CameraStateRegistry(13833): Camera@9468685[id=1]                         UNKNOWN
D/CameraStateRegistry(13833): Camera@af7ff82[id=0]                         OPENING
D/CameraStateRegistry(13833): -------------------------------------------------------------------
D/CameraStateRegistry(13833): Open count: 1 (Max allowed: 1)
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Opening camera.
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Transitioning camera internal state: REOPENING --> OPENING
D/CameraStateMachine(13833): New public camera state CameraState{type=OPENING, error=null} from OPENING and null
D/UseCaseAttachState(13833): All use case: [androidx.camera.core.Preview-fda3b65a-6a11-438e-8232-2b7704a25e8159650019, androidx.camera.core.ImageAnalysis-85c782c2-456b-4fcb-a817-ca44aab5f5b645333984] for camera: 0
E/Camera_APM : (13833): [APM]APM's Thread is started
E/Camera_APM : (13833): [APM] This app is forground app
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} CameraDevice.onOpened()
D/Camera2CameraImpl(13833): {Camera@af7ff82[id=0]} Transitioning camera internal state: OPENING --> OPENED
D/CameraStateRegistry(13833): Recalculating open cameras:
D/CameraStateRegistry(13833): Camera                                       State
D/CameraStateRegistry(13833): -------------------------------------------------------------------
D/CameraStateRegistry(13833): Camera@9468685[id=1]                         UNKNOWN
D/CameraStateRegistry(13833): Camera@af7ff82[id=0]                         OPEN
D/CameraStateRegistry(13833): -------------------------------------------------------------------
D/CameraStateRegistry(13833): Open count: 1 (Max allowed: 1)
D/CameraStateMachine(13833): New public camera state CameraState{type=OPEN, error=null} from OPEN and null
D/CameraStateMachine(13833): Publishing new public camera state CameraState{type=OPEN, error=null}
D/UseCaseAttachState(13833): All use case: [androidx.camera.core.Preview-fda3b65a-6a11-438e-8232-2b7704a25e8159650019, androidx.camera.core.ImageAnalysis-85c782c2-456b-4fcb-a817-ca44aab5f5b645333984] for camera: 0
D/UseCaseAttachState(13833): Active and attached use case: [androidx.camera.core.Preview-fda3b65a-6a11-438e-8232-2b7704a25e8159650019, androidx.camera.core.ImageAnalysis-85c782c2-456b-4fcb-a817-ca44aab5f5b645333984] for camera: 0
D/SyncCaptureSessionBase(13833): [androidx.camera.camera2.internal.SynchronizedCaptureSessionBaseImpl@c8be2ed] getSurface...done
D/CaptureSession(13833): Opening capture session.
D/DeferrableSurface(13833): New surface in use[total_surfaces=2, used_surfaces=1](androidx.camera.core.SurfaceRequest$2@2c6d80c}
D/DeferrableSurface(13833): use count+1, useCount=1 androidx.camera.core.SurfaceRequest$2@2c6d80c
D/DeferrableSurface(13833): New surface in use[total_surfaces=2, used_surfaces=2](androidx.camera.core.impl.ImmediateSurface@21fb85b}
D/DeferrableSurface(13833): use count+1, useCount=1 androidx.camera.core.impl.ImmediateSurface@21fb85b
D/CaptureSession(13833): Attempting to send capture request onConfigured
D/CaptureSession(13833): Issuing request for session.
D/CaptureSession(13833): Issuing capture request.
D/CaptureSession(13833): CameraCaptureSession.onConfigured() mState=OPENED
D/CaptureSession(13833): CameraCaptureSession.onReady() OPENED
`

**Comment by juliansteenbakker** [comment]
Please try again with v3.0.0.
