### ISSUE TITLE
Question: Get available FacingTypes

### ISSUE THREAD

**Issue by t-kietzmann** [juliansteenbakker/mobile_scanner#153]
Hey all, 

at first thanks for the great package! 
I would like to know it there is a way to get the available FacingTypes from the device , see: https://pub.dev/documentation/camera/latest/camera/availableCameras.html

Thanks!

**Comment by t-kietzmann** [comment]
Any news on this?

**Comment by juliansteenbakker** [comment]
For now this is not an option.
