### ISSUE TITLE
Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.

### ISSUE THREAD

**Issue by JamesTovarR04** [juliansteenbakker/mobile_scanner#155]
Hello, I hope you are well.

When running my application this error comes out due to the library:

`Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
Try calling using ?. instead.
    WidgetsBinding.instance.addObserver(this);
                            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/mobile_scanner-1.1.1/lib/src/mobile_scanner.dart:131:29: Error: Method 'removeObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
Try calling using ?. instead.

    WidgetsBinding.instance.removeObserver(this);`

**Comment by juliansteenbakker** [comment]
This is fixed in version 1.1.1.
