### ISSUE TITLE
Null Safety Error

### ISSUE THREAD

**Issue by hamza-bilal-gaya** [juliansteenbakker/mobile_scanner#165]
When we install a this plugin and try to reload the application it gives us the null aware operation error in plugin, although it's a minor error. 
![Screenshot 2022-05-30 at 6 43 21 PM (2)](https://user-images.githubusercontent.com/84728933/171005210-724cfb74-28fb-4414-839f-00dade1eba05.png)

**Comment by juliansteenbakker** [comment]
This will be fixed asap in version 2.0.0

**Comment by juliansteenbakker** [comment]
I've released v2.0.0 which fixes this error.

**Comment by hamza-bilal-gaya** [comment]
Thanks a lot my friend
