### ISSUE TITLE
hosted/pub.dartlang.org/mobile_scanner-1.1.2/lib/src/mobile_scanner.dart:134:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.

### ISSUE THREAD

**Issue by devsig** [juliansteenbakker/mobile_scanner#172]
../../../.pub-cache/hosted/pub.dartlang.org/mobile_scanner-1.1.2/lib/src/mobile_scanner.dart:134:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Library/Android/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.removeObserver(this);

**Comment by juliansteenbakker** [comment]
Please use version 2.0.0
