### ISSUE TITLE
Unable to archive/publish app after update -Undefined symbol: _OBJC_CLASS_$_ ...

### ISSUE THREAD

**Issue by DualPeaks** [juliansteenbakker/mobile_scanner#173]
All works great until I updated to latest version of Flutter and mobile_scanner. 
App compiles to devices and simulators fine. Flutter run --release to iOS and Android works as expected and exports to both iOS and Android without issue.
however -
When I come to publish in Xcode and select 'any IOS Device (arm64, armv7) I get the attached errors. 

One of the full warming messages is:
Ignoring file /Users/DualPeaks/Documents/Development/Apps/Event_Marshal/event_marshal/ios/Pods/MLKitBarcodeScanning/Frameworks/MLKitBarcodeScanning.framework/MLKitBarcodeScanning, missing required architecture armv7 in file /Users/DualPeaks/Documents/Development/Apps/Event_Marshal/event_marshal/ios/Pods/MLKitBarcodeScanning/Frameworks/MLKitBarcodeScanning.framework/MLKitBarcodeScanning (2 slices)

'missing required architecture armv7 in file' seems to be the issue. 

This is very frustrating, been stuck for 4 days now unable to publish app and I am up against a deadline. If I remove mobile_scanner from the project it achieves just fine. Unfortunately I am on a deadline for this and need to get It resolved ASAP. Any help would be really good.

Let me know if you need any additional information. 

![Screenshot 2022-06-03 at 08 06 30](https://user-images.githubusercontent.com/73040689/171805207-1a0a0189-a0c6-4cb6-9a43-b6b9aba6ace0.png)

**Comment by justinmoon** [comment]
I'm experiencing a very similar issue. All the FFI functions created by flutter rust bridge (https://github.com/fzyzcjy/flutter_rust_bridge) have this error. But it works when we build for physical device.
![image](https://user-images.githubusercontent.com/4335621/172094468-e8093c4a-ccd1-442c-8a8a-f0ef2ef4ed9c.png)

**Comment by hieuruoi7797** [comment]
<img width="577" alt="Screen Shot 2022-06-06 at 14 59 01" src="https://user-images.githubusercontent.com/29893843/172120401-c9db24a1-5f0c-4c38-872c-3644fb3796e2.png">

try changing the Development Info -> IOS 11.0. It solves this problem.

**Comment by berkanaslan** [comment]
> <img alt="Screen Shot 2022-06-06 at 14 59 01" width="577" src="https://user-images.githubusercontent.com/29893843/172120401-c9db24a1-5f0c-4c38-872c-3644fb3796e2.png">
> 
> try changing the Development Info -> IOS 11.0. It solves this problem.

Verified solution. Thanks!

**Comment by Kobe-Paulo-Reis** [comment]
This issue is back again I'm using IOS 15.4 and getting the same error log

**Comment by juliansteenbakker** [comment]
Can you please try again with v3.0.0?
