### ISSUE TITLE
[Web] showing white screen when building with canvaskit

### ISSUE THREAD

**Issue by nohackjustnoobb** [juliansteenbakker/mobile_scanner#175]
I use the command below to build my project.
`flutter build web --web-renderer canvaskit `
When I test my app with my iPhone that running iOS 15.4, the area that supposes to show what the camera sees is showing a white screen. Surprisingly, it still scans QRcode correctly.

When I build the app with `flutter build web `, it works perfectly. 
It shows that it is a problem with the renderer.

(Sorry for my bad English)

**Comment by darekmm** [comment]
Same problem here.

**Comment by juliansteenbakker** [comment]
Im closing this because im cleaning out the issues. If this is still a problem please comment.
