### ISSUE TITLE
FATAL EXCEPTION: CameraX-core_camera_0

### ISSUE THREAD

**Issue by espitiajose** [juliansteenbakker/mobile_scanner#177]
E/AndroidRuntime(11276): FATAL EXCEPTION: CameraX-core_camera_0
E/AndroidRuntime(11276): Process: com.xxxxxxx.app., PID: 11276
E/AndroidRuntime(11276): java.lang.AssertionError: impossible
E/AndroidRuntime(11276): 	at java.lang.Enum$1.create(Enum.java:272)
E/AndroidRuntime(11276): 	at java.lang.Enum$1.create(Enum.java:262)
E/AndroidRuntime(11276): 	at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
E/AndroidRuntime(11276): 	at java.lang.Enum.getSharedConstants(Enum.java:289)
E/AndroidRuntime(11276): 	at java.lang.Class.getEnumConstantsShared(Class.java:2423)
E/AndroidRuntime(11276): 	at java.util.EnumSet.getUniverse(EnumSet.java:407)
E/AndroidRuntime(11276): 	at java.util.EnumSet.noneOf(EnumSet.java:109)
E/AndroidRuntime(11276): 	at java.util.EnumSet.of(EnumSet.java:283)
E/AndroidRuntime(11276): 	at androidx.camera.camera2.internal.b0.<clinit>(Unknown Source:8)
E/AndroidRuntime(11276): 	at androidx.camera.camera2.internal.D.<init>(Unknown Source:140)
E/AndroidRuntime(11276): 	at androidx.camera.camera2.internal.p.a(Unknown Source:34)
E/AndroidRuntime(11276): 	at u.J.b(Unknown Source:47)
E/AndroidRuntime(11276): 	at androidx.camera.core.F.b(:1)
E/AndroidRuntime(11276): 	at androidx.camera.core.D.run(Unknown Source:28)
E/AndroidRuntime(11276): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
E/AndroidRuntime(11276): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
E/AndroidRuntime(11276): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(11276): 	at java.lang.Thread.run(Thread.java:784)
E/AndroidRuntime(11276): Caused by: java.lang.NoSuchMethodException: values []
E/AndroidRuntime(11276): 	at java.lang.Class.getMethod(Class.java:2068)
E/AndroidRuntime(11276): 	at java.lang.Class.getDeclaredMethod(Class.java:2047)
E/AndroidRuntime(11276): 	at java.lang.Enum$1.create(Enum.java:268)
E/AndroidRuntime(11276): 	... 18 more

**Comment by juliansteenbakker** [comment]
This issue is probably fixed with #257. I will release this as version 3.0.0 after i'm done with a few other functions.
