### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by Jayden62** [juliansteenbakker/mobile_scanner#182]
Please, update border like qr-code-scanner. If i scan a product has multiple QR code, its crash.

**Comment by prasunsultania** [comment]
Can you provide example of code snippet or something to understand it more ?

When I used, multi-scan is working, but, I do see following issues:
- there are certain null scans, so, make sure your app is prepared to handle cases when `barcode.rawValue` is received as null.
- there is also an issue that it calls the `onDetect` callback multiple times for images with multiple qr codes, but there is no `onComplete` event or callback to understand if the entire image has been processed completely.

**Comment by juliansteenbakker** [comment]
This is fixed in v3.0.0.
