### ISSUE TITLE
Terrible scan results onAndroid

### ISSUE THREAD

**Issue by saulopef** [juliansteenbakker/mobile_scanner#189]
Hi, first of all, I don't tested this lib with a IOS physical device yet, but when testing with Android, I get some weird results on scan, with the same barcode, that is 2RD127177 the expected result,  I'm getting: 22RD... 277157177, and others changed characters, how can I improve the resolution, ou precision of the scan?

<img width="343" alt="image" src="https://user-images.githubusercontent.com/35967830/173637754-4280e42c-5d98-4f5b-a856-f414aa65596c.png">

**Comment by yuchan2215** [comment]
I think it is a known bug that is awaiting Google's fix.
I too would like to know how to fix it.

https://github.com/juliansteenbakker/mobile_scanner/issues/95

**Comment by juliansteenbakker** [comment]
Since there has been lots of updates, please check with latest version 3.0.0-beta.4 and comment if this issue still exists.
