### ISSUE TITLE
iOS torchState doesn't turn off when going into the background

### ISSUE THREAD

**Issue by devmobile-vulog** [juliansteenbakker/mobile_scanner#190]
When putting the ios application in background, the torch turns off but the value notifier keeps the TorchState.on value

**Comment by juliansteenbakker** [comment]
Im closing this because im cleaning out the issues. If this is still a problem please comment.

**Comment by rico237** [comment]
I am a developer working for the team of [devmobile-vulog](https://github.com/devmobile-vulog) and i confirm that the issue is gone with the latest version of the lib (3.0.0)
