### ISSUE TITLE
How to access "MobileScannerWeb: NotAllowedError: Permission denied"?

### ISSUE THREAD

**Issue by t-kietzmann** [juliansteenbakker/mobile_scanner#192]
I'm trying to implement a fallback screen when the user does not grant permisson for the camera. 
On mobile i'm doing this with the permisson_handler package.

On web i get already the message from your package:

"MobileScannerWeb: NotAllowedError: Permission denied"

How can i access this state?

Thanks in advance!
Tobi

**Comment by Carlchk** [comment]
Same issue

**Comment by craigbrown-nist** [comment]
Did you add this to web/index.html?

<script src="https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.min.js"></script>

**Comment by juliansteenbakker** [comment]
Since there has been lots of updates, please check with latest version 3.0.0-beta.4 and comment if this issue still exists.
