### ISSUE TITLE
I need Border for scan camera

### ISSUE THREAD

**Issue by pathaniasam** [juliansteenbakker/mobile_scanner#193]
### What
- while scanning QRCodes or barcodes, we need a border area for camera. it will scan a particular barcode from sheet.

**Comment by hnord-vdx** [comment]
Its being worked on #176

**Comment by teolemon** [comment]
@pathaniasam it seems that the feature has been implemented and merged, does that solve your issue ?

**Comment by rxviperx** [comment]
I need this badly as there might be other QR that's on the camera view
May I know which version it's in and any sample code as in which attribute we should set ?

**Comment by the-recondite** [comment]
It seems [juliansteenbakker:feature/scan-window](https://github.com/juliansteenbakker/mobile_scanner/tree/feature/scan-window) is not merged to master

**Comment by juliansteenbakker** [comment]
With version 3.0.0-beta.4 you can use an custom scanning area like shown in the example app: https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/lib/barcode_scanner_window.dart

Please note that this is still a beta so there can be breaking changes in the near future
