### ISSUE TITLE
App is crashing when i restart the app

### ISSUE THREAD

**Issue by priyankaborate** [juliansteenbakker/mobile_scanner#20]
Restarted application in 4,055ms.
I/flutter (16870): Scan something!
D/AndroidRuntime(16870): Shutting down VM
E/AndroidRuntime(16870): FATAL EXCEPTION: main
E/AndroidRuntime(16870): Process: dev.steenbakker.mobile_scanner_example, PID: 16870
E/AndroidRuntime(16870): java.lang.IllegalArgumentException: No supported surface combination is found for camera device - Id : 0.  May be attempting to bind too many use cases. Existing surfaces: [SurfaceConfig{configType=PRIV, configSize=PREVIEW}, SurfaceConfig{configType=YUV, configSize=ANALYSIS}] New configs: [androidx.camera.core.impl.ImageAnalysisConfig@4c34bff, androidx.camera.core.impl.PreviewConfig@18eb71e]
E/AndroidRuntime(16870): 	at androidx.camera.lifecycle.LifecycleCameraRepository.bindToLifecycleCamera(LifecycleCameraRepository.java:280)
E/AndroidRuntime(16870): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(16870): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(16870): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(16870): 	at android.app.ActivityThread.main(ActivityThread.java:5539)
E/AndroidRuntime(16870): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16870): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime(16870): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
D/AppTracker(16870): App Event: crash
E/RequestThread-0(16870): Timed out while waiting for request to complete.
W/CaptureCollector(16870): Preview buffers dropped for request: 0

**Comment by juliansteenbakker** [comment]
This is happening because the native side of the plugin does not get notified when a reload is happening, so the camera and scanner are still open, however the flutter process is restarted so the screen becomes black.

This issue is known by Flutter and tracked here: https://github.com/flutter/flutter/issues/10437

This is only happening with 'Hot restart' and should not happen in any other case.
