### ISSUE TITLE
Not able to scan a barcode from Air India boarding pass 

### ISSUE THREAD

**Issue by beamAkshay** [juliansteenbakker/mobile_scanner#201]
### What

- Not able to scan a barcode from Air India boarding pass

**Comment by teolemon** [comment]
@beamAkshay is it possible to provide a sample of such a barcode if it's not confidential ?

**Comment by beamAkshay** [comment]
![33112147_2035371993203953_8445636077540081664_n](https://user-images.githubusercontent.com/100898974/186585501-82e513b8-b806-4a27-97de-539ae9f65bb1.jpg)


You can check any air india boarding pass from google

**Comment by juliansteenbakker** [comment]
This is something i cant fix since the problem lays with googles MLKit scanner.
