### ISSUE TITLE
Does not scan after few times or blank black view

### ISSUE THREAD

**Issue by elmar001** [juliansteenbakker/mobile_scanner#203]
It works really good when opened first. Then does not respond to QR codes any more or does not even show camera view - shows blank black container. I noticed it prints - MobileScanner: Called stop() while already stopped! sometimes. Not sure if it is related. I wonder what is the best way to restart it without killing the app?

**Comment by uyingchuan** [comment]
I have the same problem, after black screen scan does not working

**Comment by juliansteenbakker** [comment]
Since there has been lots of updates, please check with latest version 3.0.0-beta.4 and comment if this issue still exists.
