### ISSUE TITLE
Can not analyze this QRCode

### ISSUE THREAD

**Issue by tbm98** [juliansteenbakker/mobile_scanner#207]
Running on android.
![20220626_224107.jpg](https://user-images.githubusercontent.com/52562340/175955545-ffc87504-3f08-4910-8baf-66353962f1cb.jpg)

**Comment by teolemon** [comment]
Can you analyze other QRCodes successfully @tbm98 ?

**Comment by tbm98** [comment]
@teolemon yes. I think problem is size of image file. I tried to compress this image to smaller file size and it work.

**Comment by juliansteenbakker** [comment]
I can't really do anything about it. The live scanner registers the image correctly.
