### ISSUE TITLE
Unhandled Exception: Invalid argument: Instance of 'Ratio'

### ISSUE THREAD

**Issue by Sachinsowri** [juliansteenbakker/mobile_scanner#209]
### What
- Not able use ratio name argument in MobileScannerController
how to use 4:3 view .?
- ```Unhandled Exception: Invalid argument: Instance of 'Ratio' ```

**Comment by teolemon** [comment]
- Potentially related: https://github.com/juliansteenbakker/mobile_scanner/issues/24
