### ISSUE TITLE
can not detect the qrCode if the background is dark

### ISSUE THREAD

**Issue by ViShadowFiend** [juliansteenbakker/mobile_scanner#210]
![image](https://user-images.githubusercontent.com/22252325/176609120-07c35b55-6655-4da6-bb4d-b0c962169453.png)
![image](https://user-images.githubusercontent.com/22252325/176609141-8f85ee97-23e5-4e9f-9724-ff5083f8fce3.png)
The above two qrCode have the same content, but the one above cannot be recognized

**Comment by Alan6th** [comment]
Same issue
