### ISSUE TITLE
The package is preventing me from copy-pasting my project

### ISSUE THREAD

**Issue by gizemgizg** [juliansteenbakker/mobile_scanner#213]
Hello, first of all, thank you very much for the package you developed. The package is preventing me from copy-pasting my project. Can you help me?

**Comment by gizemgizg** [comment]
![Ekran-Kaydı-2022-07-02-21 16 09](https://user-images.githubusercontent.com/64318805/177012167-866cf7be-36da-4316-8f08-5552f5bd695c.gif)

**Comment by ardakalayci** [comment]
Same issue

**Comment by juliansteenbakker** [comment]
I have tried creating an empty project, and adding mobile scanner as a dependency, however i am not able to reproduce this behavior. Can you provide an example? Also, when you are copying you seem to get a notification. I have tried it on a simulator with ios 15.5 but i don't get any notification and can copy/paste without any issues.

**Comment by gizemgizg** [comment]
I created a new flutter project. I have added a textformfield inside the container as a widget. I can't paste. This issue exists in versions above iOS 13.5. Xcode is up to date
mobile_scanner: ^2.0.0

<img width="589" alt="Ekran Resmi 2022-09-05 13 48 02" src="https://user-images.githubusercontent.com/64318805/188432574-0d0002c4-298a-46f2-a652-9676c96edb88.png">

**Comment by gizemgizg** [comment]
Can you help me? @juliansteenbakker

**Comment by gizemgizg** [comment]
The problem persists and I ran the app in Xcode. When I copy-paste, I get an error like this. @juliansteenbakker 

![image](https://user-images.githubusercontent.com/64318805/192062473-9a7469e7-f465-4c6b-ad2c-6a3ef011732c.png)

**Comment by kyeshmz** [comment]
It would be great to create a simple example repo
@gizemgizg

**Comment by kyeshmz** [comment]
Built without errors, had to `pod repo update` inside of the ios folder

**Comment by allanwolski-openco** [comment]
Same issue here.

**Comment by juliansteenbakker** [comment]
Can you please try again with version 3.0.0?
