### ISSUE TITLE
Error if phone does not have front camera

### ISSUE THREAD

**Issue by arnzuk** [juliansteenbakker/mobile_scanner#214]
Hi,

I am receiving fatal exeptions then phone does not have front camera. Package must check if front camera is available.

on startup:

E/CameraManager( 3637): writerFile e=java.io.FileNotFoundException: sys/devices/platform/soc/soc:gpio_flash/gpioflash: open failed: EACCES (Permission denied)
E/SystemUtil( 3637): /data/system/sim.properties doesn't exist,try to create it,some methods of this class will throw exception if create the file failed
W/System.err( 3637): java.io.IOException: Permission denied
W/CameraX-core_ca( 3637): type=1400 audit(0.0:329689): avc: denied { write } for name="gpioflash" dev="sysfs" ino=47063 scontext=u:r:untrusted_app:s0:c186,c256,c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0 app=com.example.asset_manager_prod
W/System.err( 3637): 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
W/System.err( 3637): 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
W/System.err( 3637): 	at java.io.File.createNewFile(File.java:1008)
W/System.err( 3637): 	at android.util.SystemUtil.<clinit>(SystemUtil.java:70)
W/System.err( 3637): 	at android.util.SystemUtil.updateCameraPropertyValue(SystemUtil.java:353)
W/System.err( 3637): 	at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:792)
W/System.err( 3637): 	at androidx.camera.camera2.internal.compat.CameraManagerCompatApi29Impl.openCamera(CameraManagerCompatApi29Impl.java:44)
W/System.err( 3637): 	at androidx.camera.camera2.internal.compat.CameraManagerCompat.openCamera(CameraManagerCompat.java:215)
W/System.err( 3637): 	at androidx.camera.camera2.internal.Camera2CameraImpl.openCameraDevice(Camera2CameraImpl.java:1040)
W/System.err( 3637): 	at androidx.camera.camera2.internal.Camera2CameraImpl.tryForceOpenCameraDevice(Camera2CameraImpl.java:979)
W/System.err( 3637): 	at androidx.camera.camera2.internal.Camera2CameraImpl.openInternal(Camera2CameraImpl.java:273)
W/System.err( 3637): 	at androidx.camera.camera2.internal.Camera2CameraImpl.tryAttachUseCases(Camera2CameraImpl.java:752)
W/System.err( 3637): 	at androidx.camera.camera2.internal.Camera2CameraImpl.lambda$attachUseCases$11$Camera2CameraImpl(Camera2CameraImpl.java:694)
W/System.err( 3637): 	at androidx.camera.camera2.internal.Camera2CameraImpl$$ExternalSyntheticLambda4.run(Unknown Source:4)
W/System.err( 3637): 	at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.workOnQueue(SequentialExecutor.java:231)
W/System.err( 3637): 	at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.run(SequentialExecutor.java:173)
W/System.err( 3637): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 3637): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 3637): 	at java.lang.Thread.run(Thread.java:923)

on closing:E/CameraManager( 3637): writerFile e=java.io.FileNotFoundException: sys/devices/platform/soc/soc:gpio_flash/gpioflash: open failed: EACCES (Permission denied)
E/SystemUtil( 3637): /data/system/sim.properties doesn't exist,try to create it,some methods of this class will throw exception if create the file failed
W/System.err( 3637): java.io.IOException: Permission denied
W/CameraX-core_ca( 3637): type=1400 audit(0.0:329689): avc: denied { write } for name="gpioflash" dev="sysfs" ino=47063 scontext=u:r:untrusted_app:s0:c186,c256,c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0 app=com.example.asset_manager_prod
W/System.err( 3637): 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
W/System.err( 3637): 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
W/System.err( 3637): 	at java.io.File.createNewFile(File.java:1008)
W/System.err( 3637): 	at android.util.SystemUtil.<clinit>(SystemUtil.java:70)
W/System.err( 3637): 	at android.util.SystemUtil.updateCameraPropertyValue(SystemUtil.java:353)
W/System.err( 3637): 	at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:792)
W/System.err( 3637): 	at androidx.camera.camera2.internal.compat.CameraManagerCompatApi29Impl.openCamera(CameraManagerCompatApi29Impl.java:44)
W/System.err( 3637): 	at androidx.camera.camera2.internal.compat.CameraManagerCompat.openCamera(CameraManagerCompat.java:215)
W/System.err( 3637): 	at androidx.camera.camera2.internal.Camera2CameraImpl.openCameraDevice(Camera2CameraImpl.java:1040)
W/System.err( 3637): 	at androidx.camera.camera2.internal.Camera2CameraImpl.tryForceOpenCameraDevice(Camera2CameraImpl.java:979)
W/System.err( 3637): 	at androidx.camera.camera2.internal.Camera2CameraImpl.openInternal(Camera2CameraImpl.java:273)
W/System.err( 3637): 	at androidx.camera.camera2.internal.Camera2CameraImpl.tryAttachUseCases(Camera2CameraImpl.java:752)
W/System.err( 3637): 	at androidx.camera.camera2.internal.Camera2CameraImpl.lambda$attachUseCases$11$Camera2CameraImpl(Camera2CameraImpl.java:694)
W/System.err( 3637): 	at androidx.camera.camera2.internal.Camera2CameraImpl$$ExternalSyntheticLambda4.run(Unknown Source:4)
W/System.err( 3637): 	at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.workOnQueue(SequentialExecutor.java:231)
W/System.err( 3637): 	at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.run(SequentialExecutor.java:173)
W/System.err( 3637): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 3637): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 3637): 	at java.lang.Thread.run(Thread.java:923)

E/AndroidRuntime( 3637): java.lang.IllegalArgumentException: Provided camera selector unable to resolve a camera for the given use case
E/AndroidRuntime( 3637): 	at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:470)
E/AndroidRuntime( 3637): 	at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:360)
E/AndroidRuntime( 3637): 	at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda-10(MobileScanner.kt:190)
E/AndroidRuntime( 3637): 	at dev.steenbakker.mobile_scanner.MobileScanner.$r8$lambda$sabvDajmNHk5NsaaoXEm5J9v-QY(Unknown Source:0)
E/AndroidRuntime( 3637): 	at dev.steenbakker.mobile_scanner.MobileScanner$$ExternalSyntheticLambda2.run(Unknown Source:14)
E/AndroidRuntime( 3637): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 3637): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3637): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 3637): 	at android.app.ActivityThread.main(ActivityThread.java:7697)
E/AndroidRuntime( 3637): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3637): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 3637): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

**Comment by juliansteenbakker** [comment]
Can you please try again with the latest version 3.0.0-beta.4, and check if the issue still persist. Otherwise feel free to comment.
