### ISSUE TITLE
Camera Start always at resume

### ISSUE THREAD

**Issue by josefwilfinger** [juliansteenbakker/mobile_scanner#215]
### What 
- The following code in "mobile_scanner.dart" starts the camera always if i resume the app. Even if i am at a point of the app where the widget is not visible.
- An autoresume boolean would be nice.
- I just accidently recognized that, because the indicator for the camera was always on.
- This is also a flutter issue, probably, because why shall a widget which is not visible get the didchangeapplifecyclestate?

Greetings and thx for the work you have done so far.
```
 @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    switch (state) {
      case AppLifecycleState.resumed:
        if (!controller.sStarting) controller.start();
        break;
      case AppLifecycleState.inactive:
      case AppLifecycleState.paused:
      case AppLifecycleState.detached:
        controller.stop();
        break;
    }
  }

```

**Comment by Allen-Guof** [comment]
Same issue, any update?

**Comment by mikairyuu** [comment]
Bump, annoying as hell and is still there in the beta releases

**Comment by juliansteenbakker** [comment]
Can you please try this with version 3.0.0?

**Comment by josefwilfinger** [comment]
yes done :)  Thx and sorry for the late response.
