### ISSUE TITLE
Operation aborted error on mobile Chrome / iOS (Flutter Web)

### ISSUE THREAD

**Issue by darekmm** [juliansteenbakker/mobile_scanner#222]
Scanning works fine in apps and web ran on desktop, but on mobile iOS Chrome it does not ask for a permission and shows black screen. Going to the dev console on the iPhone it shows this error: 

`LOG MobileScannerWeb: AbortError: The operation was aborted.`

The app was built with Canvaskit. Any way to solve?

**Comment by juliansteenbakker** [comment]
Can you please try again with version 3.0.0?
