### ISSUE TITLE
The scanner doesn't work in android emulator

### ISSUE THREAD

**Issue by zub0r** [juliansteenbakker/mobile_scanner#223]
I've created a fresh Flutter project, installed the package and added the example widget. 
Gradle settings:
```
        compileSdkVersion 32
        minSdkVersion 28
        targetSdkVersion 28
```

In android emulator the virtual scene is showed, but you can't move around as usual (it's frozen) and the "Press alt to move camera" text is flickering.
Anyone having the same issue? 
Any suggestions how to solve this would be appreciated. 

Thanks

**Comment by juliansteenbakker** [comment]
Can you please try again with latest version 3.0.0?

**Comment by sentd94** [comment]
@juliansteenbakker 
This is still happening in ^3.2.0.
