### ISSUE TITLE
How can I mock the lib ?

### ISSUE THREAD

**Issue by Ibessas** [juliansteenbakker/mobile_scanner#228]
### What
- I need to do some tests for the app i'm developing with this lib and i need to test the page where i'm using it, but i'm not being able to mock the lib and throw the "onDetect" function with a value.

**Comment by tda-thaovd** [comment]
why use just clone this lib, and add this to your project show you can use this locally

**Comment by juliansteenbakker** [comment]
This is out of the scope for me as a maintainer of this package but i hope someone else has an answer for you.

**Comment by dtruong27** [comment]
In the old version of the library, one could test the event handler `onDetect` by using a custom controller:

`
final customController = MobileScannerController();

final testWidget = MobileScanner(
  onDetect: (capture) {
    // code to be tested
  },
  controller: customController,
);

// Test Detection 1
customController.barcodesController.add(
  BarcodeCapture(barcodes: [Barcode(rawValue: '1234')]),
);
`

However, in recent releases, this approach is not anymore possible, as the  `barcodesController` property of `MobileScannerController` has been changed to be private.

**Comment by dtruong27** [comment]
Actually, it is still possible to test `onDetect` in the latest version. We can subclass the `MobileScannerController`:

```
class MockMobileScannerController extends MobileScannerController {
  final StreamController<BarcodeCapture> barcodesController =
      StreamController.broadcast();

  @override
  Stream<BarcodeCapture> get barcodes => barcodesController.stream;
}
```

And use it in the test:
```
final customController = MockMobileScannerController();

final testWidget = MobileScanner(
  onDetect: (capture) {
    // code to be tested
  },
  controller: customController,
);

// Test Detection 1
customController.barcodesController.add(
    BarcodeCapture(
      barcodes: [
        Barcode(
          rawValue: 'invalid data',
        )
      ],
      raw: '',
    ),
  );
```
