### ISSUE TITLE
macOS library does not set BarcodeFormat

### ISSUE THREAD

**Issue by russellsteadman** [juliansteenbakker/mobile_scanner#230]
The macOS code does not transform `VNBarcodeObservation.barcodeDescriptor` to a `BarcodeFormat`, so all codes scanned on macOS appear to be `ean13`, the default. See [the macOS library barcode extraction](https://github.com/juliansteenbakker/mobile_scanner/blob/ff410a16ec7048d88e0d83bb5aed517fbf39664d/macos/Classes/MobileScannerPlugin.swift#L111) for context.

**Comment by navaronbracke** [comment]
This seems to be no longer the case in the current MacOS implementation, as it maps each symbology to transferable integers for the plugin:

https://github.com/juliansteenbakker/mobile_scanner/blob/master/macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift#L637-L704
