### ISSUE TITLE
Feature request : create setter for lastscanned

### ISSUE THREAD

**Issue by jodymac** [juliansteenbakker/mobile_scanner#234]
- My use case is I am using mobile_scanner on an iPad to check in users with key fobs that have a bar code.  Allow duplicates = false works perfectly but my situation needs the ability for occasional duplicates as one of the membership options is to buy punches that allow them to use one card(same barcode) for 4 family members to come in and use the facility.
- There is a secondary screen that will show on successful recognition of a valid barcode.  Upon returning from that screen, I would like to set the lastScanned value to a number we don't use or even barcode.rawValue to a number we don't use.
- I see lastScanned in MobileScanner class and I see other created issues where setting barcode.rawValue was an option at one point.  barcode.rawValue is a final variable so I can't change that (Flutter 3+) and if lastScanned is accessible, I'm not seeing that.
- My feature request is to make either of those accessible so that I have the option to allow a certain type of user to scan the same barcode again with a manual set of lastScanned upon return from the secondary screen while keeping the allow duplicates = false intact.

**Comment by divan** [comment]
That's certainly needed feature. In my use case I do want to keep `allowDuplicates=false` behavior, but after successful scan show some result screen and allow user to go back and scan again (the same QR code).

It would be easily achievable if lastScanned can be reset manually.

Related: https://github.com/juliansteenbakker/mobile_scanner/issues/58

**Comment by juliansteenbakker** [comment]
The whole duplicates function has been refactored. Please see https://github.com/juliansteenbakker/mobile_scanner/blob/5ebc65e96e8de7224e3a7265d388a8d5d00ee3fd/lib/src/mobile_scanner_controller.dart#L59
