### ISSUE TITLE
macos failed to open camera (chrome on same mac works)

### ISSUE THREAD

**Issue by imoldfella** [juliansteenbakker/mobile_scanner#236]
flutter: MobileScanner: No camera found or failed to open camera!
Lost connection to device.
jim@JamessMacStudio example % 
jim@JamessMacStudio example % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

Camera works fine in the web version on same machine. very cool! In Macos I get a popup asking for permission to use the camera, I say ok, then the message that it failed. In security and privacy all the apps are checked, mobile_scanner doesn't show. I approved terminal and visual studio code and those are both checked.

**Comment by tomsun** [comment]
oh nice, @nilsreichardt just added this step to README a week ago- it doesn't mention the plists or the word entitlements, instead it points out the xcode ui way to do the same.. at least it is there 👍 https://github.com/juliansteenbakker/mobile_scanner/commit/ee08cc8cc892c2aa3b9219bd944313bd7559d859

(has not propagated to https://pub.dev/packages/mobile_scanner yet, so I didn't see it)
