### ISSUE TITLE
Scan and overlay parameters

### ISSUE THREAD

**Issue by rdrgbaioco** [juliansteenbakker/mobile_scanner#250]
Is there a possibility that this package has a parameter and overlay like the old package, where it only captures the codes inside the overlay?

**Comment by rdrgbaioco** [comment]
I tried this for some time, but it captures the code in any area of the screen, and if you decrease the size of the camera area, it is visually bad

**Comment by casvanluijtelaar** [comment]
being worked on [here](https://github.com/juliansteenbakker/mobile_scanner/tree/feature/scan-window) (functional IOS, alpha android). if you don't care about being able to scan outside the window you can work from [this](https://github.com/juliansteenbakker/mobile_scanner/blob/feature/scan-window/example/lib/barcode_scanner_window.dart) example
