### ISSUE TITLE
Scanner closes unexpectedly in TabBarView

### ISSUE THREAD

**Issue by ChinHairSaintClair** [juliansteenbakker/mobile_scanner#266]
Good day,

I'm attempting to create something along the lines of the below image

![image](https://user-images.githubusercontent.com/41445931/186731753-685006d7-aa11-46b4-accd-d57792d8b690.png)

However, nesting the mobile scanner within a TabBarView has caused some unexpected behavior.
Just swiping from side to side works as expected (when AutomaticKeepAliveClientMixin is used ).
Clicking on the `MY CODE` tab button and then swiping back to the `SCAN CODE`, causes the scanner to stop and display a white screen (as shown below).

![image](https://user-images.githubusercontent.com/41445931/186734273-70d05109-604d-45d0-9e23-39fb141ea2f1.png)
![image](https://user-images.githubusercontent.com/41445931/186734377-9b7455ef-d785-43a2-9e6d-b7b864d7328d.png)
![image](https://user-images.githubusercontent.com/41445931/186734496-1d12799d-1974-4656-a167-adb8ae7a1464.png)

QR code screen content:

```
Scaffold(
  appBar: AppBar(
    title: const Text('QR code'),
    actions: [],
    bottom: TabBar(
      controller: _tabController,
      tabs: const [
        SizedBox(child: Tab(text: 'MY CODE')),
        SizedBox(child: Tab(text: 'SCAN CODE')),
      ],
    ),
  ),
   body: TabBarView(
      controller: _tabController,
      children: <Widget>[
        const Center(
          child: Text('MY CODE'),
        ),
        ScannerWrapper(
          scannerController: _scannerController,
          onDetect: _onDetect,
        )
      ],
    ),
)
```

Scanner wrapper:
```
typedef OnDetect = Function(Barcode barcode, MobileScannerArguments? args);
class ScannerWrapper extends StatefulWidget {
  final MobileScannerController scannerController;
  final OnDetect onDetect;
  const ScannerWrapper({Key? key, required this.scannerController, required this.onDetect}) : super(key: key);

  @override
  _ScannerWrapperState createState() => _ScannerWrapperState();
}

class _ScannerWrapperState extends State<ScannerWrapper> with AutomaticKeepAliveClientMixin{
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Stack(
      children: [
        MobileScanner(
          controller: widget.scannerController,
          onDetect: widget.onDetect,
          allowDuplicates: false,
        ),
        QRScannerOverlay(overlayColour: Colors.black.withOpacity(0.7))
      ],
    );
  }

  @override
  bool get wantKeepAlive => true;
}
```

Is there a way around this?

**Comment by juliansteenbakker** [comment]
Please try again with v3.0.0 and `startDelay` parameter.
