### ISSUE TITLE
Get QR code's value from images?

### ISSUE THREAD

**Issue by searene** [juliansteenbakker/mobile_scanner#267]
Hi,

Thanks for creating this fantastic library! I noticed that `mobile_scanner` could check if an image was a QR code via the `MobileScannerController#analyzeImage` method. However, I'm surprised to notice that the method's return value is only a `bool`. What if I want to get the QR code's rawValue from it? Is there any way to obtain that value?

Thanks.

**Comment by aasif129700** [comment]
You can get the value from the controller after analyzeImage() method turns true using the line below.
                       await controller.barcodes.first.then((value) {
                                            print(value.rawValue);
                      });

**Comment by juliansteenbakker** [comment]
The barcode will be returned in the normal `onDetect` function.
