### ISSUE TITLE
Allow Duplicates

### ISSUE THREAD

**Issue by krisnachy** [juliansteenbakker/mobile_scanner#271]
### What
- Hi, I want to ask, 
since this library provide to allow scan duplicate data, 
can i give timer for next scan? 
cause every time i hit api with allowduplicate true, it will always hit until i remove the code from the scanner
Thank you

**Comment by ArthurVinbeau** [comment]
I did a simple workaround using a boolean to allow scans :
```dart
void _onDetect(Barcode barcode, MobileScannerArguments? args) {
    if (canScan) {
        canScan = false;
        // ...
        Future.delayed(const Duration(milliseconds: 500), () => canScan = true)
    }
}
```
In my case the `Future.delayed` was placed in a `whenComplete` block after the `Future` called inside the `if` block

**Comment by khare4** [comment]
> 
will this stops the multiple scan at the same time? 
and allow scan after some period of time?
