### ISSUE TITLE
qr code not scanning in dark mode

### ISSUE THREAD

**Issue by lan2001** [juliansteenbakker/mobile_scanner#272]
`mobile_scanner 2.0.0`

Describe the bug
Qr code not scanning in dark mode
that same Qr code scanning without dark mode

QR code picture
![a6baeda83bc4104045a1a67b4d43b6f](https://user-images.githubusercontent.com/29707716/187340922-080224b9-49c5-4809-8fbe-46b53f6b0951.png)

**Comment by juliansteenbakker** [comment]
I think this is because there should be a white edge around the qr code, otherwise the scanner can't read the edge blocks correctly. This is not something i can fix in the scanner.

**Comment by norisfrigidiano40-dot** [comment]
WI-FI passwordo

**Comment by norisfrigidiano40-dot** [comment]
WI-FI 2026

**Comment by norisfrigidiano40-dot** [comment]
![Image](https://github.com/user-attachments/assets/3608010c-b2f1-4eb2-b91c-fbc0b4b7ea14)

**Comment by norisfrigidiano40-dot** [comment]
![Image](https://github.com/user-attachments/assets/ec1a136a-f477-48d7-b710-c54f866f7113)
