### ISSUE TITLE
(lldb) dyld[29369]: Library not loaded: '@rpath/libswiftCore.dylib'

### ISSUE THREAD

**Issue by Story5** [juliansteenbakker/mobile_scanner#277]
After install this plugin and then run flutter app on iOS device, it crash on the error

> (lldb) dyld[29369]: Library not loaded: '@rpath/libswiftCore.dylib'

Remove this plugin and run flutter app on iOS well without crash

**Comment by juliansteenbakker** [comment]
Can you please try this: https://stackoverflow.com/a/26949219
