### ISSUE TITLE
Mobile Scanner Overlay

### ISSUE THREAD

**Issue by alfredoptarigan** [juliansteenbakker/mobile_scanner#284]
This package support mobile overlay? I check on example mobile_scanner_overlay but it's not work.
![image](https://user-images.githubusercontent.com/62396803/189466075-05e744b5-2d35-4dbc-b92f-2be6071d7891.png)

**Comment by nithish-knetworks** [comment]
For me also. I need also an overlay like "qr_code_scanner". Please provide some examples.

**Comment by Kolovrat19** [comment]
[https://github.com/juliansteenbakker/mobile_scanner/tree/feature/scan-window](url)

**Comment by karsonbraaten** [comment]
do we know if there are any plans for this feature to be released? looks like the branch hasn't been updated in awhile

**Comment by EArminjon** [comment]
Up

**Comment by juliansteenbakker** [comment]
With version 3.0.0-beta.4 you can use an custom scanning area like shown in the example app: https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/lib/barcode_scanner_window.dart

Please note that this is still a beta so there can be breaking changes in the near future.
