### ISSUE TITLE
Android's first authorization crashed, and the app can be used normally for the second time

### ISSUE THREAD

**Issue by Jovines** [juliansteenbakker/mobile_scanner#29]
D/AndroidRuntime(27303): Shutting down VM
E/AndroidRuntime(27303): FATAL EXCEPTION: main
E/AndroidRuntime(27303): Process: com.emergence.friend.emergence, PID: 27303
E/AndroidRuntime(27303): java.lang.IllegalArgumentException: No supported surface combination is found for camera device - Id : 0.  May be attempting to bind too many use cases. Existing surfaces: [SurfaceConfig{configType=PRIV, configSize=PREVIEW}, SurfaceConfig{configType=YUV, configSize=ANALYSIS}] New configs: [androidx.camera.core.impl.ImageAnalysisConfig@16ae728, androidx.camera.core.impl.PreviewConfig@9be914b]
E/AndroidRuntime(27303): 	at androidx.camera.lifecycle.LifecycleCameraRepository.bindToLifecycleCamera(LifecycleCameraRepository.java:280)
E/AndroidRuntime(27303): 	at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:532)
E/AndroidRuntime(27303): 	at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:360)
E/AndroidRuntime(27303): 	at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda-10(MobileScanner.kt:167)
E/AndroidRuntime(27303): 	at dev.steenbakker.mobile_scanner.MobileScanner.lambda$bSd8nrsVH5fdvjvM1z6JkCPAiuY(Unknown Source:0)
E/AndroidRuntime(27303): 	at dev.steenbakker.mobile_scanner.-$$Lambda$MobileScanner$bSd8nrsVH5fdvjvM1z6JkCPAiuY.run(Unknown Source:14)
E/AndroidRuntime(27303): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(27303): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(27303): 	at android.os.Looper.loopOnce(Looper.java:210)
E/AndroidRuntime(27303): 	at android.os.Looper.loop(Looper.java:299)
E/AndroidRuntime(27303): 	at android.app.ActivityThread.main(ActivityThread.java:8087)
E/AndroidRuntime(27303): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27303): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/AndroidRuntime(27303): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
D/OOMEventManagerFK(27303): checkEventAndDumpForJE: 0
D/Camera2CameraImpl(27303): {Camera@bb300fe[id=0]} Resetting Capture Session
D/Camera2CameraImpl(27303): {Camera@bb300fe[id=0]} Releasing session in state INITIALIZED
D/Camera2CameraImpl(27303): {Camera@bb300fe[id=0]} Attempting to force open the camera.
D/CameraStateRegistry(27303): tryOpenCamera(Camera@bb300fe[id=0]) [Available Cameras: 1, Already Open: false (Previous state: null)] --> SUCCESS
D/CameraStateRegistry(27303): Recalculating open cameras:
D/CameraStateRegistry(27303): Camera                                       State                 
D/CameraStateRegistry(27303): -------------------------------------------------------------------
D/CameraStateRegistry(27303): Camera@a5431d6[id=1]                         UNKNOWN               
D/CameraStateRegistry(27303): Camera@bb300fe[id=0]                         OPENING               
D/CameraStateRegistry(27303): -------------------------------------------------------------------
D/CameraStateRegistry(27303): Open count: 1 (Max allowed: 1)
D/Camera2CameraImpl(27303): {Camera@bb300fe[id=0]} Opening camera.
D/Camera2CameraImpl(27303): {Camera@bb300fe[id=0]} Transitioning camera internal state: INITIALIZED --> OPENING
D/CameraStateMachine(27303): New public camera state CameraState{type=OPENING, error=null} from OPENING and null
D/CameraStateMachine(27303): Publishing new public camera state CameraState{type=OPENING, error=null}
D/UseCaseAttachState(27303): All use case: [androidx.camera.core.Preview-73ae3a3d-2b65-44e3-bcf5-c2c21bc11a07187728793, androidx.camera.core.ImageAnalysis-aaa90afa-05f1-4e35-a0ae-0ca5d1e2d11c219600478] for camera: 0
W/libc    (27303): Access denied finding property "persist.vendor.camera.privapp.list"
D/CameraExtImplXiaoMi(27303): initCameraDevice: 0
I/Process (27303): Sending signal. PID: 27303 SIG: 9
Lost connection to device.

**Comment by myoganugraha** [comment]
have created pr to fix this issue, [the pr](https://github.com/juliansteenbakker/mobile_scanner/pull/27)

will wait for the maintainer to test and approve it

**Comment by Jovines** [comment]
> 

Thank you very much. It worked!!

**Comment by juliansteenbakker** [comment]
Thanks, i've merged it and will release it asap.

**Comment by daveshirman** [comment]
What is the correct way to install this with the pr above in flutter please? 
I.e. what terminal command / pubspec.yaml line is necessary?

Thanks.

**Comment by myoganugraha** [comment]
@daveshirman you can reference to the repo

```
mobile_scanner:
    git:
      url: https://github.com/juliansteenbakker/mobile_scanner.git
```

if you need reference to another branch, you could add ref argument
