### ISSUE TITLE
[Enhancement] Optionally return InputImage to be further used with other ML Kit libraries

### ISSUE THREAD

**Issue by iklochko** [juliansteenbakker/mobile_scanner#301]
Hello.

Thank you for developing and supporting this amazing library!
I use it to scan barcodes, including ITF, which is reported to be scanned unstable, and it really is.
Luckily, in my case i have this barcode duplicated with symbols under it.
I've managed to succeed obtaining good results in following way:
1. I receive the Barcode from mobile_scanner. returnImage is not working on Android, and it's crashing the app on iOS sometimes (added some details [here](https://github.com/juliansteenbakker/mobile_scanner/issues/241#issuecomment-1252487528))
2. Then, I have to stop the scanner and use another lib to take a photo.
3. Then I use [google_mlkit_text_recognition](https://pub.dev/packages/google_mlkit_text_recognition) to match Barcode with text recognized. I have to save photo to directory to convert in to [InputImage](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_commons#creating-an-inputimage) used by ML Kit.
4. This in general works fine, but there are some performance issues on old devices or many simulate recognitions.

So, I wonder, if mobile_scanner also use ML Kit under the hood and it also obtains InputImage to recognize barcode, will you please consider a possibility to add an option to return InputImage with scan results?

Best regards

**Comment by juliansteenbakker** [comment]
With version 3.0.0-beta.4 you can retrieve the scanned image like so: https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/lib/barcode_scanner_returning_image.dart

Please note that this is still a beta so there can be breaking changes in the near future
