### ISSUE TITLE
Scanning barcode with a black background

### ISSUE THREAD

**Issue by gani12** [juliansteenbakker/mobile_scanner#305]
Hi,
We are using this plugin in one of our APP to scan a barcode ( vehicle VIN number). It is working perfectly for a white color car. But if the car color is black or any other darker color it is having trouble scanning. It takes time to scan and also it is not consistent. Sometimes takes 3 seconds and sometimes 10 seconds.  Is there a setting in the plugin adjust for this case. 
![barcode_car](https://user-images.githubusercontent.com/28710514/192366511-4bf19f12-3c25-4272-93f5-e8275e925e40.jpg)

Ganesan

**Comment by juliansteenbakker** [comment]
Right now there is nothing to change this. It would however be an option to invert the image colour first before passing it trough the analyzer.

**Comment by ThiemoImgraben** [comment]
Are there any updates or workarounds ?

**Comment by juliansteenbakker** [comment]
Im closing this because there is not much to do for now.
