### ISSUE TITLE
Release new version with Android Camera native fix

### ISSUE THREAD

**Issue by alfredo-handcash** [juliansteenbakker/mobile_scanner#307]
Hi! First of all, thanks for your time creating this package, is amazing and we are very we are very grateful for getting this package.

We have [this issue](https://github.com/juliansteenbakker/mobile_scanner/issues/255) with your package and Passbase package and we found that using the git URL in dependencies works fine! So can you release a new version with the current codebase to avoid git dependencies?

Thanks for all!

**Comment by juliansteenbakker** [comment]
I've released v3.0.0-beta.1 which has all these fixes. After some users have verified that its stable i will release a stable version.
