### ISSUE TITLE
Scanned code is incorrect sometimes

### ISSUE THREAD

**Issue by bigBoy-mm** [juliansteenbakker/mobile_scanner#313]
Hello, I've noticed that scanned code is incorrect sometimes. I've attached some example bellow when I try to scan barcode 39. The issue is on both mobile platform (android and iOS).

https://barcode.tec-it.com/barcode.ashx?data=356471T116&code=Code39

> I/flutter (15732): scanned Code 356471T116
I/flutter (15732): scanned Code 356471T116
I/flutter (15732): scanned Code 356471S116
I/flutter (15732): scanned Code 356 X1T116
I/flutter (15732): scanned Code 3564X1T116
I/flutter (15732): scanned Code 356471T116
I/flutter (15732): scanned Code 356471T116
I/flutter (15732): scanned Code 356471T116
I/flutter (15732): scanned Code 356471T116
I/flutter (15732): scanned Code 356471T116

**Comment by noga-dev** [comment]
It's an issue with MLKit's ITF scanning. Also present in latest.

Both of these have the same issue:
1. ```https://mvnrepository.com/artifact/com.google.android.gms/play-services-mlkit-barcode-scanning```
2. ```https://mvnrepository.com/artifact/com.google.mlkit/barcode-scanning```

**Comment by bigBoy-mm** [comment]
Ok, but as I mentioned the issue is also on iOS.

**Comment by peukerjonathan** [comment]
I also noticed this "issue". A possible approach for me is to buffer the scaned result. Only when I receive the same result 5 times in a row I pass the result  on to my actual handler.
Maybe this is something that could be added to the package as a parameter. "Result Confidenve Lvl" or something like that.

**Comment by nick990** [comment]
> I also noticed this "issue". A possible approach for me is to buffer the scanned result. Only when I receive the same result 5 times in a row I pass the result on to my actual handler. Maybe this is something that could be added to the package as a parameter. "Result Confidenve Lvl" or something like that.

I noticed that even the wrong result is scanned multiple times, it happens especially during camera focusing.
My approach is the following:

- Enable duplicates 
 ``allowDuplicates: true``
- From the first scanned barcode, save all the scanned barcodes with their occurences
- After a second pass the most frequent result to the actual handler

**Comment by juliansteenbakker** [comment]
I'm closing for now since lots of code has changed with version 3.0.0-beta.4.
