### ISSUE TITLE
Not building for android and iOS

### ISSUE THREAD

**Issue by bibash28** [juliansteenbakker/mobile_scanner#314]
![image](https://user-images.githubusercontent.com/18188709/193248572-9c8478d6-b3b3-4c65-a9cd-8205c5ebb7fd.png)

Android output:
![image](https://user-images.githubusercontent.com/18188709/193248654-42637476-2afc-46c4-9dfe-c4c5595d8e3f.png)

iOS Output for platform :ios, '13.0'
![image](https://user-images.githubusercontent.com/18188709/193249311-4c56facf-8797-42c9-bfc7-2fbb7d0ea7a2.png)

**Comment by juliansteenbakker** [comment]
Are you using the beta version? This version is currently only supported by the latest flutter release because of a missing import. I will see if i can get it back for the next release but for now i recommend updating to latest flutter or reverting back to version 2.0.0

**Comment by bibash28** [comment]
Thanks.. it worked with latest flutter version...

**Comment by nilsreichardt** [comment]
@juliansteenbakker In this case, you can use the flutter constrains in the `pubspec.yaml` like:

```yaml
environment:
  sdk: ...
  flutter: "=< 3.3.3"
```
