### ISSUE TITLE
mobile_scanner package conflicts with google_mlkit_face_detection

### ISSUE THREAD

**Issue by allanwolski-openco** [juliansteenbakker/mobile_scanner#319]
Hi all, thanks for the efforts in making this package.

I tried with mobile_scanner 3.0.0-beta.1 too, but GoogleMLKit/BarcodeScanning is 3.2.0 and GoogleMLKit/FaceDetection is 3.1.0.

```
  In Podfile:
    google_mlkit_commons (from `.symlinks/plugins/google_mlkit_commons/ios`) was resolved to 0.2.0, which depends on
      MLKitVision

    google_mlkit_face_detection (from `.symlinks/plugins/google_mlkit_face_detection/ios`) was resolved to 0.4.0, which depends on
      GoogleMLKit/FaceDetection (~> 3.1.0) was resolved to 3.1.0, which depends on
        MLKitFaceDetection (~> 2.1.0) was resolved to 2.1.0, which depends on
          MLKitVision (~> 4.1)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 0.0.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 2.6.0) was resolved to 2.6.0, which depends on
        MLKitBarcodeScanning (~> 1.7.0) was resolved to 1.7.0, which depends on
          MLKitVision (~> 3.0)
```

**Comment by juliansteenbakker** [comment]
You should run `pod update` in your ios directory. The version defined in this package is the latest version: 
` s.dependency 'GoogleMLKit/BarcodeScanning', '~> 3.2.0'`
https://github.com/juliansteenbakker/mobile_scanner/blob/master/ios/mobile_scanner.podspec

**Comment by allanwolski-openco** [comment]
The `google_mlkit_face_detection` package has been updated.
https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/356
