### ISSUE TITLE
Start/Stop from Camera Controller firing error

### ISSUE THREAD

**Issue by geovaniprodata** [juliansteenbakker/mobile_scanner#320]
I was searching for a method that can stop and start the camera, found it in cameraController but .... the error below keeps poping up when trigger the start( )

"'hashCode == _controllerHashcode': MobileScannerController.startAsync called after MobileScannerController.dispose
MobileScannerController methods should not be used after calling dispose.)"

and there's no dispose on my code, after the exception with  hot reload it works...

**Comment by geovaniprodata** [comment]
I found it that the CameraController its the source of the problem, without it works pretty fine..

**Comment by berdibekovaG** [comment]
the same error

**Comment by jedwiwat** [comment]
Try this one, put controller inside build function

@override
  Widget build(BuildContext context) {
    MobileScannerController cameraController = MobileScannerController();

**Comment by juliansteenbakker** [comment]
Can you please try this again with version 3.0.0?
