### ISSUE TITLE
mobile_scanner-3.0.0-beta.1 - ISO8601DateFormatter Issue while running the app on simulator

### ISSUE THREAD

**Issue by Komal-Khairnar** [juliansteenbakker/mobile_scanner#324]
Swift Compiler Error (Xcode): Value of type 'Date' has no member 'rawValue'
/Users/komalkhairnar/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/mobile_scanner-3.0.0-beta.1/ios/Classes/Util.swift:86:61
2

Swift Compiler Error (Xcode): Value of type 'Date' has no member 'rawValue'
/Users/komalkhairnar/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/mobile_scanner-3.0.0-beta.1/ios/Classes/Util.swift:86:133

Swift Compiler Error (Xcode): 'ISO8601DateFormatter' is only available in iOS 10.0 or newer
/Users/komalkhairnar/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/mobile_scanner-3.0.0-beta.1/ios/Classes/Util.swift:92:15

Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

**Comment by juliansteenbakker** [comment]
It seems like your app has an minimum deployment lower than 11, which is not supported by flutter. Please upgrade to 11 or higher.
