### ISSUE TITLE
Random PlatformException thrown

### ISSUE THREAD

**Issue by vlazdra** [juliansteenbakker/mobile_scanner#327]
First of all, thank you very much for doing the work on this library. It does helps the community, a lot! 👍 

I wanted to report something weird, the library is throwing some PlatformException errors:

```
════════ Exception caught by services library ══════════════════════════════════
The following PlatformException was thrown while de-activating platform stream on channel dev.steenbakker.mobile_scanner/scanner/event:
PlatformException(error, No active stream to cancel, null, null)

When the exception was thrown, this was the stack
#0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:653
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:296
<asynchronous suspension>
#2      EventChannel.receiveBroadcastStream.<anonymous closure>
package:flutter/…/services/platform_channel.dart:649
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════
```

I'm not doing anything special, literally happens at random. Sometimes happens when sending the app to the background, sometimes happens by just removing the widget from view.

Mobile scanner version: 2.0.0.
Flutter version: 3.3.4.
Occurs on both Android and iOS, multiple different OS versions.

If there's anything else I can provide please do let me know.

**Comment by fasterlars** [comment]
I am having the same issue.
Mobile scanner version: 2.0.0.
Flutter version: 3.3.6
Have only tested on Android.

**Comment by juliansteenbakker** [comment]
Because of problems in state management in version 2.0.0 this error could occur. Please check version 3.0.0-beta.2 and try again.

**Comment by vlazdra** [comment]
Hey @juliansteenbakker thank you for the info, and for a huge refactor of the codebase.

I will leave this one open, since it was occurring that often in development as it was when released.
As soon as I'm able to update to 3.0.0-beta.2 I will give it a go, and see if this issue presents itself.

Will make sure to leave a comment once I do.

And again, thanks for the work you're doing.

**Comment by juliansteenbakker** [comment]
I'm closing this for now since i think version 3.0.0-beta.4 does not have this issue.
