### ISSUE TITLE
The beta version is firing on duplicates

### ISSUE THREAD

**Issue by vlazdra** [juliansteenbakker/mobile_scanner#328]
I've noticed that when using the beta version 3.0.0-beta.1, the duplicate check doesn't work properly.

This behaviour results in duplicate values being sent even though the initial setup was not to send anything.

**Comment by juliansteenbakker** [comment]
Can you please checkout v3.0.0-beta.2 which has a new duplicate detection.

**Comment by vlazdra** [comment]
Wow, that's a big change. Of almost everything! :)

I'm going to give this new beta version a go, and see how it behaves.

In the meantime, I'm closing this issue, and the PR.
