### ISSUE TITLE
cannot scan after release apk

### ISSUE THREAD

**Issue by taufiqjack** [juliansteenbakker/mobile_scanner#337]
can't scan QRcode after release in Android

#android

**Comment by peukerjonathan** [comment]
Which release are you using? If you are using a "-play-services" release it is possible that the device you are attempting to scan on did not properly download the dependency and therefore codes cannot be recognized. (https://developers.google.com/ml-kit/vision/barcode-scanning/android)

Is the problem present with the v2.0.0 release / the v3.0.0-beta release?

**Comment by taufiqjack** [comment]
thankz its work

**Comment by taufiqjack** [comment]
thankz its work
