### ISSUE TITLE
Is there a built in way to set a focus zone ?

### ISSUE THREAD

**Issue by MB175** [juliansteenbakker/mobile_scanner#343]
Is there a already built in way to configure a focus zone, so the scanner only operates in a certain area of the camera view finder ?

**Comment by teolemon** [comment]
We're going to need arbitrary focus for @openfoodfacts @juliansteenbakker 
We have the option to implement it here with CameraX, but there's also the more future proof option to switch mobile_scanner to the newly released camera_android_camerax (0.5) pub.dev package which switches to CameraX (bringing arbitrary focus for free), and would reduce maintenance cost of mobile_scanner.

 https://pub.dev/packages/camera_android_camerax

**Comment by juliansteenbakker** [comment]
Since we scan with a scan window, i'm closing this issue.
