### ISSUE TITLE
Make barcode types selectable

### ISSUE THREAD

**Issue by jahnli** [juliansteenbakker/mobile_scanner#35]
Thank you for your contribution   I'm migrating a project from qr_code_scanner to this ,but Lack of specific area and bar code type support

**Comment by jahnli** [comment]
Seems to be missing the onPermissionSet call back

**Comment by juliansteenbakker** [comment]
Hello, the specific area is already tracked in #11. So this will be just for selecting barcode types.

**Comment by jahnli** [comment]
@juliansteenbakker    Expect when functionality will be available
