### ISSUE TITLE
How to customize detect camera frame?

### ISSUE THREAD

**Issue by 96Demo** [juliansteenbakker/mobile_scanner#355]
****
Dear team,
I hope you are fine and doing well.
It's not a issue but just a request,
Could you help to implment the  customize detect camera frame with blur background as qr_code_scanner package have?
This package is working fine, but it should have that customize detect camera frame which it's more better.

Thank you!

**Comment by kaciula** [comment]
@DJTB The scanner will still scan the entire area however. What's really needed is for the scanner to only scan the selected area from the camera frame.

**Comment by juliansteenbakker** [comment]
With version 3.0.0-beta.4 you can use an custom scanning area like shown in the example app: https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/lib/barcode_scanner_window.dart 

Please note that this is still a beta so there can be breaking changes in the near future.
