### ISSUE TITLE
crash on iOS

### ISSUE THREAD

**Issue by Adrift001** [juliansteenbakker/mobile_scanner#361]
Thread 1: "<mobile_scanner.MobileScanner: 0x2802d1810>: An -observeValueForKeyPath:ofObject:change:context: message was received but not handled.\nKey path: torchMode\nObserved object: <AVCaptureFigVideoDevice: 0x1048fb000 [Back Camera][com.apple.avfoundation.avcapturedevice.built-in_video:0]>\nChange: {\n    kind = 1;\n    new = 0;\n}\nContext: 0x0"

**Comment by Adrift001** [comment]
download this repository and run on iPhone, This error occurred.

**Comment by juliansteenbakker** [comment]
Can you please try v3.0.0-beta.2.

**Comment by tangyiyong** [comment]
with v3.0.0-beta.2, It also crash. When I select the button, the light flash once, and the app crash.

**Comment by nick990** [comment]
I'm testing version v3.0.0-beta.2.
The app crash on the last instruction of method `MobileScannerController.toggleTorch()` : 
`    await _methodChannel.invokeMethod('torch', torchState.value.index);` 

This is the error:
```
***  `Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<mobile_scanner.MobileScanner: 0x28012b9c0>: An -observeValueForKeyPath:ofObject:change:context: message was received but not handled.
Key path: torchMode
Observed object: <AVCaptureFigVideoDevice: 0x114c00800 [Back Camera][com.apple.avfoundation.avcapturedevice.built-in_video:0]>
Change: {
    kind = 1;
    new = 1;
}
Context: 0x0'
*** First throw call stack:
(0x1ac0dde88 0x1a540b8d8 0x1a6a28cdc 0x1a64f03f0 0x1a65068d4 0x1a64f3860 0x1a64f3590 0x1a64f2518 0x102c007c4 0x102c0c854 0x102c0a770 0x102c0aa00 0x1066759ac 0x10614de8c 0x1b36ac4b4 0x1b36adfdc 0x1b36bc7f4 0x1b36bc444 0x1ac16e6f8 0x1ac150058 0x1ac154ed4 0x1e5452368 0x1ae6333d0 0x1ae633034 0x102364370 0x1ca7bc960)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001e8cd8200 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x1e8cd8200 <+8>:  b.lo   0x1e8cd8220               ; <+40>
    0x1e8cd8204 <+12>: pacibsp
    0x1e8cd8208 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1e8cd820c <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Lost connection to device.
```

**Comment by Adrift001** [comment]
@juliansteenbakker This problem still exists.

**Comment by tangyiyong** [comment]
comment the following line may sucess:

//in every xxxx_controller.dart

  MobileScannerController controller = MobileScannerController(
    //torchEnabled: true,
    // formats: [BarcodeFormat.qrCode]
    // facing: CameraFacing.front,
    onPermissionSet: (hasPermission) {
      // Do something with permission callback
    },
    // detectionSpeed: DetectionSpeed.normal
    // detectionTimeoutMs: 1000,
    // returnImage: false,
  );

It seems the torch's problem.

**Comment by Adrift001** [comment]
@tangyiyong 嗯, 不用了, 我下载2.1.0版本的没啥问题.

**Comment by tangyiyong** [comment]
@Adrift001 Thanks a lot, It works.

**Comment by Adrift001** [comment]
@tangyiyong 你会说中国话不?

**Comment by tangyiyong** [comment]
我去，当然会啊，只是开发机器下面中文输入法比较不方便
