### ISSUE TITLE
armv7 assets not found when building ios ipa

### ISSUE THREAD

**Issue by Rookierun** [juliansteenbakker/mobile_scanner#369]
armv7 assets not found when building ios ipa,my mobile_scanner branch is 1.0.0,when I switch to 1.1.2,the armv7 not found either,
how can I get armv7 asset when I build ios ipa? 
hope your reply
<img width="657" alt="EA90CA13-3E37-4BF5-AC2F-260D6AA4C6F0" src="https://user-images.githubusercontent.com/14110110/202326712-c2a1067c-27ce-44c7-aad2-b0f61b44e186.png">

**Comment by juliansteenbakker** [comment]
Can you please try v3.0.0-beta.2.
