### ISSUE TITLE
analyzeImagePath cannot detect barcode in v3.0.0-beta.2

### ISSUE THREAD

**Issue by iamshaunwu** [juliansteenbakker/mobile_scanner#370]
@juliansteenbakker

Thanks for pushing v3.0.0-beta.2. 

Following the full example in [https://github.com/juliansteenbakker/mobile_scanner/tree/master/example/lib/barcode_scanner_controller.dart](https://github.com/juliansteenbakker/mobile_scanner/tree/master/example/lib/barcode_scanner_controller.dart), 

I kept experiencing `analyzeImagePath` being unable to detect QR code (Snackbar 'No barcode found' keeps popping up). The rest is fine.

Reverting to v3.0.0-beta.1 for now.

**Comment by wordlesser** [comment]
me too!

**Comment by juliansteenbakker** [comment]
Can you please try this with v3.0.0?
