### ISSUE TITLE
Barcode for Flutter Web

### ISSUE THREAD

**Issue by jaca420** [juliansteenbakker/mobile_scanner#372]
Plugin is great, but I need a web version. Any idea when this will be available?

**Comment by sheikh24** [comment]
https://pub.dev/packages/flutter_barcode_sdk

Hope this will fix your issue.

**Comment by juliansteenbakker** [comment]
I'm sorry, but this package does support web. Checkout the web section of the readme. https://pub.dev/packages/mobile_scanner
