### ISSUE TITLE
Image in BarcodeCapture is rotated

### ISSUE THREAD

**Issue by nick990** [juliansteenbakker/mobile_scanner#374]
I'm testing the version v3.0.0-beta.2 and I get an image with wrong size.
By showing the returned image in a Dialog, I noticed that the image is rotated (both on Android and iOS).
Before this fix, the image orientation was correct.
Actually it's not a problem, but I have to know if it's the expected behaviour and I have to rotate the returned image or it's a bug.

![screenshot](https://user-images.githubusercontent.com/8275481/203096162-91a82197-5077-487a-a8d1-0bf78a8092c2.jpg)

**Comment by EArminjon** [comment]
Yep, annoying for demo with clients :'(

**Comment by nick990** [comment]
The same problem occurs in master branch.
Does anyone know if it's a bug or not?

**Comment by MrNB0dy** [comment]
Same issue... I think it's a bug

**Comment by juliansteenbakker** [comment]
Can anyone try this with the latest version 3.0.0?

**Comment by EArminjon** [comment]
@juliansteenbakker  The camera in emulator is still rotated.
