### ISSUE TITLE
Multiple Exception while executing golden tests. 

### ISSUE THREAD

**Issue by athulgrg** [juliansteenbakker/mobile_scanner#379]
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following MissingPluginException was thrown running a test:
MissingPluginException(No implementation found for method state on channel
dev.steenbakker.mobile_scanner/scanner/method)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  QRCode Screen UI JA Golden Test
═══════════════════════════════════════════════════════════════════════════════════════════�

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel
dev.steenbakker.mobile_scanner/scanner/event:
MissingPluginException(No implementation found for method listen on channel
dev.steenbakker.mobile_scanner/scanner/event)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
═══════════════════════════════════════════════════════════════════════════════════════════�

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following MissingPluginException was thrown running a test:
MissingPluginException(No implementation found for method stop on channel
dev.steenbakker.mobile_scanner/scanner/method)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  QRCode Screen UI EN Golden Test
═══════════════════════════════════════════════════════════════════════════════════════════�

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following MissingPluginException was thrown while de-activating platform stream on channel
dev.steenbakker.mobile_scanner/scanner/event:
MissingPluginException(No implementation found for method cancel on channel
dev.steenbakker.mobile_scanner/scanner/event)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
═══════════════════════════════════════════════════════════════════════════════════════════�

**Comment by athulgrg** [comment]
Exception occurred while running golden tests.

**Comment by athulgrg** [comment]
Mobile scanner version: 


mobile_scanner:
    dependency: "direct main"
    description:
      name: mobile_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"

**Comment by 549064368** [comment]
有解决吗

**Comment by juliansteenbakker** [comment]
Can you please try this again with version 3.0.0?
