### ISSUE TITLE
After the build, the package size is too large

### ISSUE THREAD

**Issue by jahnli** [juliansteenbakker/mobile_scanner#38]
The volume is (36.8MB) with mobile_scanner and (28.4MB) without mobile_scanner.  
![image](https://user-images.githubusercontent.com/20943608/156680027-6b5485b0-0305-4765-8aac-1d2b9f2a94b7.png)

**Comment by juliansteenbakker** [comment]
Right now this plugin is using the 'bundled' mlkit library. I will do some research about how we can use the 'thin' version of mlkit. See https://developers.google.com/ml-kit/migration/android#api-specific_changes:

> For the [Barcode Scanning API](https://developers.google.com/ml-kit/vision/barcode-scanning/android), there are now two ways the models can be delivered:
> 
> Through Google Play Services a.k.a. “thin” (recommended) - this reduces the app size and the model is shared between applications. However, developers will need to ensure that the model is downloaded before using it for the first time.
> With your app’s APK a.k.a. “bundled” - this increases the app size but it means the model is immediately usable.
> The two implementations are slightly different, with the “bundled” version having a number of improvements over the “thin” version. Details on these differences can be found in the Barcode Scanning API guidelines.

**Comment by jahnli** [comment]
Yes, if the 'thin' version of MLKit is not used, this results in mobile_scanner being close to 10M more

**Comment by pablojimpas** [comment]
Even if the possibility of using the "thin" model is given, it would be good to keep the option of using the "bundled" model to avoid depending on Google Play Services among other considerations.

**Comment by JapneetSingh-28** [comment]
Hi, could you please tell me how to reduce the size on iOS, as the above solution of replacing a line in Gradle solves the problem only for android

**Comment by juliansteenbakker** [comment]
For now i have released v1.1.1-play-services, which uses a smaller model and reduces the app size with 8MB.

**Comment by hnord-vdx** [comment]
@juliansteenbakker This issue shouldn't be closed as it increases the app size on iOS equally as much. What can be done to reduce it on iOS side?
