### ISSUE TITLE
"No duplicates" not as expected with multiple barcodes

### ISSUE THREAD

**Issue by fhuonder** [juliansteenbakker/mobile_scanner#381]
Hi,

When scanning multiple barcodes at once the behavior is (in my opinion) not as expected.
My expectation is that as long as the same barcodes are visible (no one enters the camera and no one leaves it) the callback should not fire.
The actual behavior is that the callback is fired all the time because when the camera is moving while scanning, the ML Kit returns the barcodes in different orders. 
In the Android code here:

https://github.com/juliansteenbakker/mobile_scanner/blob/e6bbc31aea9a7d3e7eb43e1769a0431967d4e0fc/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt#L134

this check does not work when the order of the items changes. This comparison should make an unorderedEquals.

iOS has the same behavior by using `elementsEqual` for the array comparison.

Proposal:
I could assume that both behaviors make sense so maybe there should be two different `DetectionSpeed` enums? E.g. `NO_DUPLICATES` and `NO_DUPLICATES_STRICT` (where strict would be the current behavior).

Regards,
Florian

**Comment by juliansteenbakker** [comment]
This is now implemented in v3.0.0. Please see the example app for examples on how to achieve this.

**Comment by fhuonder** [comment]
@juliansteenbakker 
Which example? I don't see it...
