### ISSUE TITLE
Not able to run pod install

### ISSUE THREAD

**Issue by mayukhsil** [juliansteenbakker/mobile_scanner#382]
I have firebase auth and mobile scanner, both bumped up to their latest versions. But I still get dependency conflicts when trying to run pod install.

[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.1.4, which depends on
      Firebase/Auth (= 10.2.0) was resolved to 10.2.0, which depends on
        FirebaseAuth (~> 10.2.0) was resolved to 10.2.0, which depends on
          GTMSessionFetcher/Core (< 4.0, >= 2.1)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 0.0.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 3.2.0) was resolved to 3.2.0, which depends on
        MLKitBarcodeScanning (~> 2.2.0) was resolved to 2.2.0, which depends on
          MLKitVision (~> 4.2) was resolved to 4.2.0, which depends on
            GTMSessionFetcher/Core (~> 1.1)

**Comment by jari-kuipers** [comment]
I'm also experiencing this issue since these package upgrades
firebase_core: 1.22.0 > 2.3.0
firebase_crashlytics: 2.8.10 > 3.0.6

**Comment by juliansteenbakker** [comment]
This is a known issue, please see #335
