### ISSUE TITLE
Scanned area for barcode. 

### ISSUE THREAD

**Issue by developerflutter** [juliansteenbakker/mobile_scanner#384]
How can we set the area for barcode selection?

**Comment by juliansteenbakker** [comment]
With version 3.0.0-beta.4 you can use an custom scanning area like shown in the example app: https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/lib/barcode_scanner_window.dart

Please note that this is still a beta so there can be breaking changes in the near future.
