### ISSUE TITLE
Blank screen when permission granted

### ISSUE THREAD

**Issue by rakeshm12** [juliansteenbakker/mobile_scanner#385]
Shows blank screen after camera permission granted for first time open application.  camera initialise after closing and reopen scanner

**Comment by rakeshm12** [comment]
pls solve it if is a bug else guide me to solve this issue

**Comment by maulikchak** [comment]
#227 similar problem and it's solved

**Comment by fhuonder** [comment]
Hi,

I encounter the same problem. But I do not see how to solve it with what's written in #227.
Would be nice if a solution is available soon .

Regards

**Comment by EArminjon** [comment]
> #227 similar problem and it's solved

Didn't see how they resolve it. 
I've Black screen too.

**Comment by EArminjon** [comment]
As i see : 

When launching mobile_scanner without ask permission before, the plugin will do that : 

```
_methodChannel.invokeMethod('state')
```

This will return MobileScannerState.undetermined then the popup is displayed and the attribute isStarting is put at true. So we cannot call again .start method.

When accepting the popup permission no code is triggered inside mobile_scanner_controller.dart and the attribute isStarting is keep a true...

**Comment by EArminjon** [comment]
I've put some logs inside mobile_scanner_controller.dart and the package code seems to not work as expected : 

Line 135 : 

```dart
case MobileScannerState.undetermined:
          try {
            print("GITHUB-ISSUE: Test 1");
            final bool result =
                await _methodChannel.invokeMethod('request') as bool? ?? false;
            print("GITHUB-ISSUE: Test 2 $result");
            if (!result) {
              isStarting = false;
              onPermissionSet?.call(result);
              throw MobileScannerException('User declined camera permission.');
            }
          } catch (err, stack) {
            print("GITHUB-ISSUE: Throw 1");
            print(err);
            print(stack);
          } on PlatformException catch (err, stack) {
            print("GITHUB-ISSUE: Throw 2");
            print(err);
            print(stack);
          }
          break;
        case MobileScannerState.denied:
```

Logs 
```
I/flutter (20574): GITHUB-ISSUE: Test 1
# and that's all
```

After requesting camera permission, and after user click on the notification nothing happen then...

**Comment by maulikchak** [comment]
this is happening because we asking permission for camera access for 2 times,

I checked my log and find this
"Getting W/Activity: Can request only one set of permissions at a time"

so I just remove camera permission from my side and it's automatically come when I initialize Mobile Scanner controller and the error goes and camera working perfectly so this issue not from the package side

**Comment by maulikchak** [comment]
just remove manually camera permission code cause package is automatically asking camera permission and then error goes

**Comment by fhuonder** [comment]
@maulikchak 
I encounter the same problem without asking for permission outside the mobile scanner.
Further the library should be able to handle this because based on the project we want to ask for permission on our own at the right time (maybe with additional information presented to the user).

**Comment by EArminjon** [comment]
> this is happening because we asking permission for camera access for 2 times,
> 
> I checked my log and find this "Getting W/Activity: Can request only one set of permissions at a time"
> 
> so I just remove camera permission from my side and it's automatically come when I initialize Mobile Scanner controller and the error goes and camera working perfectly so this issue not from the package side

It's not the issue of this issue. The issue didn't talk about permission granted by app. I've the same issue, the camera package is the only one who ask this permission. I didn't have your logs. 

Sorry but I think you are off topic

**Comment by maulikchak** [comment]
> 

but for me it's worked blank screen gone

**Comment by maulikchak** [comment]
> > 
@EArminjon  
> but for me it's worked blank screen gone

**Comment by EArminjon** [comment]
> > >
> 
> @EArminjon
> 
> > but for me it's worked blank screen gone

Can you share you flutter doctor -v ? And the mobile_scanner version used ?

On my side : 

mobile_scanner: ^3.0.0-beta.2

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6.1 21G217 darwin-arm, locale fr-FR)
    • Flutter version 3.3.4 on channel stable at /Users/earminjon/fvm/versions/3.3.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (8 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/earminjon/Library/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/earminjon/Library/Android/Sdk
    • Java binary at: /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/earminjon/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 71.0.5
    • Dart plugin version 222.4345.14

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.6.1 21G217 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 107.0.5304.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
➜  rexel-flutter-app git:(bugfix/APPS-5076-search) fvm flutter doctor -v
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6.1 21G217 darwin-arm, locale fr-FR)
    • Flutter version 3.3.4 on channel stable at /Users/earminjon/fvm/versions/3.3.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (8 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/earminjon/Library/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/earminjon/Library/Android/Sdk
    • Java binary at: /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/earminjon/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 71.0.5
    • Dart plugin version 222.4345.14

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.6.1 21G217 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by rakeshm12** [comment]
> this is happening because we asking permission for camera access for 2 times,
> 
> I checked my log and find this
> "Getting W/Activity: Can request only one set of permissions at a time"
> 
> so I just remove camera permission from my side and it's automatically come when I initialize Mobile Scanner controller and the error goes and camera working perfectly so this issue not from the package side


Do you mean need to remove camera permission from manifest file?

**Comment by maulikchak** [comment]
> flutter doctor -v

  mobile_scanner: ^2.1.0
  
  [√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.22000.1219], locale en-IN)
    • Flutter version 3.3.8 on channel stable at D:\Flutter\flutter_windows_3.0.5-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (3 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Maulik\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.18)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32802.440
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1219]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 107.0.5304.108
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by EArminjon** [comment]
Okay, it's because of your version. The beta one have this issue.

**Comment by maulikchak** [comment]
> 

not only beta I faced this issue on same version but remove permission form my side and it's work

**Comment by EArminjon** [comment]
> > 
> 
> not only beta I faced this issue on same version but remove permission form my side and it's work

Can you test on our version ?

**Comment by renanzdm** [comment]
same issue ^3.0.0-beta.2

**Comment by huahua8893** [comment]
I'm using version 2.1.0, run the official demo on device, I'm not add some camera permission code on my side, but facing same issue, is there any suggestion please?

**Comment by renanzdm** [comment]
I opened a pull request that solves this I'm waiting to be accepted

**Comment by EArminjon** [comment]
https://github.com/juliansteenbakker/mobile_scanner/pull/393

**Comment by renanzdm** [comment]
this error solved master branch

**Comment by rakeshm12** [comment]
Issue is solved in version 2.1.0

**Comment by EArminjon** [comment]
@rakeshm12 ^3.0.0-beta.2 will replace 2.1.0, i don't think closing this issue is good...

**Comment by renanzdm** [comment]
In ^3.0.0-beta.3 is solved too

**Comment by juliansteenbakker** [comment]
^3.0.0-beta.3 contains a bug which caused an infinite loop when denying the permission. ^3.0.0-beta.4 fixes this and i just released it. I'll wait a week before releasing this as stable v3.0.0 in order to let you guys try it out and report any bugs if found.
