### ISSUE TITLE
error build: Framework not found MTBBarcodeScanner

### ISSUE THREAD

**Issue by ehsan097** [juliansteenbakker/mobile_scanner#394]
**Facing this issue while building ios build.**

using this version 
mobile_scanner: ^3.0.0-beta.2
<img width="534" alt="Screen Shot 2022-12-03 at 10 25 12 AM" src="https://user-images.githubusercontent.com/96479420/205425458-bdac37e3-f8ff-4439-8e7a-df4f9e4d9f94.png">

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)

 Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)

**Comment by juliansteenbakker** [comment]
Can you please try again with version 3.0.0?
