### ISSUE TITLE
[feature] Convert the plugin to use `plugin_platform_interface`

### ISSUE THREAD

**Issue by navaronbracke** [juliansteenbakker/mobile_scanner#401]
Currently the plugin provides support for Android, iOS, MacOS and web.
However, the current implementation mixes `Texture` & `HTMLElementView` [directly in the implementation](https://github.com/juliansteenbakker/mobile_scanner/blob/master/lib/src/mobile_scanner.dart#L140-L142)
This can be improved by migrating the plugin to use the platform interface way of doing things.

This would also make implementing https://github.com/juliansteenbakker/mobile_scanner/issues/14 a bit easier, since only the windows implementation needs to be set up using the PlatformInterface method

TODO:
- [ ] introduce a platform interface
    - [ ] Widget buildScannerView()
    - [ ] The `MobileScannerArguments` class should be private, as it exposed implementation details
- [ ] reimplement web using `package:web`, which replaces `dart:html`
    - [ ] provide a web specific API to switch between barcode readers
    - [ ] migrate to Dart 3.3 extension types (currently not possible)
    - [ ] bring the camera handling improvements to the web    - [ ] start should throw if there is no camera
       - [ ] start should handle invalid camera direction in case the direction is not available
       - [ ] start should handle the torch state if the torch is not available
       - [ ] stop should do nothing if there is no camera
       - [ ] toggleTorch should do nothing if the current camera (if any) does not have a torch
- [ ] deprecate `hasTorch` and introduce a new `unavailable` torch mode
- [ ] remove lifecycle handling from the plugin, as it leads to lifecycle bugs #691 
   - [ ] remove the autoStart parameter
   - [ ] remove the deprecated onPermissionSet parameter
   - [ ] remove the `onStart` & `onScannerStarted` parameters
- [ ] refactor the `toggleTorch()`, `resetZoomScale()`, `setZoomScale()`, `stop()` methods to return instead of throw if the camera is null

**Comment by navaronbracke** [comment]
@teolemon I would like to start working on this in the coming days.

My plan is to set up the plugin in such a way that we abstract implementation details behind the platform interface.
This would hide implementation details (such as webId vs textureId) and make fixing things a bit easier (I think)

**Comment by navaronbracke** [comment]
@juliansteenbakker Just an FYI: I'll be tackling this one next.

The plan is to indeed have a common platform interface, which hides implementation details (i.e. Texture vs HtmlElementView). I'll also convert the web implementation to a full blown static interop layer for ZXing (having a MethodChannel on the web is a little weird imo)

I'll make sure I don't forget the MacOS implementation along the way :)

This is going to be a big effort, so it might take a while to get it done.

**Comment by teolemon** [comment]
@navaronbracke @juliansteenbakker I assigned it to you

**Comment by navaronbracke** [comment]
@juliansteenbakker As I finally have some time to address this, I have started the work on this issue.

I hope that with this refactor I can also address several reported issues.

**Comment by juliansteenbakker** [comment]
Thank you very much @navaronbracke ! If you're interested, i can add you as a maintainer of this package. I unfortunately don't have enough time to keep it properly maintained right now, so some help is always welcome 😄

**Comment by navaronbracke** [comment]
I would be interested in that. I think with multiple maintainers working on it, we can divide the workload a bit better.
