### ISSUE TITLE
MobileScannerException: code genericError, message: Called start() while already started

### ISSUE THREAD

**Issue by gautamswostik** [juliansteenbakker/mobile_scanner#418]
Unhandled Exception: MobileScannerException: code genericError, message: Called start() while already started

I'm getting this issue when qr scanner page is opened for the first time

**Comment by kamami** [comment]
Same issue here

**Comment by EArminjon** [comment]
check if you put autoStart and call start then, you shouldn't do that.

**Comment by EArminjon** [comment]
same

**Comment by juliansteenbakker** [comment]
Can you please try this again with version 3.0.0?

**Comment by chedielathmnilatech** [comment]
I fixed this error by adding this in the initState function
`WidgetsBinding.instance.addPostFrameCallback(
      (_) => cameraController
        ..stop()
        ..start(),
    );`

**Comment by ElDuderini** [comment]
> I fixed this error by adding this in the initState function `WidgetsBinding.instance.addPostFrameCallback( (_) => cameraController..stop()..start(), );`

Thanks, this fixed the issue for me. Came across it whenever the app first started and I opened the camera for the first time, anytime after it would function normally. This happened in 3.0.0 for me @juliansteenbakker

**Comment by enchance** [comment]
> I fixed this error by adding this in the initState function `WidgetsBinding.instance.addPostFrameCallback( (_) => cameraController..stop()..start(), );`

This worked for me. In my case I'm using `go_router: ^13.0.1` and placed my scanning page in a `StatefulShellRoute.indexedStack`.
