### ISSUE TITLE
NO ACCESS error

### ISSUE THREAD

**Issue by romawizard** [juliansteenbakker/mobile_scanner#420]
Hi 
In Firebase crashlytics I observe the **Fatal Exception: FlutterErrorPlatformException(NO ACCESS, null, null, null). Error thrown null**. After investigating I found that the reason is denied camera permission. Could you please provide a way to handle this error?

Log attached
[stacktrace.txt](https://github.com/juliansteenbakker/mobile_scanner/files/10220236/stacktrace.txt)

**Comment by juliansteenbakker** [comment]
Which version of the plugin are you using?

**Comment by romawizard** [comment]
I used 2.0.0 and 2.1.0

**Comment by romawizard** [comment]
In mobile_scanner_controller.dart file you can find the **start** method that throws this error. Method **start** is calling in the MobileScannerController constructor, didChangeAppLifecycleState and switchCamera but in all cases the error is not handled

 ```
 Future<void> start() async {
    ensure('startAsync');
    if (isStarting) {
      throw Exception('mobile_scanner: Called start() while already starting.');
    }
    isStarting = true;
    // setAnalyzeMode(AnalyzeMode.barcode.index);

    // Check authorization status
    if (!kIsWeb) {
      MobileScannerState state = MobileScannerState
          .values[await methodChannel.invokeMethod('state') as int];
      switch (state) {
        case MobileScannerState.undetermined:
          final bool result =
              await methodChannel.invokeMethod('request') as bool;
          state = result
              ? MobileScannerState.authorized
              : MobileScannerState.denied;
          break;
        case MobileScannerState.denied:
          isStarting = false;
          _throw PlatformException(code: 'NO ACCESS');_
        case MobileScannerState.authorized:
          break;
      }
    }
```

**Comment by juliansteenbakker** [comment]
https://github.com/juliansteenbakker/mobile_scanner/blob/5ebc65e96e8de7224e3a7265d388a8d5d00ee3fd/lib/src/mobile_scanner_controller.dart#L195

The code has already been changed in the latest version v3.0.0-beta.4. With this version you can catch the error, and you can provide a widget to display if an error occurs.

https://github.com/juliansteenbakker/mobile_scanner/blob/5ebc65e96e8de7224e3a7265d388a8d5d00ee3fd/lib/src/mobile_scanner.dart#L29
