### ISSUE TITLE
Scanner on a web server

### ISSUE THREAD

**Issue by ExeLisor** [juliansteenbakker/mobile_scanner#427]
How can I run an application with a scanner on a web server? The application works correctly when it is launched via localhost, but as soon as I launch it on an ip, I do not receive any requests for permission to use the camera and instead of a scanner, there is a black screen

**Comment by daniel-lucas-silva** [comment]
Same here

**Comment by p-mazhnik** [comment]
Does your web server use `HTTP`, or is it configured to use `HTTPS`?

**Comment by juliansteenbakker** [comment]
Please see #288

**Comment by Carricklie** [comment]
Hello everybody, does this one resolved?
