### ISSUE TITLE
Element of result error - ios

### ISSUE THREAD

**Issue by tamirlet** [juliansteenbakker/mobile_scanner#432]
Hi, i installed the version 3.0.0-beta.4.
I am trying to build the project in ios but it failed with a message: 
SwiftMobileScannerPlugin.swift:41:43: Generic parameter 'ElementOfResult' could not be inferred

I was trying flutter clean and pub get and yet same result.
I need this version specific so I can handle the onError page.

There is a fix for this?

**Comment by KMIxx** [comment]
Updating OSX and Xcode to the latest version resolved this issue for me.

**Comment by EeroVilkuna** [comment]
I am just throwing an educated guess that SwiftMobileScannerPlugin.swift file row 41 `let barcodesMap = barcodes!.compactMap { barcode in` is missing element for compactMap, that causes this error

**Comment by VeryazovSergey** [comment]
Same issue for me! But I cant update my Mac and XCode its old but 13 version... Totally dont know what to do...

**Comment by juliansteenbakker** [comment]
All i can say is that you should use the latest version of xcode for this project.
