### ISSUE TITLE
[Request] Release to pub.dev

### ISSUE THREAD

**Issue by flodaniel** [juliansteenbakker/mobile_scanner#445]
I am just getting started with this package. Thank you for all the work you have done already!
Searching for a couple of features, i noticed that that some of them are already merged to `master`, such as https://github.com/juliansteenbakker/mobile_scanner/pull/407/ and https://github.com/juliansteenbakker/mobile_scanner/pull/411. 

Sadly none of these fixes/features have been released to pub.dev. I am not familiar with how much work more frequent releases would be, but it would be highly appreciated! 

Thank you :)

**Comment by flodaniel** [comment]
I just discovered that there is a beta channel here: https://pub.dev/packages/mobile_scanner/versions/3.0.0-beta.4
I will be using this one for now, but it would still be interesting to know when all of these great new things are considered stable :)

**Comment by juliansteenbakker** [comment]
I have released version 3.0.0, sorry for the delay!
