### ISSUE TITLE
ScanWindow doesn't seem right.

### ISSUE THREAD

**Issue by Ccmi** [juliansteenbakker/mobile_scanner#448]
Hi
ScanWindow is wrong when fit:BoxFit.cover. Areas other than the left and right sides of the designated area can still be identified;

**Comment by juliansteenbakker** [comment]
Can you please try again with version 3.0.0?

**Comment by simplenotezy** [comment]
@juliansteenbakker I have the same issue here. Would like some advice on how to properly calculate ScanWindow when using "cover" as fit.
