### ISSUE TITLE
3.0.0-beta.4 performance issue: slow scanning compared to stable version 2.1.0

### ISSUE THREAD

**Issue by ezraaaa** [juliansteenbakker/mobile_scanner#449]
## Steps to Reproduce

Use `mobile_scanner: 2.1.0`
1. Scan any normal text QR code
2. Slowly tilt your phone down (vertically) to get the QR code into the scan window

Use `mobile_scanner: 3.0.0-beta.4`
1. Scan any normal text QR code
2. Scan within 15 seconds and need to be nearly aligned to the QR code placement

**Expected results:** 
Detect QR no matter the angle immediately. Takes about 5 seconds. See attachment for videos.

**Actual results:** 
Required to align QR code to nearly flat and takes a while for it to detect. Takes about 15 seconds. See attachment for videos.

<details>
<summary>Code sample</summary>

2.1.0
```dart
return MobileScanner(
    fit: BoxFit.contain,
    key: const Key('qrCode_view'),
    controller: MobileScannerController(formats: [BarcodeFormat.qrCode]),
    onDetect: (barcode, arguments) {
      context
          .read<QrScannerBloc>()
          .add(QrCodeResultUpdated([barcode]));
    },
);
```

3.0.0-beta.4
```dart
return MobileScanner(
    fit: BoxFit.contain,
    key: const Key('qrCode_view'),
    controller: MobileScannerController(formats: [BarcodeFormat.qrCode]),
    onDetect: (barcode) {
      context
          .read<QrScannerBloc>()
          .add(QrCodeResultUpdated(barcode.barcodes));
    },
);
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 3.7.0-16.0.pre, on macOS 13.1 22C65 darwin-arm64, locale en-MY)
    • Flutter version 3.7.0-16.0.pre on channel master at /Users/ezragunn/Development/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4205357554 (4 days ago), 2023-01-09 18:08:34 -0800
    • Engine revision 9c0b187a11
    • Dart version 3.0.0 (build 3.0.0-103.0.dev)
    • DevTools version 2.20.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ezragunn/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Recordings:

3.0.0-beta.4
https://drive.google.com/file/d/1S4BnwQPRQuSOvHkkdzU_uULqfeq1jywz/view?usp=sharing 

2.1.0
https://drive.google.com/file/d/1tgz0Ge449-i4eQS_ZcReIoDifGsfRlkG/view?usp=sharing

**Comment by zunimc** [comment]
Similar problem here.

v2.1.0 picks barcodes instantly whereas latest beta does some weird thing under same use. Some codes are not even registered.

Oddly enough, if I rotate my phone to 90º to the side codes start getting registered way faster. My app is locked to portrait mode.

**Comment by kekko7072** [comment]
+ 1

**Comment by juliansteenbakker** [comment]
After reviewing the videos im not convinced this is an issue of the plugin. It is clear that the video showing 3.0.0-beta.4 is unfocused, and it takes a while for the camera to focus. As soon as it is focussed, the qr code is read.

I've tried this myself and i get scan results near instant using the example app.

Also, it seems like you are using the master branch of flutter, which is not recommended to use. I suggest switching to stable for production apps. 

If someone can provide me an example of a qr code thats not being registered correctly with version 3.0.0-beta.4 and is using 2.1.0, please let me know so i can investigate further.

**Comment by ezraaaa** [comment]
It seems to be like what @juliansteenbakker said, it's about the autofocus. 

I tried alternate way, which is to zoom in at 0.5 and that kind of resolve the problem. 

Is there any solution to the autofocus when it is not zoomed in? Or is it totally up to the users' camera?

**Comment by juliansteenbakker** [comment]
For now it is up to the autofocus of the users camera.

**Comment by juliansteenbakker** [comment]
For now it is up to the autofocus of the users camera.
