### ISSUE TITLE
Not possible to analyze image from gallery

### ISSUE THREAD

**Issue by rraayy** [juliansteenbakker/mobile_scanner#453]
Hi, I tried the sample code from my Google pixel 3. The sample code only works when using the camera scan the QRcode/BarCode. I tried to  pick the image with QR code from the gallery, it always show 'No barcode found!',  But if I picked an photo with barcode , the sample code works well. Is there has any way to pick the QR code image from the gallery and can works well?
I generated the QR code from [www.the-qrcode-generator.com](https://www.the-qrcode-generator.com/)

![截圖 2023-01-18 上午11 37 39](https://user-images.githubusercontent.com/4694572/213079505-66a987d1-08d2-460c-846e-e215560bf5d8.png)

**Comment by juliansteenbakker** [comment]
Can you please try again with version 3.0.0?
