### ISSUE TITLE
can't sound when scan the qr code

### ISSUE THREAD

**Issue by spdeol20** [juliansteenbakker/mobile_scanner#455]
how can we sound when it detect the barcode
there is nothing in the controller

**Comment by NAME-NikhilPatil** [comment]
use vibration package

**Comment by DayDreamer-commits** [comment]
`  Soundpool pool = Soundpool.fromOptions();
  late int soundId;

  soundId = await rootBundle
      .load("assets/sounds/notf_2.mp3")
      .then((ByteData soundData) {
  return pool.load(soundData);
  });
  await pool.play(soundId);`

please make sure that you follow the instruction from soundpool packages for resource optimization.
and use different line of above codes at appropriate places.
