### ISSUE TITLE
Support pause feature?

### ISSUE THREAD

**Issue by SushilGhorasaini1** [juliansteenbakker/mobile_scanner#46]
It would be quite nice if we could pause scanning in case of successful scan without pausing camera view. Also, vibration on detect would be helpful.

**Comment by juliansteenbakker** [comment]
Would this answer your question: https://github.com/juliansteenbakker/mobile_scanner/discussions/39#discussioncomment-2293786 ?

As for vibration, you can use https://api.flutter.dev/flutter/services/HapticFeedback-class.html
