### ISSUE TITLE
[bug] wrong scanned result when background is red

### ISSUE THREAD

**Issue by berdibekovaG** [juliansteenbakker/mobile_scanner#469]
mobile_scanner could scan right when I changed background color at photoshop to black or white and changed color of bar code.

there is wrong result from scanning bar code from picture (for example I got barcode's results like this: 700050553593,470455036662,705550351533). other bar code scanners/services check it right.

to reproduce the bug, please scan this bar code.
![photo_2023-02-03 11 42 03](https://user-images.githubusercontent.com/68873785/216523695-a598a481-462c-4a60-bdf0-c75b06c7fecf.jpeg)

**Comment by juliansteenbakker** [comment]
This is an issue with the underlying framework from google, MLKit barcode scanner, so i can't fix this.
