### ISSUE TITLE
Disable Firebase logging

### ISSUE THREAD

**Issue by sprimm98** [juliansteenbakker/mobile_scanner#47]
Hi Julian,

First of all, thanks for your amazing work!

Every once in a while, "Making request to: https://firebaselogging.googleapis.com/v0cc/log/batch?format=json_proto3" is printed to the console which I assume is the standard behaviour of MLKit. Is there any chance to disable logging/analytics to Firebase or is this necessary for scanning?

**Comment by juliansteenbakker** [comment]
Hi @sprimm98 ,

thanks ! The logging is indeed part of MLKit. Maybe you can try the following: https://stackoverflow.com/a/37311309

**Comment by sprimm98** [comment]
Thanks for replying. On https://firebase.google.com/docs/analytics/configure-data-collection?platform=android, I found a way to disable Firebase analytics permanently. I think that'll fix it.

**Comment by hellohejinyu** [comment]
> Thanks for replying. On https://firebase.google.com/docs/analytics/configure-data-collection?platform=android, I found a way to disable Firebase analytics permanently. I think that'll fix it.

Hi, are you sure the problem is solved? I set it up and it doesn't work

**Comment by hellohejinyu** [comment]
<img width="1446" alt="image" src="https://user-images.githubusercontent.com/8766034/216511272-c303e67f-40b1-4a58-895e-1ece131b4017.png">

**Comment by sprimm98** [comment]
@hellohejinyu Hello, at this point I thought the problem was solved. In fact, logging was never disabled. I forgot to modify the post here. Sorry.
