### ISSUE TITLE
You can add the qr_code_scanner overlay.

### ISSUE THREAD

**Issue by Freilynbp03** [juliansteenbakker/mobile_scanner#472]
Thanks for your work.

I would like to be able to implement a mask like this to focus on the qr. Can you explain to me how I do it?
![android-app-screen-one](https://user-images.githubusercontent.com/54672897/216635425-1df756ca-b30e-4831-a5a6-328a249c2c52.jpg)

**Comment by edytk** [comment]
https://github.com/juliansteenbakker/mobile_scanner/issues/250#issuecomment-1209723708

**Comment by vlazdra** [comment]
@Freilynbp03  Maybe checkout the example inside the repo and check if it's what your looking for: https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/lib/barcode_scanner_window.dart

**Comment by pmatatias** [comment]
> @Freilynbp03 Maybe checkout the example inside the repo and check if it's what your looking for: https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/lib/barcode_scanner_window.dart

for anyone want to try this example, make sure you to use latest beta version.

when I wrote this comment, latest on pub.dev are `version 2.1.0`
and I got error `BarcodeCapture` undefined. 

we can see the [changelog 3.0.0-beta2](https://github.com/juliansteenbakker/mobile_scanner/blob/master/CHANGELOG.md#300-beta2) point 2:
- onDetect now returns the object BarcodeCapture, which contains a List of barcodes and, if enabled, an image.

you can wait until v3.0.0 release or use beta version on your `pubspe.ymal`
```
mobile_scanner: ^3.0.0-beta.4
```
---

<details>
<summary>Screenshot</summary>

![Screenshot_2023-02-07-12-02-40-243_com example workshop_mobile](https://user-images.githubusercontent.com/33835308/217153122-7619206f-b2aa-46f6-bc9f-2a5781976ed0.jpg)
</details>

**Comment by juliansteenbakker** [comment]
I have released v3.0.0 which contains this feature.

**Comment by Freilynbp03** [comment]
> > @Freilynbp03Tal vez revise el ejemplo dentro del repositorio y verifique si es lo que está buscando: https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/lib/barcode_scanner_window.dart
> 
> para cualquiera que quiera probar este ejemplo, asegúrese de usar la última versión beta.
> 
> cuando escribí este comentario, lo último en pub.dev es `version 2.1.0` y obtuve un error `BarcodeCapture`indefinido.
> 
> podemos ver el [changelog 3.0.0-beta2](https://github.com/juliansteenbakker/mobile_scanner/blob/master/CHANGELOG.md#300-beta2) punto 2:
> 
> * onDetect ahora devuelve el objeto BarcodeCapture, que contiene una lista de códigos de barras y, si está habilitado, una imagen.
> 
> puede esperar hasta el lanzamiento de v3.0.0 o usar la versión beta en su`pubspe.ymal`
> 
> ```
> mobile_scanner: ^3.0.0-beta.4
> ```
> 
> Captura de pantalla

Thank you, your answer has been quite useful.
