### ISSUE TITLE
Camera won't work when impeller enabled on IOS

### ISSUE THREAD

**Issue by dogukany** [juliansteenbakker/mobile_scanner#473]
When I activate impeller on iOS a blank white screen appears instead of the camera screen.

**Comment by CoryADavis** [comment]
I recently upgraded from mobile_scanner major version 2 to 3, while using Flutter 3.7.3 on iOS with impeller enabled. On both versions of mobile_scanner, our scanning solution is working and the camera is displayed properly.


The issue you experienced may be specific to another aspect of your particular solution.
