### ISSUE TITLE
Swift Compiler Error (Xcode): Cannot find 'pronunciation' in scope

### ISSUE THREAD

**Issue by Andy126** [juliansteenbakker/mobile_scanner#48]
I have some problems to use  mobile_scanner: ^0.2.0, Swift Compiler Error (Xcode): Cannot find 'pronunciation' in scope /Flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/mobile_scanner-0.1.3/ios/Classes/Util.swift:110:131]()

**Comment by SaikCaskey** [comment]
The issue seems to be here in `Util.swift`:

```swift
extension BarcodePersonName {
    var data: [String: Any?] {
        return ["first": first, "formattedName": formattedName, "last": last, "middle": middle, "prefix": prefix, "pronunciation": pronunciation, "suffix": suffix]
    }
```

If I just delete that argument from my locally cached plugin, it works (for now)

**Comment by juliansteenbakker** [comment]
This is because you are using an older version of MLKit cocoapod. Please run pod update in the ios folder of your application. I also constrained the version so this won't happen again.
