### ISSUE TITLE
Scanner does not work when autostart is set to false

### ISSUE THREAD

**Issue by Abdan009** [juliansteenbakker/mobile_scanner#484]
MobileScannerController controller = MobileScannerController(autoStart: false, );

  @override
  void initState() {
    super.initState();
    controller.start();
  }

**Comment by maximletushov** [comment]
Thame issue for me on both iOS and Android.
mobile_scanner 3.0.0
`onDetect` callback is never called when `autoStart` is `false`.
Please take a look.

**Comment by maximletushov** [comment]
I would like to add that I tried `controller.start()` inside `init` directly and inside`WidgetsBinding.instance.addPostFrameCallback` called from `init`. Result is the same : `onDetect` callback is never called.

**Comment by ecolque** [comment]
same problem

**Comment by chyhcq** [comment]
Still not resolved?
