### ISSUE TITLE
Swift Compiler Error (Xcode): Generic parameter 'ElementOfResult' could not be inferred

### ISSUE THREAD

**Issue by mustafayilmazdev** [juliansteenbakker/mobile_scanner#489]
This package works fine on android but there is an error on IOS platform.

Error;
Swift Compiler Error (Xcode): Generic parameter 'ElementOfResult' could not be inferred
/Users/mus/.pub-cache/hosted/pub.dev/mobile_scanner-3.0.0/ios/Classes/SwiftMobileScannerPlugin.swift:40:42

Could not build the application for the simulator.
Error launching application on iPhone 8.

This line gives the error:   let barcodesMap = barcodes!.compactMap { barcode in...

Package version: mobile_scanner: ^3.0.0
Flutter version: Flutter 3.7.3

**Comment by baimamboukar** [comment]
Same here! I came across the same problem....

**Swift Compiler Error (Xcode): Generic parameter 'ElementOfResult' could not be inferred
/Users/baimamboukar/.pub-cache/hosted/pub.dev/mobile_scanner-3.0.0/ios/Classes/SwiftMobileScannerPlugin.swift:40:42**

- Device: iPhone 8
- Flutter version: 3.7

**Comment by baimamboukar** [comment]
@juliansteenbakker 
I followed the configuration steps but still, it failed!
> Same here! I came across the same problem....
> 
> **Swift Compiler Error (Xcode): Generic parameter 'ElementOfResult' could not be inferred /Users/baimamboukar/.pub-cache/hosted/pub.dev/mobile_scanner-3.0.0/ios/Classes/SwiftMobileScannerPlugin.swift:40:42**
> 
> * Device: iPhone 8
> * Flutter version: 3.7

**Comment by CoryADavis** [comment]
You may need to update to the latest version of MacOS, then to the latest version of Xcode.

**Comment by mustafayilmazdev** [comment]
> You may need to update to the latest version of MacOS, then to the latest version of Xcode.

Thank you for your answer. This solved my problem.

**Comment by baimamboukar** [comment]
> > You may need to update to the latest version of MacOS, then to the latest version of Xcode.
> 
> Thank you for your answer. This solved my problem.

@mustafayilmazdev can you show the output of your ```flutter doctor``` please ?

**Comment by mustafayilmazdev** [comment]
> > > You may need to update to the latest version of MacOS, then to the latest version of Xcode.
> > 
> > 
> > Thank you for your answer. This solved my problem.
> 
> @mustafayilmazdev can you show the output of your `flutter doctor` please ?

[✓] Flutter (Channel stable, 3.7.3, on macOS 13.2.1 22D68 darwin-arm64, locale
    en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.75.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!

Hope it helps 😄

**Comment by leeyisoft** [comment]
> 您可能需要更新到最新版本的 MacOS，然后更新到最新版本的 Xcode。

Upgrading to the latest version of MaxOS and the latest version of Xcode can solve the problem. The key is that my home computer is MacBook Pro (Retina, 15-inch, Mid 2014), and there is no version upgrade.

How can I solve the problem (by adjusting swift code) when I cannot upgrade MacOS?
