### ISSUE TITLE
Error related to Uint8List in version 3.0.0

### ISSUE THREAD

**Issue by edrianbiagi** [juliansteenbakker/mobile_scanner#491]
After updating mobile_scanner to version 3.0.0 i came across this error when running the code.

![image](https://user-images.githubusercontent.com/67551467/219113845-c0fcf4bd-e337-4631-a543-1d4d30f5a648.png)

Has this ever happened to anyone? Can you help me?
Thanks in advance!

**Comment by juliansteenbakker** [comment]
Can you please post the output of `flutter doctor -v`?

**Comment by edrianbiagi** [comment]
I saw in another post that you had informed about the flutter update.
After updating to version 3.3.9 it worked normally.
