### ISSUE TITLE
Error in SwiftMobileScannerPlugin when building the project on iOS

### ISSUE THREAD

**Issue by aoancea** [juliansteenbakker/mobile_scanner#495]
Hello,

I'm getting this error when trying to build the project on iOS. Android works perfect!

![image](https://user-images.githubusercontent.com/4282532/219615953-f11f6169-6b6b-41cf-a44c-2f38c35eacc4.png)

Any ideas on what it might be ?

**Comment by Pierre2tm** [comment]
I have the same error

**Comment by CoryADavis** [comment]
#489

**Comment by leeyisoft** [comment]
> #489

Upgrading to the latest version of MaxOS and the latest version of Xcode can solve the problem. The key is that my home computer is MacBook Pro (Retina, 15-inch, Mid 2014), and there is no version upgrade.

How can I solve the problem (by adjusting swift code) when I cannot upgrade MacOS?

**Comment by navaronbracke** [comment]
Going to close this issue as the related XCode bug seems to be fixed.
