### ISSUE TITLE
Problem with small qr

### ISSUE THREAD

**Issue by Batuhanseckin** [juliansteenbakker/mobile_scanner#503]
Hello everyone! Thanks for this great package. But there are things I don't understand.

I have an application that I developed with this package. It is very important for me to be able to read the barcode quickly and comfortably while the application is running.

As you can see in the video, when I scan the same barcode with 3 different applications, I see a huge speed difference between them. My app can't even read the barcode if I don't get close enough.

https://user-images.githubusercontent.com/32499207/220156183-14c5e79f-8d0a-4691-9046-eb527d45490c.mp4

![barcode](https://user-images.githubusercontent.com/32499207/220156897-fa8f52e9-ed74-4753-8e37-79a548156880.jpeg)

Note: I am using mobile_scanner: ^3.0.0. 

Anyone have any suggestions or recommendations? Thanks in advance..

**Comment by juliansteenbakker** [comment]
Right now MLKit does not fully support inverted qr codes like the one you showed.
