### ISSUE TITLE
Platform exception Called state before initializing

### ISSUE THREAD

**Issue by yiorgosc** [juliansteenbakker/mobile_scanner#507]
hi, any indication why I get this exception? thanks a lot

![Screenshot 2023-02-23 114452](https://user-images.githubusercontent.com/35425088/220872153-d7332cc2-064e-47ad-b8e5-137402494185.png)

**Comment by navaronbracke** [comment]
We did a big refactor of the internal state of the MobileScannerController in version 5.0.0-beta.1

Could you retest this? Although I don't think it is likely that this issue still occurs.

**Comment by yiorgosc** [comment]
thanks but you are right. this issue doesn't occur any more.

**Comment by navaronbracke** [comment]
Thanks for confirming!
