### ISSUE TITLE
allowDuplicates variable does not exist in version 3.0.0

### ISSUE THREAD

**Issue by RodrigoScott** [juliansteenbakker/mobile_scanner#511]
I have looked for the variable in the documentation and code and I have not found it. How can I avoid scanning the same code multiple times?

<img width="352" alt="image" src="https://user-images.githubusercontent.com/25831861/220989181-f4617fcd-b89d-48ef-82f2-6258eccfc722.png">

**Comment by juliansteenbakker** [comment]
It is now called `detectionSpeed`.
