### ISSUE TITLE
ios gallery typecast issue

### ISSUE THREAD

**Issue by neel-sharma** [juliansteenbakker/mobile_scanner#532]
If I pick the same QR from a picture from Gallery in Android it works fine. But when I pick it in IOS it gives me a type casting error saying.

This is an error on the App. level - MobileScannerException: code genericError, message: No camera found or failed to open camera!
This is an error on the App. level - type '_Map<Object?, Object?>' is not a subtype of type 'List<dynamic>' in type cast

While debugging I found that the error comes in _handleEvent. I was getting the exact values from the Barcode in event['data']. But I suspect the error comes in when we parse the same in list.

  void _handleEvent(Map event) {
    final name = event['name'];
    final data = event['data'];

    switch (name) {
      case 'torchState':
        final state = TorchState.values[data as int? ?? 0];
        torchState.value = state;
        break;
      case 'barcode':
        if (data == null) return;
        final parsed = (data as List)
            .map((value) => Barcode.fromNative(value as Map))
            .toList();

The same issue won't be there when we are scanning from the camera in IOS. It only happens after picking from Gallery.

The Sample QR I was scanning: 
![sample_qr](https://user-images.githubusercontent.com/75809664/223198577-3331c031-daed-4339-978a-49fcf8e4889e.jpeg)

**Comment by abldabl** [comment]
same issue, did you solve it?

**Comment by abldabl** [comment]
> > same issue, did you solve it?
> 
> Try #534 . It worked for me.

Awesome! thanks, it worked
