### ISSUE TITLE
onDetect Running Multiple Times After AppLifecycleState Changed

### ISSUE THREAD

**Issue by Rqmco** [juliansteenbakker/mobile_scanner#536]
When you scan a code after changing the applifecyclestate it will call onDetect as many times as the applifecyclestate changed plus default. For example, you went to the home of the phone and back to the app twice, it will call on detect 3 times (one time default and the other 2 times because of the applifecyclestate changes).

**Comment by trdmm** [comment]
same to me

**Comment by rapan931** [comment]
fixed?
- https://pub.dev/packages/mobile_scanner/changelog#330
- https://github.com/juliansteenbakker/mobile_scanner/pull/594
