### ISSUE TITLE
!!! Android error on start: called start() while already started

### ISSUE THREAD

**Issue by Shakle** [juliansteenbakker/mobile_scanner#539]
After some update recently - wether it was Android 13 QPR 2 (March Pixel update) or Flutter 3.7.7 on first camera initialization I get this error. In Example app it also happens. Did not check on other devices. I also guess that something related to it causes a crash from time to time when disabling/enabling camera.

ℹ️ Environment:
- Pixel 7 Pro. Android 13 march 2023

✅ Steps to reproduce:
1. Grant permissions to camera
2. Freshly open an app
3. Open camera screen

💡 Actual result:
- mobile_scanner: MobileScannerException: code genericError, message: Called start() while already started

👍 Expected result:
- no error

**Comment by tsomone** [comment]
You can do the trick by reloading camera with this code,

> errorBuilder: (context, error, child) {
>       controller.stop();
>       controller.start();
>       return ScannerReloadingWidget(error: error);
> }

its not recommended, but its working in my case

**Comment by BryceCYB** [comment]
Add   ```controller.stop();``` in ```initState``` works for me.
```@override
  void initState() {
     // To fix on start error
    controller.stop();
    super.initState();
  }
```

**Comment by sebatorresi** [comment]
In my case I did 

`void initState() {
     // To fix on start error
    cameraController.stop();
    super.initState();
  }`

**Comment by Ishchik** [comment]
It also reproduces when hitting Hot Restart on the screen with MobileScanner and navigating back to it

**Comment by arnabonetraker** [comment]
@juliansteenbakker  MobileScannerException: code genericError, message: Called start() while already started.

**Comment by maulikchak** [comment]
same issue

**Comment by tologonkudaiberdiuulu** [comment]
Any progress @juliansteenbakker ?

**Comment by Logaritma26** [comment]
same

**Comment by JoshPark1** [comment]
We are seeing the same issue on iOS. Adding controller.stop() to initState does not resolve the issue.

**Comment by Blvckleg** [comment]
> We are seeing the same issue on iOS. Adding controller.stop() to initState does not resolve the issue.

Have you tried this? 

https://github.com/juliansteenbakker/mobile_scanner/issues/589#issuecomment-1599677867

While I definitelly think instantiating a new controller everytime isn't the prettiest I ended up using the same workaround as the user who wrote the comment.

Works fine for me. Maybe this can help?

I am still hoping this is getting fixed anytime soon though.

**Comment by navaronbracke** [comment]
This should no longer occur with the new beta, version 5.0.0-beta.1 , as the lifecycle is now no longer managed by `mobile_scanner` itself, due to issues with widget tree reparenting.

**Comment by cbassols** [comment]
> This should no longer occur with the new beta, version 5.0.0-beta.1 , as the lifecycle is now no longer managed by `mobile_scanner` itself, due to issues with widget tree reparenting.

I've been fighting with this issue for the last two hours in the version 5.0.0-beta.2.
If I make a hot restart, I get "MobileScannerException: code genericError, message: Called start() while already started!"
The only way I have to make it work is completely closing the App and reopening it.

**Comment by navaronbracke** [comment]
I am aware that we should handle hot restart better, we have a tracking issue for that specifically:
https://github.com/juliansteenbakker/mobile_scanner/issues/773

I still need to figure out if we can intercept it internally, or provide users with guidance around the use of `reassemble()`.

**Comment by Quelich** [comment]
In my case, users were navigated to a new page that includes the scanner but when i do this back-and-forth navigation multiple times i was getting this error in debug console:
`W/WindowOnBackDispatcher(11079): OnBackInvokedCallback is not enabled for the application.
W/WindowOnBackDispatcher(11079): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.`

so i have updated `AndroidManifest.xml` in `android/app/src/main` by adding this line   `android:enableOnBackInvokedCallback="true"` and it works.

For example: 
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="your.package.name">

    <application
        android:label="Your App Name"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher"
        android:enableOnBackInvokedCallback="true">
        <!-- ... other application configurations ... -->
    </application>

</manifest>
```

However, this change only works for targeting `Android 13 (API level 33) and above`.

**Comment by joeyojoeyo** [comment]
@navaronbracke this keeps happening for me too:

Flutter 3.24.2 • channel stable 
Tools • Dart 3.5.2 
on Android (API Level 33 and above)
when testing on a physical device

when it happens, the screen showing up is simply plain white, with nothing inside it. That is, visually. in the widget tree, all the widgets are built normally, which is somewhat weird (The QR-Code Scanner / Camera simply does not show up and the entire screen stays white).

And the error causing this behaviour is the same as above: Our app triggers a screen using the MobileScanner, and when we open and close that one multiple times, by the attempt 10, we get the `MobileScannerException: code genericError, message: Called start() while already started`.

Any idea why this is happening?

**Comment by fulstadev** [comment]
@navaronbracke  this keeps happening for me too:

Flutter 3.24.2 • channel stable Tools
Dart 3.5.2
Android (API Level 33 and above) 
when testing on a physical device

when it happens, the screen showing up is simply plain white, with nothing inside it. That is, visually. in the widget tree, all the widgets are built normally, which is somewhat weird (The QR-Code Scanner / Camera simply does not show up and the entire screen stays white, which is the background colour of our app's Scaffold).
And the error causing this behaviour is the same as the one above: Our app triggers a screen using the MobileScanner, and when we open and close that one multiple times, we after some attempts get the `MobileScannerException: code genericError, message: Called start() while already started.`, with the entire screen being white, no camera being visually active.

Any idea why this is happening?
