### ISSUE TITLE
Privacy issue: Firebase logging or "performance monitoring"

### ISSUE THREAD

**Issue by chickahoona** [juliansteenbakker/mobile_scanner#553]
It seems that MLKit is sending every 15 minutes a request to https://firebaselogging.googleapis.com/v0cc/log/batch?format=json_proto3 

You can see that in your console:

![image](https://user-images.githubusercontent.com/8075146/227522275-99a1b93b-75fd-4ce7-bf53-cc2b0cad0a56.png)

Details about this can be found her:
https://stackoverflow.com/questions/71465067/disable-firebase-logging-for-google-ml-kit-library-in-android
https://firebase.google.com/docs/perf-mon/disable-sdk?platform=android

This is some concern for all companies in Germany / Europe due to privacy restrictions as the ip address alone is considered "personal identifiable inforamtion" and companies werre already sued for including e.g. google fonts on their websites.

Is there a chance that one could disable this logging?

**Comment by hukell** [comment]
Did you solve it? I have the same problem

**Comment by chickahoona** [comment]
No I am sorry. I haven't investigated this more. I was fighting another issue and was forced to use an older lib that's not based on MLKit.

**Comment by juliansteenbakker** [comment]
I can't disable this via this plugin, since it's something that is handled from MLKit rather than this plugin. I can only refer you to MLKits privacy policy: https://developers.google.com/ml-kit/terms

**Comment by Coin-ai** [comment]
"You are responsible for informing users of your app about Google’s processing of ML Kit metrics data as required by applicable law." this need add to readme

**Comment by pablojimpas** [comment]
What other library did you use to address this concern @chickahoona?

It's so sad that there is no way to opt out of this, since this is the only viable plugin for QR scanning with Flutter that I've found.

**Comment by chickahoona** [comment]
I am using at the moment this one here https://pub.dev/packages/qr_code_scanner

**Comment by pablojimpas** [comment]
> I am using at the moment this one here https://pub.dev/packages/qr_code_scanner

Thanks! I think that I will migrate to [`flutter_zxing`](https://pub.dev/packages/flutter_zxing). It's basically a wrapper around [zxing-cpp](https://github.com/zxing-cpp/zxing-cpp), a reimplementation in C++ of the original zxing Java library, which is actively maintained.

Seems harder to use, but it should have high performance, of course, works perfectly offline and without any privacy concerns.

**Comment by chickahoona** [comment]
Thanks for sharing that one. Looks good with support for Linux / Web / Macos without too much of a hassle to install it!

**Comment by fe-data** [comment]
To get rid of those annoying "calling home" events just add this code just after the start of 'main'
```
  final dir = await getApplicationDocumentsDirectory();
  final path = dir.path.substring(0, dir.path.length - 11);
  final file = File('$path/databases/com.google.android.datatransport.events');
  await file.writeAsString('Fake');
```
I know: a dirty trick, but on Android it works. It starts complaining that the file is not a database, but it works fine.

**Comment by elliotwutingfeng** [comment]
> To get rid of those annoying "calling home" events just add this code just after the start of 'main'
> 
> ```
>   if (Platform.isAndroid) {
>     final dir = await getApplicationDocumentsDirectory();
>     final path = dir.path.substring(0, dir.path.length - 11);
>     final file = File('$path/databases/com.google.android.datatransport.events');
>     await file.writeAsString('Fake');
>   }
> ```
> 
> I know: a dirty trick, but on Android it works. It starts complaining that the file is not a database, but it works fine.

When using **main() async** I had to put it after **runApp(...);** otherwise **runApp(...)** won't execute. 

`final path = dir.path.substring(0, dir.path.length - 11);` gives the wrong path (extra slash) for me, `final path = dir.parent.path;` should be more accurate.

```dart
Future<void> main() async {
  // ...
  // <some other async calls>
  // ...
  runApp(const App());
  if (Platform.isAndroid) {
    final dir = await getApplicationDocumentsDirectory();
    final path = dir.parent.path;
    final file =
        File('$path/databases/com.google.android.datatransport.events');
    await file.writeAsString('Fake');
  }
}
```

**Comment by Allen-Guof** [comment]
I found that MLKit collects user's SIM data before privacy consent, which is also illegal in our region. So, I wrote a manual initialization method myself, not sure if it's useful for everyone?
https://github.com/Allen-Guof/mobile_scanner/commit/57d082253608fd40ca6bca9e8cb1ee61dda5f9e8

**Comment by shirozatou** [comment]
I made a gist for this risk. Android only. :⁠-⁠)
https://gist.github.com/shirozatou/5a80b064498c81e767541f071f6fe33b

**Comment by MSL-BIT** [comment]
> To get rid of those annoying "calling home" events just add this code just after the start of 'main'
> 
> ```
>   if (Platform.isAndroid) {
>     final dir = await getApplicationDocumentsDirectory();
>     final path = dir.path.substring(0, dir.path.length - 11);
>     final file = File('$path/databases/com.google.android.datatransport.events');
>     await file.writeAsString('Fake');
>   }
> ```
> 
> I know: a dirty trick, but on Android it works. It starts complaining that the file is not a database, but it works fine.

Does this also works on iOS?

**Comment by fe-data** [comment]
> > To get rid of those annoying "calling home" events just add this code just after the start of 'main'
> > ```
> >   if (Platform.isAndroid) {
> >     final dir = await getApplicationDocumentsDirectory();
> >     final path = dir.path.substring(0, dir.path.length - 11);
> >     final file = File('$path/databases/com.google.android.datatransport.events');
> >     await file.writeAsString('Fake');
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I know: a dirty trick, but on Android it works. It starts complaining that the file is not a database, but it works fine.
> 
> Does this also work on iOS?

Noop

**Comment by goerlitz** [comment]
There is another solution in the [original Stackoverflow question](https://stackoverflow.com/questions/71465067/disable-firebase-logging-for-google-ml-kit-library-in-android). Instead of corrupting the database it disables the scheduler in the Android manifest. Works well for me.

`android/app/src/main/AndroidManifest.xml`
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">
<application>
    ...
    <!--Remove Firebase Logging-->
    <service
        android:name="com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService"
        tools:node="remove">
    </service>
</application>
```
