### ISSUE TITLE
Focus needed

### ISSUE THREAD

**Issue by georges-ph** [juliansteenbakker/mobile_scanner#558]
The package either doesn't work on web or it needs focus.

When I was trying it I was using a barcode image on my pc and scan it from my phone on the web version. I have to place the phone really close to the barcode for it to be able to detect it. On android this is not an issue. If I'm 5 meters away and scan the barcode it is able to detect it fast with no problem, but not on the web.

But when I was trying to scan any item on my hand it wasn't detecting it. If I try to be as close as I can it becomes blurry. And I couldn't find a property in the widget for focusing.

**Comment by teolemon** [comment]
Duplicate of #343
