### ISSUE TITLE
Running analyze again after navigator pop

### ISSUE THREAD

**Issue by myoganugraha** [juliansteenbakker/mobile_scanner#58]
Hi, previously i've raise the issue
[#41 ](https://github.com/juliansteenbakker/mobile_scanner/issues/41), and it has been closed

but i don't think the latest version has fixed this issue,
so i create minimal reproduce about my issue, [reproduce repo](https://github.com/myoganugraha/reproduce_scan_after_pop)

which after i get the scan result and navigate to result screen, and then pop to preview / scanner screen,
the controller won't analyze the image

or is it impossible to run the analyze image after navigate ?

thanks

**Comment by juliansteenbakker** [comment]
Hi, this is because allowDuplicates is false, and i think you are trying to scan the same barcode again after pop().
I will see if i can make a function to reset the lastScanned barcode to null.

**Comment by myoganugraha** [comment]
well, thank you @juliansteenbakker for the quick response
yes, you right it happen because i'm using same barcode

thanks and this issue can be close now

**Comment by myoganugraha** [comment]
> ```dart
>  if (this.barcode != barcode.rawValue)
> ```

well thank you,
it's works :D

**Comment by juliansteenbakker** [comment]
Happy to help!
