### ISSUE TITLE
[bug]: Swift Compiler Error (Xcode): Value of type 'AVCaptureDevice' has no member 'automaticallyAdjustsFaceDrivenAutoFocusEnabled'

### ISSUE THREAD

**Issue by lockiechen** [juliansteenbakker/mobile_scanner#582]
<img width="931" alt="image" src="https://user-images.githubusercontent.com/33082528/230263940-e7685aa0-ceae-40ed-bb90-a0f12fc689f2.png">
can not build ipa because this error

**Comment by lockiechen** [comment]
version: 3.2.0

**Comment by sarinkarma** [comment]
Facing the same issue. Any update on this?

**Comment by faaqi** [comment]
Idk whether its good or not but I replaced this line by:

`device.isSmoothAutoFocusEnabled = false`

to make it work.

**Comment by lockiechen** [comment]
> Idk whether its good or not but I replaced this line by:
> 
> `device.isSmoothAutoFocusEnabled = false`
> 
> to make it work.

@faaqi cloud you show me where to replaced this line?

**Comment by faaqi** [comment]
@lockiechen 

1. Try to open the project in xcode and build / run it using xcode. You'll see that build failed and errors will appear. Clicking on that error will open this file and specific line where error occurs.

2. Otherwise , you can find this file as well. I attached the screenshot so that you can view the path. 

- YourProject
        - ios
               - .symlinks
                         - plugins
                                  - mobils_scanner
                                      - ios
                                            - Classes
                                                 - MobileScanner
                                                         


<img width="1436" alt="image" src="https://user-images.githubusercontent.com/61233208/230829428-b214bef8-d3a4-4926-8674-180e73b13566.png">

**Comment by lockiechen** [comment]
i wonder why the bug only occur when i build ipa package

**Comment by faaqi** [comment]
That needs investigation.

Because when I build IPA after replacing that line. I get this new [issue](https://github.com/juliansteenbakker/mobile_scanner/issues/583)

**Comment by lockiechen** [comment]
@juliansteenbakker any suggestion?

**Comment by aoancea** [comment]
I also have the same problem. Are there any updates on it?

**Comment by aoancea** [comment]
@lockiechen @faaqi any ideas if someone is looking into this ?

**Comment by faaqi** [comment]
> @lockiechen
> 
> 1. Try to open the project in xcode and build / run it using xcode. You'll see that build failed and errors will appear. Clicking on that error will open this file and specific line where error occurs.
> 2. Otherwise , you can find this file as well. I attached the screenshot so that you can view the path.
> 
> * YourProject
>   - ios
>   - .symlinks
>   - plugins
>   - mobils_scanner
>   - ios
>   - Classes
>   - MobileScanner
> 
> <img alt="image" width="1436" src="https://user-images.githubusercontent.com/61233208/230829428-b214bef8-d3a4-4926-8674-180e73b13566.png">

@aoancea , Replacing this line in xcode worked for me. But I was not satisfied with overall performance of the plugin.

I ended up using this [plugin](https://pub.dev/packages/scan)

**Comment by phong016688** [comment]
Can you quickly fix this problem, or is there a better way to solve this problem. Thank you

**Comment by afdaldev** [comment]
any update for this issue?

**Comment by dariobrux** [comment]
Updating MacOs to Ventura 13.5.1 and updating XCode to 14.3.1 they solve this issue
