### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "GoogleMLKit/BarcodeScanning"

### ISSUE THREAD

**Issue by tikno09** [juliansteenbakker/mobile_scanner#595]
[!] CocoaPods could not find compatible versions for pod "GoogleMLKit/BarcodeScanning":
  In Podfile:
    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 3.2.0, which depends on
      GoogleMLKit/BarcodeScanning (~> 4.0.0)

None of your spec sources contain a spec satisfying the dependency: `GoogleMLKit/BarcodeScanning (~> 4.0.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
 
<img width="931" alt="Screenshot 2023-04-17 at 10 39 33" src="https://user-images.githubusercontent.com/43721614/232372717-c3c39abe-1185-4750-bf7a-ebe0b38f1184.png">

**Comment by subair-zufi** [comment]
Can I know, how did you resolve this issue?

**Comment by vely-digital** [comment]
Just gona leave here my fix for this.

I found that in my pubspec.lock, Podfile.lock and ios/symlinks there were old references. 

1. Delete pubspec.lock, ios/Podfile.lock and ios/.symlinks
2. run 'flutter clean'
3. run 'flutter pub get'
4. Start app in debug mode

Hope this will help someone!
