### ISSUE TITLE
Scanner is using only fornt camera when using web app on android.

### ISSUE THREAD

**Issue by Antoni-Czaplicki** [juliansteenbakker/mobile_scanner#60]
When I open the web app on my phone, the scanner is only used from the front camera. I tried to set the facing of the camera using initial values or change it using `controller.switchCamera ()` but it didn't do anything.

**Comment by djpnewton** [comment]
made PR here https://github.com/juliansteenbakker/mobile_scanner/pull/78

**Comment by jaredsburrows** [comment]
@juliansteenbakker #78 was merged. If this is fixed, can we release a new version?
