### ISSUE TITLE
Gradle 8 support, Flutter 3.7.12+

### ISSUE THREAD

**Issue by Shakle** [juliansteenbakker/mobile_scanner#602]
https://github.com/flutter/flutter/issues/125181

Flutter app android module can't be upgraded to gradle 8, until all dependencies which use native code are also upgraded or at least have namespace in app/build.gradle.

android {
    namespace = "com.example.myapp"
    ...
}

**Comment by navaronbracke** [comment]
@Shakle Apparently only the example app had its namespace set properly. #603 Should fix it.
