### ISSUE TITLE
Conflicting protobuf version

### ISSUE THREAD

**Issue by itjhin** [juliansteenbakker/mobile_scanner#61]
Trying to use mobile_scanner (1.0.0) package with flutter_blue (0.8.0 - latest version) in my app development. During the Pod install steps when running in iOS system, I was greet with the follow error:
-- snipets --

> [!] CocoaPods could not find compatible versions for pod "Protobuf":
      In snapshot (Podfile.lock):
        Protobuf (= 3.11.4, ~> 3.11.4)

      In Podfile:
        flutter_blue (from `.symlinks/plugins/flutter_blue/ios`) was resolved to 0.0.1, which depends on
          flutter_blue/Protos (= 0.0.1) was resolved to 0.0.1, which depends on
            Protobuf (~> 3.11.4)

        mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 0.0.1, which depends on
          GoogleMLKit/BarcodeScanning (~> 2.6.0) was resolved to 2.6.0, which depends on
            MLKitBarcodeScanning (~> 1.7.0) was resolved to 1.7.0, which depends on
              MLKitVision (~> 3.0) was resolved to 3.0.0, which depends on
                Protobuf (~> 3.12)

-------------

Tried the suggested fix from the IDE ("pod repo update" && "pod install --repo-update") but it doesnt resolve the issue.

**Comment by juliansteenbakker** [comment]
Please mind that the original flutter_blue is not maintained and is using old version of packages. I suggest using https://pub.dev/packages/flutter_blue_plus which is a fork with updated versions of dependencies.

**Comment by itjhin** [comment]
Will update to the flutter_blue_plus and try it again. 
Thanks!

**Comment by itjhin** [comment]
Issue resolved using the updated dependency in flutter_blue_plus package.
