### ISSUE TITLE
clear lastScanned sometimes

### ISSUE THREAD

**Issue by ghost** [juliansteenbakker/mobile_scanner#62]
Hello dear
best regards

**Comment by facceapps** [comment]
The problem has been resolved
thank you

**Comment by ryeates1** [comment]
> i have solved the issues thank you

How did you solve this issue?

**Comment by olivierkastel** [comment]
Agree, I am facing the same issue. How do we reset the history, so we can re-scan codes?

**Comment by facceapps** [comment]
> Agree, I am facing the same issue. How do we reset the history, so we can re-scan codes?

change allowDuplicates:false to true
/////////////
String lastScanned;
/////////////
 onDetect: (barcode, args) {
 setState(() {
if (lastScanned != barcode.rawValue) {
     this.barcode = barcode.rawValue;
     lastScanned = this.barcode;
     print(this.barcode);
   }
 });
 }),
/////////////
And if you want to scan the same barcode ?
lastScanned='';

**Comment by raicaetano** [comment]
I am also going through the same situation. In my application, when an error occurs, I need to read a different code or close the scanner screen and open it again to read the code that gave an error, as the allowDuplicates flag is set to false. If I set the allowDuplicates flag value to true, the scanner detects too many reads and crashes the application.

It would be very helpful to implement this enhancement.

**Comment by facceapps** [comment]
Hello dear
If you need to close the scanning screen and open it again, dont forget to
use (dispose()) when closing the page so as not to face a problem when
opening the page again
best regards

‫في الجمعة، 25 مارس 2022 في 3:03 ص تمت كتابة ما يلي بواسطة ‪raicaetano‬‏ <‪
***@***.***‬‏>:‬

**Comment by facceapps** [comment]
change allowDuplicates:false to true
/////////////
String lastScanned;
/////////////
onDetect: (barcode, args) {
setState(() {
if (lastScanned != barcode.rawValue) {
this.barcode = barcode.rawValue;
lastScanned = this.barcode;
print(this.barcode);
}
});
}),
/////////////
And if you want to scan the same barcode ?
lastScanned='';

‫في الجمعة، 18 مارس 2022 في 10:10 م تمت كتابة ما يلي بواسطة
‪olivierkastel‬‏ ***@***.***‬‏>:‬

**Comment by facceapps** [comment]
> Author

I did the following
Now I don't have any problems at all

**Comment by facceapps** [comment]
> > Agree, I am facing the same issue. How do we reset the history, so we can re-scan codes?
> 
> change allowDuplicates:false to true ///////////// String lastScanned; ///////////// onDetect: (barcode, args) { setState(() { if (lastScanned != barcode.rawValue) { this.barcode = barcode.rawValue; lastScanned = this.barcode; print(this.barcode); } }); }), ///////////// And if you want to scan the same barcode ? lastScanned='';

I did the following
Now I don't have any problems at all

**Comment by juliansteenbakker** [comment]
Please see the following parameter in order to clear lastscanned: https://github.com/juliansteenbakker/mobile_scanner/blob/5ebc65e96e8de7224e3a7265d388a8d5d00ee3fd/lib/src/mobile_scanner_controller.dart#L66
