### ISSUE TITLE
.analyzeImage() dosen't work on Android.

### ISSUE THREAD

**Issue by ttb-inc** [juliansteenbakker/mobile_scanner#620]
Hi

I'm loading the image directly to get the QR data.
However, .analyzeImage() is not working.
It doesn't even throw an exception.
It works fine on iOS.

```
    var mobileScannerController = MobileScannerController(formats: [BarcodeFormat.qrCode]);

    try {
      barcodesStreamSubscription = mobileScannerController.barcodes.listen((BarcodeCapture barcodes) {
        if (barcodes.barcodes.isNotEmpty) {
          detectedCode = barcodes.barcodes[0].rawValue ?? '';
        }
      });

      barcodesStreamSubscription.onError((e) {
        consoleLog(e.toString());
      });

      await mobileScannerController.analyzeImage(imagePath);
    } catch (e) {
      print(e.toString());
    }
```
Neither .listen() nor .onError() are called.
Doesn't this work on Android?

Thank you

---
The storage permission is fine.

mobile_scanner: 3.2.0

[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E772610a darwin-arm64, locale ko-KR)
    • Flutter version 3.7.12 on channel stable at /Users/jeonglockpark/Desktop/work/flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/jeonglockpark/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

**Comment by raywoocn** [comment]
same issue here, any solution?

**Comment by ttb-inc** [comment]
> 

I'm still waiting.

**Comment by Alex-A4** [comment]
Same problem, works fine on ios, but android is not working (tested on Android 14)

**Comment by dahvlhldle** [comment]
Android 14 does not work, while some other versions can work partially. It is strange that the cropped image success.
