### ISSUE TITLE
Build fail with AGP 8.0

### ISSUE THREAD

**Issue by ttb-inc** [juliansteenbakker/mobile_scanner#621]
Hi,
Please resolve issues with AGP 8.0 on Android.(’namespace’)
Thank you.

**Comment by navaronbracke** [comment]
What version are you using? This was fixed in version 3.2.1

**Comment by ttb-inc** [comment]
I'm using 3.2.0
I will wait for the next version.

Thank you

**Comment by Nodios** [comment]
@navaronbracke version 3.2.1 is not available [here](https://pub.dev/packages/mobile_scanner/versions). How should it be installed?

**Comment by navaronbracke** [comment]
@Nodios I don't think @juliansteenbakker published it as a release yet.

You can use a git override in your pubspec.yaml instead:

```
mobile_scanner:
   git: https://github.com/juliansteenbakker/mobile_scanner.git
```

**Comment by navaronbracke** [comment]
@Nodios Version 3.2.1 has been published for a while now. The plugin itself also uses Gradle 8 since a few versions.
