### ISSUE TITLE
Start + Stop will make the camera dissappear

### ISSUE THREAD

**Issue by janikontturi** [juliansteenbakker/mobile_scanner#624]
if wi will stop the camera after it has read the code, it will work great, but after that when i trigger the start command, it will make the whole camera disappear.

`
cameraController.stop();
Timer(Duration(seconds: 3), () => {cameraController.start()});
`

**Comment by incon** [comment]
I have the same issue

**Comment by navaronbracke** [comment]
When you start a camera, the camera needs time to allocate a Texture.
Switching the camera controller to `start > stop > start` and so on, disposes of the old texture, hence the closed camera view.

So this is working as intended.
