### ISSUE TITLE
Permission error on web platform after flutter 3.10 upgrade

### ISSUE THREAD

**Issue by MBjoern** [juliansteenbakker/mobile_scanner#625]
Handling the permissions doesn't work on web anymore after upgrading to Flutter 3.10.
The library appears to be not able to gather the permissions

You get a warning saying ... even if the permissions are manually added in the browser's page settings.

mobile_scanner: MobileScannerException: code permissionDenied, message: TypeError: Cannot read properties of undefined (reading 'BrowserMultiFormatReader')

Tested on chrome and safari browsers

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-x64, locale en-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.3)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

**Comment by fernandolop** [comment]
Same here

**Comment by Amphaal** [comment]
https://github.com/juliansteenbakker/mobile_scanner/issues/622#issuecomment-1544908494

**Comment by Solutionstbd** [comment]
Awaiting resolution. Thanks in advance

**Comment by teolemon** [comment]
@Solutionstbd @Amphaal @MBjoern @fernandolop I'm closing this one in favor of #622
