### ISSUE TITLE
Flutter 3.10 (tracker issue)

### ISSUE THREAD

**Issue by teolemon** [juliansteenbakker/mobile_scanner#631]
### What

- [x] #622 
- [x] #637 

### Part of
- #260

**Comment by UliPrantz** [comment]
Any progress report on this one?

**Comment by aliaksei-liavonik** [comment]
I think this issue has really high priority. This is already almost a month after Flutter 3.10 has been released and the mobile_scanner package is not working on the web, where it is not even used...
@juliansteenbakker, can we expect a fix for this in the near future?

**Comment by teolemon** [comment]
@aliaksei-liavonik could you help ? https://github.com/juliansteenbakker/mobile_scanner/issues/652

**Comment by navaronbracke** [comment]
@teolemon @juliansteenbakker I'll try to look into this today.
