### ISSUE TITLE
scanWindow not applied correctly

### ISSUE THREAD

**Issue by glemartret** [juliansteenbakker/mobile_scanner#633]
I'm trying to restrict the scan window to the size of the camera preview which is constrained by a `SizedBox` but out of screen barcodes (above and below my SizedBox) are still scanned.

Maybe I misuse `scanWindow` parameter ? Or is there an issue with the cover BoxFit ?

```
SizedBox(
	height: 250,
	width: double.infinity,
	child: MobileScanner(
		fit: BoxFit.cover,
		scanWindow: const Rect.fromLTWH(0, 0, double.infinity, 250),
		onDetect: (BarcodeCapture barcode) async {
			// ...
		}
	),
)
```

**Comment by navaronbracke** [comment]
IIRC MLKit does not allow for specifying the scan area. You'll have to work with the `corners` property of the `Barcode` in the `BarcodeCapture` to figure out if the scanned barcode should be 'accepted'.

**Comment by sdkysfzai** [comment]
I actually modified the Mobile Scanner widget to make it work.

**Comment by sdkysfzai** [comment]
I had the same issue, I fixed it by doing modification to the package itself. Lmk if you need it and I'll make a fork and update it.

**Comment by sdkysfzai** [comment]
> I'm trying to restrict the scan window to the size of the camera preview which is constrained by a `SizedBox` but out of screen barcodes (above and below my SizedBox) are still scanned.
> 
> Maybe I misuse `scanWindow` parameter ? Or is there an issue with the cover BoxFit ?
> 
> ```
> SizedBox(
> 	height: 250,
> 	width: double.infinity,
> 	child: MobileScanner(
> 		fit: BoxFit.cover,
> 		scanWindow: const Rect.fromLTWH(0, 0, double.infinity, 250),
> 		onDetect: (BarcodeCapture barcode) async {
> 			// ...
> 		}
> 	),
> )
> ```

https://github.com/sdkysfzai/mobile_scanner_upgrade
You can use this, it fixes this issue.

**Comment by holailusoria** [comment]
Looks like scanWindow still doesn't work.
If I don't assign anything to this parameter, I can scan any area of the screen, which is to be expected.
As soon as I assign any value, I can't scan at all.

**Comment by k435467** [comment]
+1 😢
I've encountered the same issue where the actual scan window doesn't match my expectations. I used `Rect.fromCenter` to define the scan window. However, it seems that the actual scanning area is biased toward the top of the camera's view. I'm unsure about how to properly center the scan window. If this isn't a bug, I'm hoping someone could provide a functional example along with an overlay widget.
```dart
// not working properly
class ScanScreen extends StatelessWidget {
  const ScanScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return MobileScanner(
      controller: MobileScannerController(
        detectionSpeed: DetectionSpeed.normal,
      ),
      fit: BoxFit.contain, // Box.Fit.Cover is tried
      scanWindow: Rect.fromCenter(
        center: Offset.zero,
        width: double.infinity,
        height: 400,
      ),
      overlay: Text('something'),
      onDetect: (capture) {
        final List<Barcode> barcodes = capture.barcodes;
        for (final barcode in barcodes) {
          debugPrint(
              'Barcode found! rawValue=${barcode.rawValue}, format=${barcode.format}, type=${barcode.type}');
        }
      },
    );
  }
}
```
mobile_scanner: `3.4.1`
device info: 
```
Device - Redmi 10A
UI - MIUI Global 12.5.2.0(RCZTWXM)
OS - 11 RP1A.200720.011
```

**Comment by guizamberlam** [comment]
> IIRC MLKit does not allow for specifying the scan area. You'll have to work with the `corners` property of the `Barcode` in the `BarcodeCapture` to figure out if the scanned barcode should be 'accepted'.
> 
> You'll also need the coordinates of the overlay widget, but you can get that from its RenderBox (using its BuildContext).
> 
> Once you get those two things, make a `Rect` for each of them, and use `Rect.intersects()` to figure out if the barcode intersects your scan area :)

Wanting to know if this is still the only way to solve this problem, I have the same exact scenario where I am limiting the preview but I still scan things outside it. @navaronbracke

**Comment by navaronbracke** [comment]
We haven't been able to update MLKit in a while (it really hasn't gotten any updates :/ ) so this has not yet changed.

**Comment by guizamberlam** [comment]
That's a bummer, I am giving mainteinance to a project that is using [another package](https://pub.dev/packages/qr_code_scanner_plus) which is in legacy mode where this feature is builtin, but I am guessing that they dont use MLKIT. I still plan to use this package so I will do the rect intersection like you said, thanks!
