### ISSUE TITLE
⚠︎ Maintainer wanted. Delay with merging PR's for the last and coming months. 

### ISSUE THREAD

**Issue by juliansteenbakker** [juliansteenbakker/mobile_scanner#652]
The past few months i've been struggling to find some free time to maintain my packages, mainly due to work related deadlines and vacation. Long story short, this will continue to be at least the coming two or three months. This is why it would be great if someone whats to help me maintain this package, and also has the knowledge to do so.

**Comment by juliansteenbakker** [comment]
Thank you @teolemon for helping me out here!

**Comment by navaronbracke** [comment]
What if, we move the package over to the community packages repo? https://github.com/fluttercommunity
Then more people can chime in on getting PR's landed. That does require transferring ownership, though, which might not be want you want to do.

I myself have some experience with maintaining packages, but I also lack the time (work related + other open source contributions also chew away at the time I do have)

**Comment by SputNikPlop** [comment]
I use this package a lot, I would be happy to help for some of the iOS stuff.

**Comment by teolemon** [comment]
@juliansteenbakker

**Comment by juliansteenbakker** [comment]
Thanks for the options! @teolemon @SputNikPlop i'm on vacation right now and will be back the 26th of june. After that i'll take some action on this

**Comment by kyeshmz** [comment]
@juliansteenbakker Would love to help out if this is also migrated to the community repo!
