### ISSUE TITLE
Various linter reported issues

### ISSUE THREAD

**Issue by teolemon** [juliansteenbakker/mobile_scanner#653]
### What
- [ ] info • Library directives without comments or annotations should be avoided • lib/mobile_scanner.dart:1:1 • unnecessary_library_directive
- [ ]    info • Library directives without comments or annotations should be avoided • lib/mobile_scanner_web.dart:1:1 • unnecessary_library_directive
- [ ]    info • Sort combinator names alphabetically • lib/src/web/utils.dart:3:18 • combinators_ordering
- [ ]    info • 'setMockMethodCallHandler' is deprecated and shouldn't be used. Use tester.binding.defaultBinaryMessenger.setMockMethodCallHandler or TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger.setMockMethodCallHandler instead. Pass the channel as the first argument. This feature was deprecated after v3.9.0-19.0.pre • test/mobile_scanner_test.dart:10:[13](https://github.com/juliansteenbakker/mobile_scanner/actions/runs/5115857679/jobs/9197485010?pr=650#step:7:14) • deprecated_member_use
- [ ]    info • 'setMockMethodCallHandler' is deprecated and shouldn't be used. Use tester.binding.defaultBinaryMessenger.setMockMethodCallHandler or TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger.setMockMethodCallHandler instead. Pass the channel as the first argument. This feature was deprecated after v3.9.0-19.0.pre • test/mobile_scanner_test.dart:16:13 • deprecated_member_use

**Comment by navaronbracke** [comment]
@teolemon This was fixed in #655 (I addressed the analysis discrepancy there). Are there any other rules that CI applies to linting besides the ones that are currently in the `analysis_options.yml` ? If not then this is no longer an issue.

**Comment by navaronbracke** [comment]
I no longer get any lint warnings in the repo. Closing as completed.
