### ISSUE TITLE
[Regression] Different initial zoom scale between iOS and Android

### ISSUE THREAD

**Issue by burekas7** [juliansteenbakker/mobile_scanner#659]
Hi,

Since upgrading the package to 3.1.1 I have a difference with the initial zoom scale between iOS and Android.

EDIT:
It seems that it is a problem with the screen physical size different and not a platform issue.

Is it a known issue?

For example:
The left device is an iOS device, the right is an Android
https://i.postimg.cc/tTn2jmpk/IMG-6468.jpg

**Comment by juliansteenbakker** [comment]
This should be fixed right now.

**Comment by burekas7** [comment]
> This should be fixed right now.

Should I need to set anything or it should be fixed by default?
