### ISSUE TITLE
API for Permission Handling

### ISSUE THREAD

**Issue by p0wl90** [juliansteenbakker/mobile_scanner#67]
Hey!
I hope that I'm not missing something but as far as I see it, there is currently no possibility to react to permission-issues. This would be good for the following use case: 

1. I have a full-screen QR scanner view
2. The user opens it for the first time and does **not** grant the app permission to use the camera 
3. In that case, I want to close the view and display a dialog that tells users that they cannot use that view without granting the camera permission.

Thanks!

**Comment by p0wl90** [comment]
You're right, I was used to this because my previous package supported this but actually, it is out of scope for a QR scanner. Still, maybe it makes sense to have some indicator or way to react if the permissin is missing.

**Comment by janwol** [comment]
@tim-teacher throwing the exception, if something went wrong, would be very helpful:
https://github.com/juliansteenbakker/mobile_scanner/blob/bbf4d5855d6e75295c44826a811cba72ea9bab7c/lib/src/mobile_scanner_controller.dart#L167-L175

**Comment by adar2378** [comment]
Yes, this is a must needed thing for the library

**Comment by juliansteenbakker** [comment]
This is all present in the latest version 3.0.0-beta.4
