### ISSUE TITLE
Can you add one animation like the one on the description.

### ISSUE THREAD

**Issue by freidev** [juliansteenbakker/mobile_scanner#673]
First, Thanks for your time, this project is amazing. I found this in pub.dev : 
https://pub.dev/packages/flutter_camera_qrcode_scanner this package have one animation so cool

![image](https://github.com/juliansteenbakker/mobile_scanner/assets/54672897/6a6c80fa-31c0-4bfb-872e-82cdb1f4d3a9)

Can you help me to get this result?

**Comment by navaronbracke** [comment]
For help with user interfaces, I do recommend asking a question on Stackoverflow, as this Github repository is for issues with `mobile_scanner` itself.
