### ISSUE TITLE
[Web] Null error with MobileScannerController when permission is not granted to app

### ISSUE THREAD

**Issue by Foldblade** [juliansteenbakker/mobile_scanner#69]
<small>English is not my native language; please excuse typing errors.</small>

Thank you for your package! I struggled for days for the QR code scanning of Flutter web with jsQR, until I found your package. But during my test, an error occurred:

Console: `Expected a value of type 'MobileScannerArguments', but got one of type 'Null'`

This occurs when open the a page with `MobileScanner` using `MobileScannerController`, before granting the permission.

![ShareX_DxYiOmCZVU](https://user-images.githubusercontent.com/25426917/158579381-c9c1ba9f-41b4-46d0-9464-4f36d9e20798.png)

My code:

```dart
class _BarcodeScannerViewState extends State<BarcodeScannerView> {
  final MobileScannerController _controller =
      MobileScannerController(facing: CameraFacing.back, torchEnabled: false);

  @override
    Widget build(BuildContext context) {
    return OrientationBuilder(
      builder: (context, orientation) {
        return Scaffold(
          appBar: AppBar(
            title: Text(widget.title),
          ),
          body: MobileScanner(
              controller: _controller,
              onDetect: (barcode, args) {
                final String code = barcode.rawValue!;
                debugPrint('Barcode found! $code');
                if (widget.popBack) {
                  Navigator.pop(context, code);
                } else {
                  searchNavigator(context, code,
                      destination: widget.destination, searchType: "CRID");
                }
              }),
          floatingActionButton: FloatingActionButton(
            heroTag: null,
            child: ValueListenableBuilder(
              valueListenable: _controller.torchState,
              builder: (context, state, child) {
                switch (state as TorchState) {
                  case TorchState.off:
                    return const Icon(Icons.flash_on);
                  case TorchState.on:
                    return const Icon(Icons.flash_off);
                }
              },
            ),
            onPressed: () {
              _controller.toggleTorch();
            },
          ),
        );
      },
    );
  }
}
```

May be related to #67 , hoping for a API for Permission Handling, or make sure MobileScannerController won't be null when permission is not granted to app?

Because `ValueListenableBuilder` is used to decide the flash button's icon, `valueListenable` requires `ValueListenable<MobileScannerArguments?>`, so it's impossible to make `_controller` nullable, setting `valueListenable: _controller!.args,` will leads to `Expected a value of type 'MobileScannerArguments', but got one of type 'Null'`.

Thank you!

**Comment by juliansteenbakker** [comment]
Please check with latest version v3.0.0-beta.4
