### ISSUE TITLE
Unable to build to iOS device

### ISSUE THREAD

**Issue by thiagorbernardo** [juliansteenbakker/mobile_scanner#690]
I'm getting the error below when building to an iOS device.
`Null objc class data for '_OBJC_METACLASS_$_MLKBarcode' in '/Users/thiagorbernardo/Documents/pantry_trackr_project/pantry_trackr_app/ios/Pods/MLKitBarcodeScanning/Frameworks/MLKitBarcodeScanning.framework/MLKitBarcodeScanning'` 

I do not get this error when building to the iOS simulator. The error is on the Xcode build. I already clean the cache, clean the pod, deintegrate etc...
I have tried with iOS 17 and 16, I'm currently using the Xcode Version 15.0 beta 3 (15A5195k).

### Flutter doctor
[✓] Flutter (Channel stable, 3.10.6, on macOS 14.0 23A5286i darwin-arm64, locale en-BR)
    • Flutter version 3.10.6 on channel stable at /Users/thiagorbernardo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 hours ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/thiagorbernardo/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 15A5195k
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • Thiago’s iPhone (mobile) • 00008120-00091568363B401E • ios            • iOS 17.0 21A5277j
    • macOS (desktop)          • macos                     • darwin-arm64   • macOS 14.0 23A5286i darwin-arm64
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by navaronbracke** [comment]
I think that the MLBarcode scanning library will have to be updated to work with XCode 15. If it already has such a version, then we should upgrade to that version in the plugin.

**Comment by tayormi** [comment]
A workaround for now would be to use the classic linker by including `-ld64` in the 'Other Linker Flags' build settings in Xcode.

**Comment by thiagorbernardo** [comment]
> A workaround for now would be to use the classic linker by including `-ld64` in the 'Other Linker Flags' build settings in Xcode.

Thank you so much, it worked, now I can test at least!!!!

**Comment by mrRedSun** [comment]
Probably related to this, but in our case the error is different and we use Xcode 14.3.1. Only happens on Simulator and only for ARM Macbooks (M1, M2, etc.)

Removing the mobile_scanner fixes the issue. I suppose either GoogleMLKit/BarcodeScanning or our internal configuration is to blame. If I could be of any help let me know.

```
Error (Xcode): Framework not found Pods_Runner

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.

```

<details><summary>Flutter doctor</summary>
<p>

[✓] Flutter (Channel stable, 3.3.10, on macOS 13.4.1 22F770820d darwin-arm, locale en-UA)
    • Flutter version 3.3.10 on channel stable at /Users/user/fvm/versions/3.3.10
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (7 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Zulu11.66+15-CA (build 11.0.20+8-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (4 available)
    • iPad (mobile)  • 00008027-001468221E85002E            • ios            • iOS 16.5.1 20F75
    • iPhone SE (3rd generation) (mobile) • B013C97F-83BB-4031-B614-ED92A7C84B9A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 115.0.5790.98

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

</p>
</details>

**Comment by magic3584** [comment]
> A workaround for now would be to use the classic linker by including `-ld64` in the 'Other Linker Flags' build settings in Xcode.

ld: library not found for -ld64

Plz tell me how to solve this

**Comment by toddtarbox** [comment]
> Probably related to this, but in our case the error is different and we use Xcode 14.3.1. Only happens on Simulator and only for ARM Macbooks (M1, M2, etc.)
> 
> Removing the mobile_scanner fixes the issue. I suppose either GoogleMLKit/BarcodeScanning or our internal configuration is to blame. If I could be of any help let me know.
> 
> ```
> Error (Xcode): Framework not found Pods_Runner
> 
> Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
> 
> Could not build the application for the simulator.
> ```
> 
> Flutter doctor

Any updates on this? I'm currently blocked because I can't build for simulator. Again, removing mobile_scanner completely resolves this issue.

**Comment by mrRedSun** [comment]
Xcode 15 when using default excluded architecture settings in Xcode works fine on the simulator

**Comment by navaronbracke** [comment]
I verified this on XCode 15.0 (15A240d), using an iOS 17 Simulator, and the example app builds fine on the Simulator.

There isn't much we can do otherwise.

**Comment by parthpatel-simbiotik** [comment]
I am also facing the same issue in v5.1.1. I am using XCode 15.4. Using MacBook Pro (M1 Pro)
Running on my iPhone 14 Pro Device

Please help how to fix this.

**Comment by Igor-Pavlyshyn** [comment]
> I am also facing the same issue in v5.1.1. I am using XCode 15.4. Using MacBook Pro (M1 Pro) Running on my iPhone 14 Pro Device
> 
> Please help how to fix this.

did you solved that?

**Comment by quetool** [comment]
> Probably related to this, but in our case the error is different and we use Xcode 14.3.1. Only happens on Simulator and only for ARM Macbooks (M1, M2, etc.)
> 
> Removing the mobile_scanner fixes the issue. I suppose either GoogleMLKit/BarcodeScanning or our internal configuration is to blame. If I could be of any help let me know.
> 
> ```
> Error (Xcode): Framework not found Pods_Runner
> 
> Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
> 
> Could not build the application for the simulator.
> ```
> 
> Flutter doctor

This is still an issue in Xcode 15.4 (15F31d)
