### ISSUE TITLE
Second scan

### ISSUE THREAD

**Issue by pom11** [juliansteenbakker/mobile_scanner#694]
When navigating from another screen the scanner is not working. Tried everything i found from issues but without luck... init another controller on initState, reassemble etc. Having this bug only on Android!!!!

**Comment by burekas7** [comment]
I have something similar, it happens only in Android, on iOS it's ok.

**Comment by i-show** [comment]
+1

**Comment by famasf1** [comment]
avoid detectionSpeed: DetectionSpeed.noDuplicates for the time being. It doesn't work well in many cases. For now. just use the following.

`detectionSpeed: DetectionSpeed.normal,
    detectionTimeoutMs: 250,`

**Comment by pom11** [comment]
worked. thx
