### ISSUE TITLE
[Bug] 'detectionTimeoutMs' doesn't work in iOS

### ISSUE THREAD

**Issue by burekas7** [juliansteenbakker/mobile_scanner#700]
Hi,

I define the controller like that:
`MobileScannerController(detectionSpeed: DetectionSpeed.normal, detectionTimeoutMs: 10000);`

In Android it's working, but in iOS it ignores this timeout value.

Update:
By the way, it seems that in iOS it totally ignores the `detectionSpeed` property, because it ignores also the `DetectionSpeed.noDuplicates` 

Version 3.3.0
@juliansteenbakker

**Comment by imaaronath** [comment]
Yeah me too, i have same problem with you

**Comment by navaronbracke** [comment]
The detection timeout for iOS was fixed in version 3.5.0.
