### ISSUE TITLE
Scan on Flutter Web (iOS, macOS only) not working

### ISSUE THREAD

**Issue by linussorg** [juliansteenbakker/mobile_scanner#705]
Error message: 
`mobile_scanner: MobileScannerException: code permissionDenied, message: NoSuchMethodError: method not found: 'BrowserMultiFormatReader' on null`

This happens using mobile scanner version 3.3.0 (newest at this point in time)

This error does not occur:
- on Android native
- on Android web

This error occurs:
- on iOS web
- on macOS web

This happens although camera permissions were granted to the flutter web app

Any idea?

**Comment by rahulrmishra** [comment]
Same with me

**Comment by shahjash1212** [comment]
When we will resolve this ?? stuck in the same issue.

**Comment by bhaveshrs** [comment]
any update on this issue?

**Comment by linussorg** [comment]
This seems to be an issue after upgrading the flutter version:
For now, I was able to resolve it with this added to the head in my index.html:
`<script src="https://unpkg.com/@zxing/library@0.20.0"></script>
  <script type="text/javascript" src="https://unpkg.com/@zxing/library@0.20.0/umd/index.min.js"></script>`
