### ISSUE TITLE
NPE - Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest android.hardware.camera2.impl.CameraDeviceImpl$CaptureCallbackHolder.getRequest(int)' on a null object reference

### ISSUE THREAD

**Issue by teolemon** [juliansteenbakker/mobile_scanner#719]
From the @openfoodfacts Sentry system: 
NPE - Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest android.hardware.camera2.impl.CameraDeviceImpl$CaptureCallbackHolder.getRequest(int)' on a null object reference

Sentry Issue: [SMOOTHIE-2EC](https://openfoodfacts.sentry.io/issues/4275004795/?referrer=github_integration)

```
NullPointerException: Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest android.hardware.camera2.impl.CameraDeviceImpl$CaptureCallbackHolder.getRequest(int)' on a null object reference
    at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(CameraDeviceImpl.java:2070)
    at android.hardware.camera2.legacy.CameraDeviceUserShim$CameraCallbackThread$CallbackHandler.handleMessage(CameraDeviceUserShim.java:325)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by navaronbracke** [comment]
@teolemon I'll take a look at it.

**Comment by navaronbracke** [comment]
I think I know what is causing this. We are doing several `camera!!` forced null assertions, which could be the problem.

**Comment by rohansohonee1** [comment]
@navaronbracke Received a crash which used mobile_scanner version 6.0.2
```console
          Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest android.hardware.camera2.impl.CameraDeviceImpl$CaptureCallbackHolder.getRequest(int)' on a null object reference
       at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(CameraDeviceImpl.java:1919)
       at android.hardware.camera2.legacy.CameraDeviceUserShim$CameraCallbackThread$CallbackHandler.handleMessage(CameraDeviceUserShim.java:323)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
        
```

```logs
Device
Brand:Motorola
Model:Moto G (5) Plus
Orientation:Portrait
RAM free: 459.34 MB
Disk free: 18.11 GB
Operating System
Version:Android 8.1.0
Orientation:Portrait
Rooted: No
Crash
Date:Mar 12, 2025, 1:16:25 AM
```

**Comment by navaronbracke** [comment]
Hi @rohansohonee1 I had a look at the issue and the following thread indicates that this is possibly an issue with our SurfaceProducer implementation: https://issuetracker.google.com/issues/236055506

In version 6.0.6 we were not using the `Consumer` argument of the `provideSurface()` method (the third argument is null / not provided): https://github.com/juliansteenbakker/mobile_scanner/blob/master/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt#L321

However, with the migration to Impeller for Android, we revisited this function and had to provide the `Consumer` argument:
https://github.com/juliansteenbakker/mobile_scanner/blob/develop/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt#L254-L276

Notably the Consumer calls `release()` on the Surface when needed.

Can you retest this with mobile_scanner 7.0.0-beta.8
