### ISSUE TITLE
Unresolved reference Error on Android Build on 3.4.1

### ISSUE THREAD

**Issue by AndreLuizNogueira** [juliansteenbakker/mobile_scanner#722]
After Upgrading to 3.4.1, at android build I am getting multiple Unresolved reference errors.

.../MobileScanner.kt:30:40 Unresolved reference: MobileScannerCallback
.../MobileScanner.kt:31:45 Unresolved reference: MobileScannerErrorCallback
...MobileScanner.kt:83:52 Unresolved reference: data
.../MobileScanner.kt:86:48 Unresolved reference: data
.../MobileScanner.kt:179:29 Unresolved reference: TorchStateCallback
.../MobileScanner.kt:180:33 Unresolved reference: ZoomScaleStateCallback
.../MobileScanner.kt:181:39 Unresolved reference: MobileScannerStartedCallback
.../MobileScanner.kt:307:52 Unresolved reference: AnalyzerCallback
.../MobileScanner.kt:312:68 Unresolved reference: data

Execution failed for task ':mobile_scanner:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

**Comment by AndreLuizNogueira** [comment]
Sorry, please disregard. just cleaning the project solved the problem

**Comment by jenpingus** [comment]
I am still getting the error.. after install update the 3.4.1 version

**Comment by timouano** [comment]
I'm still getting an error
```
* What went wrong:
Execution failed for task ':mobile_scanner:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
```

**Comment by AndreLuizNogueira** [comment]
> I'm still getting an error
> 
> ```
> * What went wrong:
> Execution failed for task ':mobile_scanner:compileReleaseKotlin'.
> > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
> ```

Did you run "flutter clean"? That's what solved it for me.
