### ISSUE TITLE
[Proposal] Have `analyzeImage` return the detected barcode

### ISSUE THREAD

**Issue by fosteranese** [juliansteenbakker/mobile_scanner#728]
_This issue is a feature request to have the analyzeImage method return the barcode, rather than a boolean_

Sorry, if this is a dump question. But I can analyze a qrcode file image to determine if contains qrcode or not but I can't seem to extract the code or text embedded in the qrcode file image analyzed

**Comment by g1tPush** [comment]
You can use your controller for this purpose.
cameraController.barcodes.listen((BarcodeCapture capture) {
  // extraction is described in Usage section of the plugin on pub dev 
});

Remember to dispose the controller during widget dispose()

**Comment by fosteranese** [comment]
Thank you very much. This information has been very help to me. Thank you once again.

**Comment by navaronbracke** [comment]
@fosteranese Does https://github.com/juliansteenbakker/mobile_scanner/issues/728#issuecomment-1685399907 help you with your issue? If it does, then we can close this issue.

**Comment by navaronbracke** [comment]
@fosteranese I think this is a feature request to change the signature of `Future<bool> analyzeImage(String filePath)` into `Future<BarcodeCapture?> analyzeImage(String filePath)`?

**Comment by fosteranese** [comment]
> @fosteranese Does [#728 (comment)](https://github.com/juliansteenbakker/mobile_scanner/issues/728#issuecomment-1685399907) help you with your issue? If it does, then we can close this issue.

Yeap, it did

**Comment by ozkayas** [comment]
@navaronbracke 

Is it possible to supply a minimal sample code for this operation?
I still can not understand what to do after picking an image file.

```   
    final mobileScannerCtr = MobileScannerController();
    final XFile? file =
    await ImagePicker().pickImage(source: ImageSource.gallery);
    
    // Next Step?
      mobileScannerCtr.barcodes.listen((event) { });```

**Comment by ozkayas** [comment]
> You can use your controller for this purpose. cameraController.barcodes.listen((BarcodeCapture capture) { // extraction is described in Usage section of the plugin on pub dev });
> 
> Remember to dispose the controller during widget dispose()

I can not see any sample about listen method on Usage, and package examples.
Was this an older feature? Not supported now?

**Comment by navaronbracke** [comment]
Pass the path of the XFile to `analyzeImage` ?

```
final XFile file = ...

mobileScannerCtr.barcodes.listen((event) { });

await mobileScannerCtr.analyzeImage(file.path!);
```

**Comment by dferrarigrowtech** [comment]
Here is another implementation of the workaround:
```dart
import 'dart:async';

BarcodeCapture analyzeQrImage(String qrPath) async {
  final Completer<BarcodeCapture> completer = Completer();
  final controller = MobileScannerController();
  controller.barcodes.listen((BarcodeCapture capture) {
    completer.complete(capture);
  }, onError: (e) {
    completer.completeError(e);
  });
  await controller.analyzeImage(qrPath);
  return completer.future;
}
```
