### ISSUE TITLE
Incorrect camera orientation after phone orientation change.

### ISSUE THREAD

**Issue by peengle** [juliansteenbakker/mobile_scanner#731]
How can the issue of incorrect camera orientation be resolved when the phone is rotated from a vertical to a horizontal position? 
Currently the camera image is rotated by 90 degrees in such a case.

I've checked deprecated project https://pub.dev/packages/qr_code_scanner and there this problem doesn't exist.

**Comment by frankvollebregt** [comment]
It's (unfortunately) a known limitation/issue:
https://github.com/juliansteenbakker/mobile_scanner/discussions/17

**Comment by peengle** [comment]
Thanks for pointing out the duplicate. So I'll follow #17
