### ISSUE TITLE
Error: PlatformException(Unimplemented, null, The mobile_scanner plugin for web doesn't implement the method 'analyzeImage', null)

### ISSUE THREAD

**Issue by gapkukb** [juliansteenbakker/mobile_scanner#733]
Show this error message when used on web as according the demo locate at "mobile_scanner/example/lib\n/barcode_scanner_controller.dart"

**Comment by RelicOfTesla** [comment]
Why not work Web. Zxing supports binary decoding... We can convert it.
```js
const reader = new MultiFormatReader();
const luminanceSource = new RGBLuminanceSource(imgByteArray, imgWidth, imgHeight);
const binaryBitmap = new BinaryBitmap(new HybridBinarizer(luminanceSource));
reader.decode(binaryBitmap, hints);
```

**Comment by navaronbracke** [comment]
I don't think that either ZXing or JSQr support analyzing an image. They are only mean to detect barcodes/ QR codes in an image, which is a specific kind of image analysis.

Closing as not planned.
