### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by plkgq** [juliansteenbakker/mobile_scanner#742]
I got this error when trying to run my iOS project:
../../../../.pub-cache/hosted/pub.dev/mobile_scanner-3.4.1/lib/src/web/base.dart:1:8: Error: Dart library 'dart:html' is not available on this platform.

Flutter 3.13.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision efbf63d9c6 (2 weeks ago) • 2023-08-15 21:05:06 -0500
Engine • revision 1ac611c64e
Tools • Dart 3.1.0 • DevTools 2.25.0

**Comment by MagnumAlex** [comment]
same here what was the resolution ? building for iOS same issue!

**Comment by MagnumAlex** [comment]
No devices found yet. Checking for wireless devices...
Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: ******
Running pod install...                                              4.6s
Running Xcode build...                                                  
Xcode build done.                                           38.8s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): ../../../../../.pub-cache/hosted/pub.dev/mobile_scanner-3.4.1/lib/src/web/base.dart:1:8: Error: Dart library 'dart:html' is
not available on this platform.

Error launching application on

----

but this is not my code doesn't seem like I should change it!

**Comment by ForterLi** [comment]
Error: Dart library 'dart:html' is not available on this platform
