### ISSUE TITLE
iOS can not read a barcode while Android can

### ISSUE THREAD

**Issue by oorfalimak** [juliansteenbakker/mobile_scanner#743]
I use different kind of barcodes in my app, but for one of them I have this issue:
Android can read barcode, but iOS devices can not read (When barcode is bold).

This is the link of my barcode image (left is working on both platforms, right one is only working on Android): 
https://github.com/juliansteenbakker/mobile_scanner/assets/81231302/c5a05488-3fae-4281-a3ed-74bb450a6b06

Flutter doctor results:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.1 22C65 darwin-arm64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (2 available)
[✓] Network resources

**Comment by gigafunk** [comment]
I just discovered this behavior and came to see if there was any info.  I was wondering what the difference was, thanks for the pics. It the Bold style doing it.

**Comment by gigafunk** [comment]
try with version 3.5.2

**Comment by oorfalimak** [comment]
Problem is solved with version 3.5.2, thanks.
