### ISSUE TITLE
Scanner returns different values from the same barcode

### ISSUE THREAD

**Issue by AliEasy** [juliansteenbakker/mobile_scanner#749]
When scanning barcodes, each time it returns a different value.

Plugin mobile_scanner 3.4.1 on flutter_windows_3.10.2-stable

Code:
```
             MobileScanner(
                fit: BoxFit.fitWidth,
                controller: MobileScannerController(
                  detectionSpeed: DetectionSpeed.noDuplicates,
                  torchEnabled: false,
                ),
                onDetect: (capture) async {
                  if (!_inProcess) {
                    _inProcess = true;
                    final List<Barcode> barcodes = capture.barcodes;
                    if (barcodes.isNotEmpty) {
                      var barcode = barcodes[0];
                      String serial = barcode.rawValue ?? '';
                      print(serial);
                    }
                    _inProcess = false;
                  }
                },
              )
```

Barcode:
![code](https://github.com/juliansteenbakker/mobile_scanner/assets/45623453/2545074a-fe20-48e0-bad6-22cc418b0cd0)

results:
987654321098
981654327098

**Comment by gigafunk** [comment]
reading off paper or a screen? I notice sometimes it will return some wrong numbers when reading off a digital screen of some sort, usually while its still kind of farther away. I was thinking it was just noise from the movement of the code into a "good spot".  I found it to be far more accurate off of real printed barcode.

**Comment by AliEasy** [comment]
It's happening on both paper and screen

I get couple of different values by scanning  below barcode on a real product:

![1000006610.jpg](https://user-images.githubusercontent.com/45623453/266997768-ecefb6e5-74ad-41f4-8152-230fd58daef2.jpg)

My device is Galaxy A51 but also tested on another android device and still happening

**Comment by EArminjon** [comment]
Maybe this is related to the image quality given to ML Kit. This package seems to give to ml Kit an image of 640/480 as default resolution...

**Comment by plkgq** [comment]
Try setting sessionPreset to AVCaptureSession.Preset.medium and it will be recognized
