### ISSUE TITLE
'dev.steenbakker.mobile_scanner/scanner/event' channel sent a message from native to Flutter on a non-platform thread.

### ISSUE THREAD

**Issue by memishood** [juliansteenbakker/mobile_scanner#751]
Whenever I start the app in debug mode for iOS, I see this warning at console:
```shell
[VERBOSE-2:shell.cc(1004)] The 'dev.steenbakker.mobile_scanner/scanner/event' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
```

<details><summary>Details</summary>

```
Flutter version: 3.13.3
Dart Version: 3.1.1 (stable)
Device: iPhone 14 Pro Max (Not simulator)
```

pubspec.yaml:
```yaml
mobile_scanner: ^3.4.1
```

implementation:
```dart
import 'package:auto_route/annotations.dart';
import 'package:flutter/material.dart';
import 'package:menuu/common/widgets/spinner_widget.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

@RoutePage()
class ScanPage extends StatefulWidget {
  const ScanPage({super.key});

  @override
  State<ScanPage> createState() => _ScanPageState();
}

class _ScanPageState extends State<ScanPage> {
  final _cameraController = MobileScannerController();

  @override
  void dispose() {
    _cameraController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: MobileScanner(
        controller: _cameraController,
        placeholderBuilder: (context, child) => const Center(
          child: Spinner(),
        ),
        onDetect: (capture) {
          final url = capture.barcodes.first.url?.url;
          // some stuff..
        },
      ),
    );
  }
}
```
</details>

**Comment by ErichPetersen** [comment]
Did you find a solution?

**Comment by memishood** [comment]
@ErichPetersen Unfortunately not.

**Comment by michaelhitzker** [comment]
Fixed it by using version 3.3.0

**Comment by loic-hamdi** [comment]
> Fixed it by using version 3.3.0

Tried this, also tried to downgrade to 3.2.0 or even using last commit `128ce4b` and it still gives this message + crash the app in `release`.

Did you guys find any solution?

@juliansteenbakker Please need urgent advice

**Comment by kit2512** [comment]
> > Fixed it by using version 3.3.0
> 
> Edit:
> 
> Using last commit `128ce4b` seems to work
> 
> ```
>   mobile_scanner: 
>     git:
>       url: https://github.com/juliansteenbakker/mobile_scanner.git
>       ref: 128ce4b
> ```

it doesn't work for me

**Comment by andreask99** [comment]
I only could fix it by downgrading Flutter to 3.10.7

It would be greatly appreciated if this is fixed properly so the most current stable Flutter version can be used.

**Comment by navaronbracke** [comment]
This has nothing to do with the used Flutter version. It is a bug with the plugin not executing the method channel result invocations on the main thread.

**Comment by andreask99** [comment]
> This has nothing to do with the used Flutter version. It is a bug with the plugin not executing the method channel result invocations on the main thread.

Thanks for the response... I read somewhere that since Flutter 3.13 the framework has gotten stricter regarding method channel invocations. Also downgrading seems to have removed the error for now. 

But happy for any better interim workarounds while the root bug is not yet solved.

**Comment by andreask99** [comment]
@navaronbracke   Does version 3.5.0 fix this issue?

**Comment by andreask99** [comment]
Thanks again for the quick response. Users had reported app crashes while scanning, which was indeed a blocker. As mentioned the downgrading of Flutter seems to avoid such crashes but I am not very confident on that workaround. Needless to say that downgrading isn't a great strategy in itself.

Hence yes I would greatly appreciate if you are able to prioritize this.

**Comment by navaronbracke** [comment]
@andreask99 I have a WIP patch that fixes this for iOS and Android.

The only thing missing is MacOS, but I have to resolve a build error first. 
After that it should be smooth sailing to get MacOS fixed as well.

**Comment by andreask99** [comment]
@navaronbracke That was now lightning fast - thank you so much!

**Comment by navaronbracke** [comment]
Version 3.5.1 is now available with this fix.
