### ISSUE TITLE
Feature Request: Add Functionality to Change Camera Quality

### ISSUE THREAD

**Issue by freidev** [juliansteenbakker/mobile_scanner#752]
Hello,

First of all, thank you for creating this useful package. It has been very helpful for my project.

I have a feature request that I believe could make the package even better. Currently, it seems like there is no option to change the camera quality or resolution when using mobile_scanner.

This feature would be extremely beneficial for applications that require high-quality scanning or image capture. Providing an API to adjust the camera resolution could improve the user experience and the versatility of your package.

Here's how I envision the API might look:

MobileScannerController( cameraResolution: ResolutionPreset.high);
Or maybe as a method to change it dynamically:
mobileScannerController.setCameraResolution(ResolutionPreset.high);

I understand that maintaining an open-source project is a lot of work, and I appreciate the effort you've put into this package. I would be thrilled to see this feature implemented and am looking forward to your thoughts on this request.

Thank you for considering this feature!

Best regards,
Freilyn Bernabe

**Comment by EArminjon** [comment]
Currently this package have trouble to scan the following barcode. Sadly this barcode is wide and 'easy'.
![Capture d’écran 2023-09-26 à 09 35 07](https://github.com/juliansteenbakker/mobile_scanner/assets/37028599/02ca0ac4-e361-4802-ae43-df63b864c607)

I could understand that the following barcodes can sadly fail but we make fix that. To make it possible we need to have a way to improve the scan image quality @juliansteenbakker  :/ !
![Capture d’écran 2023-09-26 à 09 36 15](https://github.com/juliansteenbakker/mobile_scanner/assets/37028599/81548b78-2345-4a32-8faf-03db0dfc692b)
