### ISSUE TITLE
Issue with MobileScannerController not Triggering onDetect after Navigation and Pop

### ISSUE THREAD

**Issue by Hemant-sha** [juliansteenbakker/mobile_scanner#756]
I am facing an issue with the MobileScanner widget where the onDetect callback is not being triggered after navigating away from the ScanScreen, initiating another instance of MobileScanner, and then navigating back to the initial ScanScreen. Initially, when the ScanScreen is loaded, the MobileScanner works correctly and the onDetect function is hit as expected. However, after completing the flow on a new page, where another instance of MobileScanner is crucial for scanning, and coming back to the first instance of the scanning feature, onDetect does not get triggered anymore.

Here is a simplified version of my ScanScreen widget which uses MobileScanner:

dart

class ScanScreen extends StatefulWidget {
  // ... constructor and other code
}

class _ScanScreenState extends State<ScanScreen> {

  final MobileScannerController cameraController = MobileScannerController(
    detectionTimeoutMs: 2000,
  );

  // ... other code

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // ... AppBar and other code
      body: MobileScanner(
        controller: cameraController,
        onDetect: (capture) async {
          // Handling barcode detection
        },
      ),
    );
  }
}
Steps to Reproduce:

Navigate to ScanScreen and scan a package.
Navigate to a new page, which also involves initiating another MobileScanner instance, and handle the scanned package.
Return to the initial ScanScreen by popping the second screen.
Attempt to scan another package.
Expected Behavior:
Upon returning to the initial ScanScreen, I expect the MobileScanner to work as it initially does and the onDetect function to be triggered when a barcode is detected.

Actual Behavior:
The onDetect function is not triggered when coming back to the initial ScanScreen after navigating to a new page and popping the second MobileScanner instance.

Attempted Solutions:

I have verified that cameraController.start() is being called when returning to the ScanScreen.
I have manually stopped and restarted the cameraController using cameraController.stop() and cameraController.start() during navigation transitions.
I have tried to reinitialize the MobileScannerController by creating a new instance and calling setState.
I have explored using different navigation approaches such as Navigator.push and Navigator.pop.
Environment:

Flutter version: (Your Flutter version)
mobile_scanner package version: (The version of the package you are using)
(Any other relevant environment details)
This behavior seems to clean up everything and hinders the functionality of the initial MobileScanner instance. I would appreciate any guidance on resolving this issue or information on whether this is a known limitation of the MobileScanner widget. Thank you for your time and support!

**Comment by Hemant-sha** [comment]
Doesn't work for me, I am opening another scanner screen while the first one is in the background. I implemented your solution the new screen comes up with an exclamation in the middle, when I pop that screen I suspect an implicit dispose is run which makes the first scan screen appear blank. thanks for helping tho.

**Comment by Hemant-sha** [comment]
> This solution worked when there was an exclamation in the middle. <img alt="Screenshot 2023-09-27 at 14 05 20 (2)" width="516" src="https://user-images.githubusercontent.com/112816113/270971861-ffceb77a-8def-48d7-b9c3-8fb8764dfdb3.png">

**Comment by Hemant-sha** [comment]
The major problem here is with popping one scan screen and not being able to use an already existing instance in the stack.

**Comment by Rjongenburger** [comment]
can you use code blocks in your comments next time.... jeez

**Comment by navaronbracke** [comment]
When the Widget gets unmounted due to navigating away, the `onDetect` function won't be called anymore, because we clean up the widget (and its Texture).

We _could_ move the onDetect function to the controller (having it on the widget is a bit weird).

What we will not do is having the controller still forward events when it is being cleaned up.

Instead, prefer to use a mechanism like `PopScope` to prevent navigating away if you still have pending barcodes that are being processed.

The plugin's responsibilities are mainly to manage the lifetime of the resources (camera/texture/scanner), not anything relating to navigation.

**Comment by Dr-Usman** [comment]
Facing same issue. Camera controller dispose method called by itself when pop from scanner page. That's why couldn't able to switch camera and toggle flash light.

**Comment by navaronbracke** [comment]
As `onDetect` is no longer provided in the latest beta release, I'm going to close this issue.

For future readers: listen to the barcode stream instead, since you have control over the lifecycle of the MobileScannerController now.
