### ISSUE TITLE
 Flutter 3.13.6: Incompatible classes were found in dependencies. 

### ISSUE THREAD

**Issue by 1Dimitri** [juliansteenbakker/mobile_scanner#763]
When building a simple example with latest Flutter (Channel stable, 3.13.6), 
I receive first an message saying to update the minsdkVersion to 21 to build on Android
Once this modification is done, the following error appears

`Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors`

Could somebody tell me how to work around this if already encountered?

**Comment by selawik** [comment]
Same. Any updage?

**Comment by Rjongenburger** [comment]
can you try updating kotlin version?
`ext.kotlin_version = '1.9.10'`

**Comment by WiRight** [comment]
same here

after update kotlin version to `1.9.10` app is not launching (activity closing after starting)

**Comment by WiRight** [comment]
Sorry, in may case i have wrong android main package name...

update kotlin version to `1.9.10` help me!

**Comment by navaronbracke** [comment]
We downgraded the Kotlin version in the plugin from 1.9.0 to 1.7.22

Does this help for this issue? (fix has not been published yet, but you could test with the master branch of `mobile_scanner` to verify, using https://dart.dev/tools/pub/dependencies#git-packages)

**Comment by JackWH** [comment]
@navaronbracke Thanks for the update comment... This issue is preventing our app from building, but we're using FlutterFlow, so restricted to Kotlin 1.7.10.

I see you downgraded to 1.7.22 — I'm not too familiar with Kotlin/Gradle but am I right in assuming semver applies, so it will still build? (Hopefully! 🤞) Any advice greatly appreciated — thanks.

**Comment by navaronbracke** [comment]
Yes, I would think so. The main point here is that we are back to Kotlin 1.7.x, the patch version doesn't affect things.

**Comment by JackWH** [comment]
@navaronbracke Thanks 🙏 Any ETA on publishing the release? FlutterFlow doesn't let me import from master branch unfortunately.

**Comment by navaronbracke** [comment]
@JackWH I will try to get this released this week if possible. I understand that getting these fixes published is a high priority.

**Comment by navaronbracke** [comment]
The fix for the Kotlin version is available from v3.5.0 onwards.

**Comment by Jack04Sm** [comment]
Hello @1Dimitri 

I've sent the details directly to your inbox.

Responding in regards to your flutterflow.io forum post.
Please check your messages or feel free to contact me using the information provided below for further assistance

Email: jack(at)technogiq(dot)com
Skype: live:.cid.a0f06a69cf1c6478

Looking forward to hearing from you.

Regards,
Jack
