### ISSUE TITLE
Pod Installation Error After Upgrading mobile_scanner from 3.1.0 to 3.4.1

### ISSUE THREAD

**Issue by AristideVB** [juliansteenbakker/mobile_scanner#769]
**Issue Description:**
After upgrading the `mobile_scanner` package from version 3.1.0 to 3.4.1, I'm experiencing a conflict in my CocoaPods dependencies related to `MLKitCommon`.

**Steps to Reproduce:**

1. Upgrade `mobile_scanner` in `pubspec.yaml` from version 3.1.0 to 3.4.1.
2. Run `flutter pub get`.
3. Navigate to the `ios` directory and run `pod repo update` `pod install`.

**Expected Outcome:**
CocoaPods dependencies should be resolved and installed successfully.

**Actual Outcome:**
Received the following error:

```
firebase_crashlytics: Using Firebase SDK version '10.15.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.15.0' defined in 'firebase_core'

CocoaPods could not find compatible versions for pod "MLKitCommon":
  In Podfile:
    MLKitCommon (from `MLKitCommon.podspec.json`)
    MLKitVision (from `MLKitVision.podspec.json`) was resolved to 4.2.0, which depends on
      MLKitCommon (~> 8.0)
    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 3.2.0, which depends on
      GoogleMLKit/BarcodeScanning (~> 4.0.0) was resolved to 4.0.0, which depends on
        GoogleMLKit/MLKitCore (= 4.0.0) was resolved to 4.0.0, which depends on
          MLKitCommon (~> 9.0.0)
```

**Environment:**

- Flutter version: 3.13.6
- Dart version: 3.1.3

**Additional Information:**
I've tried everything, uninstall cocoapods, reinstalling, `flutter clean` `flutter pub get` removing my `Podfile.lock` `pod cache clean --all` `pod repo update` `pod install`... my firebase dependencies are also up to date

**Comment by BilalAhmed-1998** [comment]
I am facing the same issue. Have you worked out somewthing?

**Comment by BilalAhmed-1998** [comment]
CocoaPods could not find compatible versions for pod "MLKitCommon":
  In Podfile:
    MLKitCommon (from `MLKitCommon.podspec.json`)

    MLKitVision (from `MLKitVision.podspec.json`) was resolved to 4.2.0, which depends on
      MLKitCommon (~> 8.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 3.2.0, which depends on
      GoogleMLKit/BarcodeScanning (~> 4.0.0) was resolved to 4.0.0, which depends on
        GoogleMLKit/MLKitCore (= 4.0.0) was resolved to 4.0.0, which depends on
          MLKitCommon (~> 9.0.0)

**Comment by AristideVB** [comment]
@BilalAhmed-1998 No sorry haven't figured it out yet. But let me know if you do 🙂

**Comment by navaronbracke** [comment]
See my comment in https://github.com/juliansteenbakker/mobile_scanner/issues/771#issuecomment-1760148418

That should help with the dependency issue.

**Comment by EArminjon** [comment]
```
rm -rf Podfile.lock Pods .symlinks
```
```
pod install  --repo-update
```

**Comment by navaronbracke** [comment]
As mentioned by @EArminjon above, this is most likely a Cocoapods dependency issue with an outdated pods configuration.

The example app runs fine on iOS, so there is not much we can do about this, as `MLKitCommon 9.0.0` is the most recent version. See https://github.com/CocoaPods/Specs/tree/master/Specs/c/c/6/MLKitCommon/9.0.0
