### ISSUE TITLE
MobileScannerController.analyzeImage() method return wrong value when we click image using camera

### ISSUE THREAD

**Issue by priyankaborate** [juliansteenbakker/mobile_scanner#77]
1. Capture a photo return correct value
2. Capture another photo with different QR code it returns the old value(returns value from image captured in 1 step)

**Comment by myoganugraha** [comment]
should [this](https://github.com/juliansteenbakker/mobile_scanner/issues/58#issuecomment-1066501878) is accept as the answer  ?

**Comment by leeyisoft** [comment]
I had the same problem: LOADING a QR code image from an gallery, I couldn't recognize it, the analyzeImage method always returned false

**Comment by juliansteenbakker** [comment]
Please check with latest version v3.0.0-beta.4

**Comment by ShwetaChauhan18** [comment]
`mobile_scanner: ^3.4.1`

I also have same problem. Also, screenshot image is not working.
