### ISSUE TITLE
 CocoaPods could not find compatible versions for pod "MLKitCommon" (mobile_scanner 2.1.0 --> mobile_scanner^3.4.1)

### ISSUE THREAD

**Issue by BilalAhmed-1998** [juliansteenbakker/mobile_scanner#771]
CocoaPods could not find compatible versions for pod "MLKitCommon":
  In Podfile:
    MLKitCommon (from `MLKitCommon.podspec.json`)

    MLKitVision (from `MLKitVision.podspec.json`) was resolved to 4.2.0, which depends on
      MLKitCommon (~> 8.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 3.2.0, which depends on
      GoogleMLKit/BarcodeScanning (~> 4.0.0) was resolved to 4.0.0, which depends on
        GoogleMLKit/MLKitCore (= 4.0.0) was resolved to 4.0.0, which depends on
          MLKitCommon (~> 9.0.0)

**Comment by mrRedSun** [comment]
Try to do 
`cd ios && rm Podfile.lock && pod install --repo-update`

**Comment by navaronbracke** [comment]
`mobile_scanner` depends on `MLKitCommon (~> 9.0.0)`, but your `MLKitVision` dependency depends on `MLKitCommon (~> 8.0)`, which is a lower version.

You'll have to upgrade to `MLKitVision version 5.0.0`

https://github.com/CocoaPods/Specs/blob/master/Specs/8/1/e/MLKitVision/5.0.0/MLKitVision.podspec.json
