### ISSUE TITLE
Clean up the use of print statements in the plugin

### ISSUE THREAD

**Issue by navaronbracke** [juliansteenbakker/mobile_scanner#780]
The plugin has a bunch of print / debugPrint statements in the code.

These should either be removed, or turned into proper thrown errors (MethodChannel result/ event sink or otherwise)

**Comment by Redvey** [comment]
Please can u share a ss of the statements to be removed?

**Comment by Pushpendra1001** [comment]
i am interested in this only remove print statements ? or something else ?

**Comment by navaronbracke** [comment]
The new beta release cleans this up, so this can be closed.
