### ISSUE TITLE
Bug at detectionTimeoutMS on iOS

### ISSUE THREAD

**Issue by imaaronath** [juliansteenbakker/mobile_scanner#787]
I'm already at MobileScannerController Detectionspeed.normal and DetectionTimeoutMS 5000 but in iOS not working and in Android working normal

**Comment by navaronbracke** [comment]
It seems that only the MacOS implementation uses the timeout properly. The iOS implementation never uses the timeout.

Should be trivial to fix.

**Comment by navaronbracke** [comment]
@juliansteenbakker Essentially it is this PR, but for iOS https://github.com/juliansteenbakker/mobile_scanner/pull/675

Not sure why the PR title indicated iOS, even though it was only implemented for MacOS.

**Comment by navaronbracke** [comment]
This is fixed in version 3.5.0
