### ISSUE TITLE
Example app lacks a sample with an overlay

### ISSUE THREAD

**Issue by navaronbracke** [juliansteenbakker/mobile_scanner#794]
The example app currently lacks a sample for an overlay.

There is one in `lib/mobile_scanner_overlay.dart` but it is non-functional.

We should fix that sample.

**Comment by Spyy004** [comment]
Hey, I would like to work on this issue but there is no file named mobile_scanner_overlay.dart inside lib folder.  I tried searching other folders but couldn't find one anywhere.

**Comment by navaronbracke** [comment]
It should be this one: https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/lib/mobile_scanner_overlay.dart

**Comment by Spyy004** [comment]
@navaronbracke  So I was able to add the overlay but do you need the overlay to be something specific or am I free to make an overlay of my wish ?

**Comment by navaronbracke** [comment]
As it is a sample, you can choose how the overlay looks. But in my opinion perhaps a square or rectangle would be a good option, since that is probably the most common. Perhaps you could even give it rounded corners?

I would configure the scan window in the sample, so that the overlay indicates where the scan window is located?

**Comment by Spyy004** [comment]
So a rectangle box with rounded borders? No text or button or anything inside it. Also, I didn't understood " so that the overlay indicates where the scan window is located?" this part.

**Comment by navaronbracke** [comment]
I think that with the overlay, we want something like this:
https://stackoverflow.com/questions/38300362/how-to-draw-four-boundary-corner-for-qr-code-scanner

Then the overlay is the square. You can add some text below the square (perhaps a `scan a code / scanned barcode value`)

For the scan window, I meant to use this function: https://github.com/juliansteenbakker/mobile_scanner/blob/master/lib/src/mobile_scanner_controller.dart#L446C16-L446C32

With that function we configure what part of the camera view is the actual scan region, so that nothing outside the square is detected.

**Comment by Spyy004** [comment]
Got it. Thanks for the clear explanation.

**Comment by Spyy004** [comment]
https://github.com/juliansteenbakker/mobile_scanner/assets/54628130/82c6bbc4-7433-4c7b-afee-4b0a8d14ee6a

Does this look fine ?. I am trying to add the white borders to the scan window but I am kind of a noob with custom paint. Will figure out something

**Comment by navaronbracke** [comment]
That is already a good start!

**Comment by Spyy004** [comment]
I have raised a PR. Please have alook @navaronbracke

**Comment by Redvey** [comment]
Please can u also assign me? I would like to try my hands on it@navaronbracke

**Comment by navaronbracke** [comment]
Fixed by #798
