### ISSUE TITLE
When proguard is enabled it's not working in android

### ISSUE THREAD

**Issue by KoustuvGanguly** [juliansteenbakker/mobile_scanner#795]
Add 

-keep class com.google.mlkit.** { *; }
-keep class com.google.android.libraries.barhopper.** { *; }
-keep class com.google.photos.** { *; }

to avoid crash/not working issues. TIA!

**Comment by navaronbracke** [comment]
I'll see if I can put this in the plugin's ProGuard file. Thanks!

**Comment by navaronbracke** [comment]
This is included in version 3.5.1
