### ISSUE TITLE
v3.4.0 and above fails to scan QR code in short distance.

### ISSUE THREAD

**Issue by limbo93** [juliansteenbakker/mobile_scanner#796]
When I scan QR it fails to scan, where while scanning from at least 10/12 inch scans fine.

**Comment by hrithikM31** [comment]
i noticed the same

**Comment by limbo93** [comment]
![Screenshot 2023-10-19 101249](https://github.com/juliansteenbakker/mobile_scanner/assets/26410152/f870c02a-80e9-4fe0-b509-8c228aaf6b24)

Checked with Android (Samsung, HuaweiP30 light) & iOS 14

**Comment by EArminjon** [comment]
Do you use a scanWindow ? Do you have the issue on the master branch of this repo ?

**Comment by limbo93** [comment]
Yes, the scan window opens fine. But can't scan the QR if it's too close. I haven’t checked the master branch. However I have checked last two published version.

**Comment by EArminjon** [comment]
I believe your issue is fixed on master branch, please test ;).

**Comment by limbo93** [comment]
Master branch works fine :)

**Comment by EArminjon** [comment]
Issue can be closed, version 3.5.0 is available on pub.dev
