### ISSUE TITLE
[Flutter Web] Question: Camera Facing Default Value

### ISSUE THREAD

**Issue by dhruvilp** [juliansteenbakker/mobile_scanner#82]
Hey, 

I've set default CameraFacing to back like `MobileScannerController(facing: CameraFacing.back)` for web app.
However, it's still using FrontCamera, is FontCamera default to web and only option?

**Comment by Antoni-Czaplicki** [comment]
#78

**Comment by juliansteenbakker** [comment]
This is fixed in #78
