### ISSUE TITLE
Definition of 'MobileScannerPlugin' must be imported from module 'mobile_scanner.Swift' before it is required

### ISSUE THREAD

**Issue by afelipe00** [juliansteenbakker/mobile_scanner#830]
Semantic Issue (Xcode): Duplicate interface definition for class 'MobileScannerPlugin'
.../build/ios/Release-iphoneos/mobile_scanner/mobile_scanner.framework/Headers/MobileScanne
rPlugin.h:2:0

Modules Issue (Xcode): Definition of 'MobileScannerPlugin' must be imported from module 'mobile_scanner.Swift' before it is required
.../ios/Runner/GeneratedPluginRegistrant.m:127:3

Encountered error while building for device.

**Comment by navaronbracke** [comment]
@afelipe00 What version of the plugin are you using? Newer version of the plugin no longer use the Objective-C header stub, so `MobileScannerPlugin.h` does not exist anymore.

Does this reproduce on version 3.5.1 ?

**Comment by camillobucciarelli** [comment]
I have the same issue with the version 3.5.1

**Comment by navaronbracke** [comment]
You probably need to do a `flutter clean` as well. Do you use Objective-C for your iOS codebase?

And what is your Flutter version?

**Comment by Mortando** [comment]
Same issue on version 3.5.1

Deleted the Podfile.lock, did pod install --repo-update and I get:

Semantic Issue (Xcode): Duplicate interface definition for class 'MobileScannerPlugin'
Modules Issue (Xcode): Definition of 'MobileScannerPlugin' must be imported from module 'mobile_scanner.Swift' before it is required

**Comment by navaronbracke** [comment]
@Mortando What Flutter version are you using? The `GeneratedPluginRegistrant.m` which has the error, is generated by Flutter. So you have to do a `flutter clean`. What is the content of your `GeneratedPluginRegistrant.m` ?

**Comment by Mortando** [comment]
@navaronbracke Flutter 3.13.6

I can't tell you what the `GeneratedPluginRegistrant.m` says in it's content, but the `flutter clean` did indeed **solve** the issue.

**Comment by navaronbracke** [comment]
For anyone running into this issue:

- Update to `mobile_scanner` version `3.5.1`
- remove your Podfile.lock
- run `flutter clean`
- run `flutter build ios`

The reason is that the `MobileScannerPlugin.h/.m` has been removed, because it was unnecessary.
But since the generated `GeneratedPluginRegistrant.m` file contains a reference to that file, it needs to be regenerated by Flutter.

**Comment by Dilshan97** [comment]
> * flutter clean

this one work for me

**Comment by Dilshan97** [comment]
> For anyone running into this issue:
> 
> * Update to `mobile_scanner` version `3.5.1`
> * remove your Podfile.lock
> * run `flutter clean`
> * run `flutter build ios`
> 
> The reason is that the `MobileScannerPlugin.h/.m` has been removed, because it was unnecessary. But since the generated `GeneratedPluginRegistrant.m` file contains a reference to that file, it needs to be regenerated by Flutter.

this one work for me
