### ISSUE TITLE
toggleTorch() is out of sync with the actual torch state

### ISSUE THREAD

**Issue by edwintsai** [juliansteenbakker/mobile_scanner#833]
I had upgrade to mobile_scanner 3.5.1, If I set torchEnabled : true, it's working in start the camera, but can't stop torch if I call toggleTorch. 

`IconButton(
            color: Colors.white,
            icon: ValueListenableBuilder(
              valueListenable: cameraController.torchState,
              builder: (context, state, child) {
                switch (state) {
                  case TorchState.off:
                    return const Icon(Icons.flash_off, color: Colors.grey);
                  case TorchState.on:
                    return const Icon(Icons.flash_on, color: Colors.yellow);
                }
              },
            ),
            iconSize: 32.0,
            onPressed: () =>cameraController.toggleTorch(),
          )`
...
`controller: MobileScannerController(
                      formats: [BarcodeFormat.qrCode],
                      detectionSpeed: DetectionSpeed.noDuplicates,  //DetectionSpeed.normal,
                      facing: CameraFacing.back,
                      detectionTimeoutMs: 1000,
                      returnImage: false,
                      torchEnabled: false,
                    ),`

**Comment by navaronbracke** [comment]
I think I know what the problem might be here.

On iOS, we turn on the torch if `torchEnabled` is true.
However, we do not forward the torch state to the notifier.
And in `toggleTorch()` we do not check the current state either.

As a workaround you could try to set the torch after the controller was started.

**Comment by navaronbracke** [comment]
What we should do is the following:

- instead of blindly trying to turn the torch on on the native side, check if the torch is on before turning it on
- forward the result of the torch being set to on to the notifier, so the state is in sync
- fix the MacOS implementation to match the iOS one (they both use a slightly different setup)

**Comment by navaronbracke** [comment]
@edwintsai This should have been fixed on master now. I'm currently looking into a small MLKit related issue on Android, but there should be a hotfix later today with this bug fixed.
