### ISSUE TITLE
Doesn't work on mobile Safari 

### ISSUE THREAD

**Issue by agordeev** [juliansteenbakker/mobile_scanner#834]
The example app shows a black frame:

<img src="https://github.com/juliansteenbakker/mobile_scanner/assets/2883524/38f572a6-0ee7-408d-920a-b9230e3342cd" width="320"/>

Camera permission isn't triggered

**Comment by codewithbayanda** [comment]
I'm also facing this😥

**Comment by agordeev** [comment]
Apparently, it works only in secure context. You have to use HTTPS.
