### ISSUE TITLE
Scanning onDetect runs multiple times

### ISSUE THREAD

**Issue by MarkoMlinarevicDept** [juliansteenbakker/mobile_scanner#84]
i have allowDuplicates: false, but it stills triggers constantly when scanned

```
MobileScanner(
          allowDuplicates: false,
          onDetect: (barcode, args) {
            final code = barcode.rawValue;
            print(code);
          },
        ),
```

**Comment by AdamVe** [comment]
You can stop the scanning when you are satisfied with the barcode result by calling [MobileScannerController.stop()](https://github.com/juliansteenbakker/mobile_scanner/blob/c989684c3d4b68ece890d216851b4de26c9eecbc/lib/src/mobile_scanner_controller.dart#L199)

**Comment by MarkoMlinarevicDept** [comment]
Thanks
