### ISSUE TITLE
Using multiple `MobileScanner`s in a `PageTransitionSwitcher`

### ISSUE THREAD

**Issue by frankvollebregt** [juliansteenbakker/mobile_scanner#853]
I got into the scenario where I would like to use multiple different `MobileScanner` Widgets one after the other, and I would like to transition between one scanner and the other using a `PageTransitionSwitcher`:
https://pub.dev/documentation/animations/latest/animations/PageTransitionSwitcher-class.html

Which works by keeping both children alive until the old one has left the screen, after which it is disposed. Obviously, this is a problem, because we can only have the camera open once at any time.

I tried to call `controller.close()` on the `MobileScannerController` (and awaiting it) before triggering the transition. This seems to prevent the `errorBuilder` from triggering, but the camera does not show in the second scan view. I also tried to disable `autoOpen` and instead open the scanner manually (also closing it manually as before), but this also did not work for me.

This issue occurs for me both on Android (Pixel 6, Pixel 7) as well as on iOS (iPhone XR, iPhone 14 Pro)

If I just replace the Widget in the widget tree, it works as expected. Is there some way I can manage the lifecycle of the `MobileScanner` such that I can prevent this behavior?

## Some logs
For the examples below, I show only the logs I think are relevant.
<details><summary>Default case</summary>

In this case, the first time the camera is shown as expected. I dispose the `controller` in the Widget's `dispose` method (which triggers at the end of the transition). The second time the camera is not shown, and I see the error builder instead (black screen with small white exclamation mark)

```
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Opening camera.
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: INITIALIZED --> OPENING
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} CameraDevice.onOpened()
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: OPENING --> OPENED

<-- This is where I trigger the transition

W/1.raster(15811): type=1400 audit(0.0:5539): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app:s0:c111,c257,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=nl.evoit.lmsdriver
D/DeferrableSurface(15811): surface closed,  useCount=1 closed=true androidx.camera.core.SurfaceRequest$2@d422dda
D/DeferrableSurface(15811): surface closed,  useCount=1 closed=true androidx.camera.core.impl.ImmediateSurface@3ecab01
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Use cases [androidx.camera.core.Preview-6ed4b90f-1b65-4018-bc6b-459bacd2cbb996226249, androidx.camera.core.ImageAnalysis-52278297-5b21-481e-a876-06c019b51f3c112833230] now DETACHED for camera
D/UseCaseAttachState(15811): All use case: [] for camera: 0
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Resetting Capture Session
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Releasing session in state OPENED
D/UseCaseAttachState(15811): Active and attached use case: [] for camera: 0
D/UseCaseAttachState(15811): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Closing camera.
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: OPENED --> CLOSING
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} CameraDevice.onClosed()
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: CLOSING --> INITIALIZED
```
</details>

<details><summary>Close in dispose</summary>

In this case, the first time the camera is shown as expected too. I still dispose the `controller` in the Widget's `dispose` method (which triggers at the end of the transition). Now I call and await `controller.stop()` before triggering the transition. In the second view, I do not see the error builder, but I also do not see the camera view.

Judging from the logs, it seems to open and immediately close again...

```
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Opening camera.
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: INITIALIZED --> OPENING
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} CameraDevice.onOpened()
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: OPENING --> OPENED

<-- This is where I call controller.stop()
<-- This is where I trigger the transition

D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Closing camera.
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: OPENED --> CLOSING
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} CameraDevice.onClosed()
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: CLOSING --> INITIALIZED
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Opening camera.
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: INITIALIZED --> OPENING
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} CameraDevice.onOpened()
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: OPENING --> OPENED
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Closing camera.
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: OPENED --> CLOSING
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} CameraDevice.onClosed()
D/Camera2CameraImpl(15811): {Camera@52e0755[id=0]} Transitioning camera internal state: CLOSING --> INITIALIZED
```
</details>

**Comment by navaronbracke** [comment]
Currently, the `MobileScanner` widget manages the lifecycle by itself. This is an error, as the controller gets disposed of when the widget moves in the widget tree (instead of being _removed from_ the widget tree).

I plan to address this and https://github.com/juliansteenbakker/mobile_scanner/issues/691 (which is related to the lifecycle as well). This is going to take a bit of work since the scanner currently has several attributes relating to starting the scanner
(onStart, onScannerStarted, onPermissionSet etc)

I would remove the `WidgetsBindingObserver` from the `MobileScanner` widget. Would that solve your use case?

**Comment by frankvollebregt** [comment]
Hmm, so from what I understand, currently as the first scanner view moves out of screen in the transition, the scanner/camera is disabled "globally" as it is diposed, even though the second scanner view has just entered.

I'm not sure if removing the `WidgetsBindingObserver` would have the desired effect (the app stays in the foreground when the transition happens). But if there is, at some point, a version of the package I can try this with, feel free to ping me so I can try. I might also try to create a more minimal example to demonstrate/investigate this issue, if I can find some time.

Should I leave this issue open to track it here, or do you prefer making it part of #691 and closing this one?

**Comment by navaronbracke** [comment]
The underlying cause is probably the same as https://github.com/juliansteenbakker/mobile_scanner/issues/691

Although, once I remove the WidgetsBindingObserver, you'll have to test if that fixes your issue.
I propose to leave this one open, since you provided some useful details. Once the underlying issue is fixed, we can close both anyway.

I am currently working on refactoring the platform interface (since there is some room for improvement in that area).
I do plan on removing the WidgetsBindingObserver in this refactor.

Currently I have most of the native work done (web needs a bit more work though).
Once this is in a runnable state for native (Android/iOS/MacOS) I'll ping you, so that you can test on the branch.
That should be the case in the coming days, if my planning allows it :)
