### ISSUE TITLE
[Android] QR Scanner not working on second attempt of granting permissions

### ISSUE THREAD

**Issue by Sikorrr** [juliansteenbakker/mobile_scanner#860]
**Issue Summary:**
The QR scanner in the 'MobileScanner with Controller' example app fails to activate on an Android physical device after permissions are granted on the second attempt.

**Steps to Reproduce:**
1. Open the example app on an Android physical device.
2. Tap on the 'MobileScanner with Controller' button.
3. When prompted for camera permissions, choose "Deny".
4. Go back to the main screen of the app.
5. Tap on the 'MobileScanner with Controller' button again.
6. This time, when prompted for permissions, select "Allow while using the app".

**Expected Behavior:**
The QR scanner should activate and be ready to scan QR codes after the permissions are granted.

**Actual Behavior:**
After granting the permissions on the second attempt, the QR scanner does not activate.

**Additional Information:**
- Device Model: Pixel 4a
- Android Version: 13

**Comment by demamano** [comment]
is there solution for this issue if so would you please let me know

**Comment by navaronbracke** [comment]
This also reproduces on Android 10 when first denying and then allowing the permission.

I'll investigate the issue.
