### ISSUE TITLE
[IOS] Running out of memory

### ISSUE THREAD

**Issue by ZiiwareJordanc** [juliansteenbakker/mobile_scanner#862]
Issue im having is that when im using the widget to scan barcode on a IPad Air IOS 12.5.6.
First scan seems to go fine, same with the second as long as its on the exact same barcode.
If i swap between 4 different codes eventually i end up getting a crash. With the fact that its crashing i dont get much of a log to share in this post.
![Screenshot 2023-11-15 at 3 43 50 PM](https://github.com/juliansteenbakker/mobile_scanner/assets/78875555/62b0bc15-f89f-4562-836f-f7ad85176aa2)
But i will post what xcode ends up showing me for my companies own app.
Ive tried using the example app that is posted for the library but it results in the same kind of problem.

This almost seems like its running out of memory, so any help would be much appreciated.

**Comment by ZiiwareJordanc** [comment]
To expand upon this, none of the ipads i have access to on IOS16 or higher seem to have this issue.

**Comment by navaronbracke** [comment]
@ZiiwareJordanc Do you see this with mobile_scanner version 5 as well? For iOS/iPadOS I am currently fixing a bug where the scanner is not deallocated. Maybe this is related?

**Comment by ZiiwareJordanc** [comment]
I'll take a look and let you know.
