### ISSUE TITLE
QR code not scanning, onDetect not calling

### ISSUE THREAD

**Issue by mahendravijay** [juliansteenbakker/mobile_scanner#866]
onDetect callback not calling. I tried to downgrade to 3.2.0 and upgraded to 3.5.2. 2 weeks before it worked with 3.2.0 but the QR code not detecting both Android and iOS. 

I tried the unbundled version too.

`W/OnBackInvokedCallback(13664): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
D/TransportRuntime.SQLiteEventStore(13664): Storing event with priority=DEFAULT, name=FIREBASE_ML_SDK for destination cct
D/DeferrableSurface(13664): Surface created[total_surfaces=1, used_surfaces=0](androidx.camera.core.SurfaceRequest$2@bc92979}
D/CameraOrientationUtil(13664): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/TransportRuntime.JobInfoScheduler(13664): Upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/CameraOrientationUtil(13664): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/CameraOrientationUtil(13664): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/DeferrableSurface(13664): Surface created[total_surfaces=2, used_surfaces=0](androidx.camera.core.impl.ImmediateSurface@6c8566c}
D/CameraOrientationUtil(13664): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/CameraOrientationUtil(13664): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
E/FileUtils(13664): err write to mi_exception_log
D/Camera2CameraImpl(13664): {Camera@ed0ef0[id=0]} Use case androidx.camera.core.Preview-8753efdb-cbe1-44de-af96-a040e4be711b83214548 ACTIVE
D/UseCaseAttachState(13664): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl(13664): {Camera@ed0ef0[id=0]} Use case androidx.camera.core.ImageAnalysis-2417b284-bf34-4955-a969-d3fc925d2e6689907837 ACTIVE
D/UseCaseAttachState(13664): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl(13664): {Camera@ed0ef0[id=0]} Use cases [androidx.camera.core.Preview-8753efdb-cbe1-44de-af96-a040e4be711b83214548, androidx.camera.core.ImageAnalysis-2417b284-bf34-4955-a969-d3fc925d2e6689907837] now ATTACHED
D/UseCaseAttachState(13664): All use case: [androidx.camera.core.Preview-8753efdb-cbe1-44de-af96-a040e4be711b83214548, androidx.camera.core.ImageAnalysis-2417b284-bf34-4955-a969-d3fc925d2e6689907837] for camera: 0
D/UseCaseAttachState(13664): Active and attached use case: [androidx.camera.core.Preview-8753efdb-cbe1-44de-af96-a040e4be711b83214548, androidx.camera.core.ImageAnalysis-2417b284-bf34-4955-a969-d3fc925d2e6689907837] for camera: 0
D/Camera2CameraImpl(13664): {Camera@ed0ef0[id=0]} Resetting Capture Session
D/Camera2CameraImpl(13664): {Camera@ed0ef0[id=0]} Releasing session in state INITIALIZED
D/Camera2CameraImpl(13664): {Camera@ed0ef0[id=0]} Attempting to force open the camera.
D/CameraStateRegistry(13664): tryOpenCamera(Camera@ed0ef0[id=0]) [Available Cameras: 1, Already Open: false (Previous state: CLOSED)] --> SUCCESS
D/CameraStateRegistry(13664): Recalculating open cameras:
D/CameraStateRegistry(13664): Camera                                       State                 
D/CameraStateRegistry(13664): -------------------------------------------------------------------
D/CameraStateRegistry(13664): Camera@f0633fa[id=1]                         UNKNOWN               
D/CameraStateRegistry(13664): Camera@ed0ef0[id=0]                          OPENING               
D/CameraStateRegistry(13664): -------------------------------------------------------------------
D/CameraStateRegistry(13664): Open count: 1 (Max allowed: 1)
D/Camera2CameraImpl(13664): {Camera@ed0ef0[id=0]} Opening camera.
D/Camera2CameraImpl(13664): {Camera@ed0ef0[id=0]} Transitioning camera internal state: INITIALIZED --> OPENING
D/CameraStateMachine(13664): New public camera state CameraState{type=OPENING, error=null} from OPENING and null
D/CameraStateMachine(13664): Publishing new public camera state CameraState{type=OPENING, error=null}
D/UseCaseAttachState(13664): All use case: [androidx.camera.core.Preview-8753efdb-cbe1-44de-af96-a040e4be711b83214548, androidx.camera.core.ImageAnalysis-2417b284-bf34-4955-a969-d3fc925d2e6689907837] for camera: 0
W/libc    (13664): Access denied finding property "persist.vendor.camera.privapp.list"
D/CameraExtImplXiaoMi(13664): initCameraDevice: 0
W/libc    (13664): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal(13664): ignore the torch status update of camera: 3
W/libc    (13664): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal(13664): ignore the torch status update of camera: 4
W/libc    (13664): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal(13664): ignore the torch status update of camera: 5
W/libc    (13664): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal(13664): ignore the torch status update of camera: 6
W/libc    (13664): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal(13664): ignore the torch status update of camera: 7
D/Camera2CameraImpl(13664): {Camera@ed0ef0[id=0]} Use case androidx.camera.core.Preview-8753efdb-cbe1-44de-af96-a040e4be711b83214548 ACTIVE
D/UseCaseAttachState(13664): Active and attached use case: [androidx.camera.core.Preview-8753efdb-cbe1-44de-af96-a040e4be711b83214548, androidx.camera.core.ImageAnalysis-2417b284-bf34-4955-a969-d3fc925d2e6689907837] for camera: 0
D/Camera2CameraImpl(13664): {Camera@ed0ef0[id=0]} Use case androidx.camera.core.ImageAnalysis-2417b284-bf34-4955-a969-d3fc925d2e6689907837 ACTIVE
D/UseCaseAttachState(13664): Active and attached use case: [androidx.camera.core.Preview-8753efdb-cbe1-44de-af96-a040e4be711b83214548, androidx.camera.core.ImageAnalysis-2417b284-bf34-4955-a969-d3fc925d2e6689907837] for camera: 0
D/Camera2CameraImpl(13664): {Camera@ed0ef0[id=0]} Issue capture request
D/UseCaseAttachState(13664): Active and attached use case: [androidx.camera.core.Preview-8753efdb-cbe1-44de-af96-a040e4be711b83214548, androidx.camera.core.ImageAnalysis-2417b284-bf34-4955-a969-d3fc925d2e6689907837] for camera: 0
D/Camera2CameraImpl(13664): {Camera@ed0ef0[id=0]} CameraDevice.onOpened()
D/Camera2CameraImpl(13664): {Camera@ed0ef0[id=0]} Transitioning camera internal state: OPENING --> OPENED
D/CameraStateRegistry(13664): Recalculating open cameras:
D/CameraStateRegistry(13664): Camera                                       State                 
D/CameraStateRegistry(13664): -------------------------------------------------------------------
D/CameraStateRegistry(13664): Camera@f0633fa[id=1]                         UNKNOWN               
D/CameraStateRegistry(13664): Camera@ed0ef0[id=0]                          OPEN                  
D/CameraStateRegistry(13664): -------------------------------------------------------------------
D/CameraStateRegistry(13664): Open count: 1 (Max allowed: 1)
D/CameraStateMachine(13664): New public camera state CameraState{type=OPEN, error=null} from OPEN and null
D/CameraStateMachine(13664): Publishing new public camera state CameraState{type=OPEN, error=null}
D/UseCaseAttachState(13664): All use case: [androidx.camera.core.Preview-8753efdb-cbe1-44de-af96-a040e4be711b83214548, androidx.camera.core.ImageAnalysis-2417b284-bf34-4955-a969-d3fc925d2e6689907837] for camera: 0
D/UseCaseAttachState(13664): Active and attached use case: [androidx.camera.core.Preview-8753efdb-cbe1-44de-af96-a040e4be711b83214548, androidx.camera.core.ImageAnalysis-2417b284-bf34-4955-a969-d3fc925d2e6689907837] for camera: 0
D/SyncCaptureSessionBase(13664): [androidx.camera.camera2.internal.SynchronizedCaptureSessionBaseImpl@6375a46] getSurface...done
D/CaptureSession(13664): Opening capture session.
D/DeferrableSurface(13664): New surface in use[total_surfaces=2, used_surfaces=1](androidx.camera.core.SurfaceRequest$2@bc92979}
D/DeferrableSurface(13664): use count+1, useCount=1 androidx.camera.core.SurfaceRequest$2@bc92979
D/DeferrableSurface(13664): New surface in use[total_surfaces=2, used_surfaces=2](androidx.camera.core.impl.ImmediateSurface@6c8566c}
D/DeferrableSurface(13664): use count+1, useCount=1 androidx.camera.core.impl.ImmediateSurface@6c8566c
D/CameraDevice-JV-0(13664): waitUntilIdle: E. id = 0
D/CameraDevice-JV-0(13664): waitUntilIdle: X
D/CaptureSession(13664): Attempting to send capture request onConfigured
D/CaptureSession(13664): Issuing request for session.
D/Camera2CaptureRequestBuilder(13664): createCaptureRequest
D/CaptureSession(13664): Issuing capture request.
D/Camera2CaptureRequestBuilder(13664): createCaptureRequest
D/CaptureSession(13664): CameraCaptureSession.onConfigured() mState=OPENED
D/CaptureSession(13664): CameraCaptureSession.onReady() OPENED
I/olutions.festiv(13664): createIfNeeded: Recreate new EGLImage since dataspace changed
I/olutions.festiv(13664): createIfNeeded: Recreate new EGLImage since dataspace changed
I/olutions.festiv(13664): createIfNeeded: Recreate new EGLImage since dataspace changed
I/olutions.festiv(13664): createIfNeeded: Recreate new EGLImage since dataspace changed
I/olutions.festiv(13664): createIfNeeded: Recreate new EGLImage since dataspace changed
I/olutions.festiv(13664): createIfNeeded: Recreate new EGLImage since dataspace changed
I/olutions.festiv(13664): createIfNeeded: Recreate new EGLImage since dataspace changed
I/olutions.festiv(13664): createIfNeeded: Recreate new EGLImage since dataspace changed
D/TransportRuntime.SQLiteEventStore(13664): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(13664): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/TransportRuntime.SQLiteEventStore(13664): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(13664): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/TransportRuntime.SQLiteEventStore(13664): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(13664): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/TransportRuntime.SQLiteEventStore(13664): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(13664): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
W/System  (13664): A resource failed to call Surface.release. 
I/BpBinder(13664): onLastStrongRef automatically unlinking death recipients: <uncached descriptor>`

The Camera is still open and the controller configuration is

` MobileScannerController cameraController = MobileScannerController(
    autoStart: true,
    facing: CameraFacing.back,
    formats: [BarcodeFormat.qrCode],
    torchEnabled: false,
    detectionSpeed: DetectionSpeed.noDuplicates,
  );`

Any solutions or workarounds?

**Comment by KaiExa** [comment]
Hi, its happening too me also, is there any solutions yet?

**Comment by KaiExa** [comment]
Found the solution, need to widen the scanWindow if you have declare the scanWindow

**Comment by CollinsMunene** [comment]
Still having the same issue, I'm not using the scanWindow
