### ISSUE TITLE
Getting Error after upgrading to new version

### ISSUE THREAD

**Issue by LauMeiso** [juliansteenbakker/mobile_scanner#876]
Im getting this error message when im start my project after upgrading  to new version

e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:21:45 Unresolved reference: YuvToRgbConverter
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:34:40 Unresolved reference: MobileScannerCallback
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:35:45 Unresolved reference: MobileScannerErrorCallback
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:88:52 Unresolved reference: data
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:91:48 Unresolved reference: data
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:101:43 Unresolved reference: YuvToRgbConverter
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:214:29 Unresolved reference: TorchStateCallback
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:215:33 Unresolved reference: ZoomScaleStateCallback
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:216:39 Unresolved reference: MobileScannerStartedCallback
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:393:52 Unresolved reference: AnalyzerCallback
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:398:68 Unresolved reference: data
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:23:33 Unresolved reference: BarcodeHandler
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:25:30 Unresolved reference: MobileScannerPermissions
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:29:35 Unresolved reference: AnalyzerCallback
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:45:27 Unresolved reference: MobileScannerCallback
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:62:32 Unresolved reference: MobileScannerErrorCallback
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:73:37 Unresolved reference: TorchStateCallback
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:77:41 Unresolved reference: ZoomScaleStateCallback
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:111:25 Unresolved reference: MobileScannerPermissions
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:112:21 'onResult' overrides nothing
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:115:29 Unresolved reference: MobileScannerPermissions
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:178:36 Not enough information to infer type variable V
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:179:40 Unresolved reference: it
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:180:32 Not enough information to infer type variable B
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:180:35 Not enough information to infer type variable V
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:180:52 Unresolved reference: it
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:180:74 Unresolved reference: it
e: file:///C:/Users/meiser/AppData/Local/Pub/Cache/hosted/pub.dev/mobile_scanner-3.5.3/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:181:40 Unresolved reference: it

**Comment by EArminjon** [comment]
Can you try 
- flutter clean
- flutter pub cache repair
- flutter pub get

**Comment by navaronbracke** [comment]
Version 3.5.3 has been retracted due to a critical issue on iOS. Could you retry with version 3.5.4?

**Comment by guibrandalisee** [comment]
Still happens on 3.5.4, seems to be a problem that happens only in Windows, on MacOS with the same project works fine for me

**Comment by SputNikPlop** [comment]
```
Failed to build iOS app
Semantic Issue (Xcode): Duplicate interface definition for class 'MobileScannerPlugin'
/Users/dev/rtkit/remote/build/ios/Debug-iphonesimulator/mobile_scanner/mobile_scanner.framework
/Headers/MobileScannerPlugin.h:2:0


Modules Issue (Xcode): Definition of 'MobileScannerPlugin' must be imported from module
'mobile_scanner.Swift' before it is required
/Users/dev/rtkit/remote/ios/Runner/GeneratedPluginRegistrant.m:62:3


Could not build the application for the simulator.
Error launching application on iPhone 14.
```

I got these errors which went away eventually on macos, still persist in windows though

**Comment by navaronbracke** [comment]
@SputNikPlop building for iOS is only supported when the host is a MacOS device.

The duplicate interface issue should have been fixed a while back anyway.
Make sure you are on the latest version of the plugin.

**Comment by Clon1998** [comment]
> Collaborator

I am on `mobile_scanner: 3.5.5` and see the exact same issue:
```
Running Xcode build...
Xcode build done.                                           316,6s
Failed to build iOS app
Semantic Issue (Xcode): Duplicate interface definition for class 'MobileScannerPlugin'
/Users/patrick/development/flutter-projects/mobileraker/build/ios/Debug-iphonesimulator/mobile_scanner/mobile_scanner.framework/Headers/MobileScannerPlugin.h:2:0

Modules Issue (Xcode): Definition of 'MobileScannerPlugin' must be imported from module 'mobile_scanner.Swift' before it is required
/Users/patrick/development/flutter-projects/mobileraker/ios/Runner/GeneratedPluginRegistrant.m:208:3

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.
```

**Comment by SputNikPlop** [comment]
@Clon1998 In this order try
flutter clean
flutter pub cache repair
flutter pub get

**Comment by EArminjon** [comment]
Please check the steps above and then give us your flutter doctor output.

**Comment by Clon1998** [comment]
> flutter pub get

That worked, thanks!

**Comment by navaronbracke** [comment]
@LauMeiso are you still getting this issue after doing a repair of your pub cache, as noted in https://github.com/juliansteenbakker/mobile_scanner/issues/876#issuecomment-1822721253 ?

**Comment by navaronbracke** [comment]
As this issue seems to be resolved after doing a `flutter clean && flutter pub get` I'm going to close this issue.
