### ISSUE TITLE
MissingPluginExeption (Flutter Android) 

### ISSUE THREAD

**Issue by devsef** [juliansteenbakker/mobile_scanner#89]
I always get the same ErrorMessage:
`The following MissingPluginException was thrown while de-activating platform stream on channel dev.steenbakker.mobile_scanner/scanner/event:
MissingPluginException(No implementation found for method cancel on channel dev.steenbakker.mobile_scanner/scanner/event)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:528:9)
<asynchronous suspension>`

This happens when using the original example file without controller, too.

Flutter doc:
`flutter doctor -v
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3.1 21E258 darwin-arm, locale de)
    • Flutter version 2.10.3 at /Users/tobiasn/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (5 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/tobiasn/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (3 available)
    • A11 (mobile)    • A1141280012195 • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos          • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome         • web-javascript • Google Chrome 99.0.4844.84

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`

Using Flutter and all plugins up to date versions.

**Comment by Mumunt** [comment]
it happen to me too. i use this scanner on web project.

**Comment by FabrizioBilleciUNICT** [comment]
@devsef I had the same issue. 
I solved by adding the camera permission in AndroidManifest.xml 
`<uses-permission android:name="android.permission.CAMERA" />`
and then re-build the app. 
So the app asks me to allow camera permission and finally it works.
