### ISSUE TITLE
The plugin `mobile_scanner` requires your app to be migrated to the Android embedding v2. 

### ISSUE THREAD

**Issue by danilof** [juliansteenbakker/mobile_scanner#895]
This error happens if I try to build  app on github actions or bitbacket pipiline.

Im using mobile_scanner 3.5.5 version and 
Flutter 3.16.2

After I run `dart pub get ` action I get this error:

The plugin `mobile_scanner` requires your app to be migrated to the Android embedding v2. Follow the steps on the migration doc above and re-run this command.

**Comment by navaronbracke** [comment]
The `mobile_scanner` plugin uses the Android embedding V2 setup, as the Android embedding V1 is deprecated.

Your should be using the migration guide to update your app to Android Embedding V2

See https://docs.flutter.dev/release/breaking-changes/android-v1-embedding-create-deprecation

**Comment by danilof** [comment]
👍 Thnx
