### ISSUE TITLE
[flutter web] zxingBarcodeFormat: return type 'int' doesn't allow null

### ISSUE THREAD

**Issue by hazzo** [juliansteenbakker/mobile_scanner#912]
Hi with the current version of the package (`3.5.5`) app does not get executed on flutter web.

Flutter doctor
```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.6 22G120 darwin-arm, locale en-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

Console shows the following error:
```
Launching lib/main_development.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
../../../../.pub-cache/hosted/pub.dartlang.org/mobile_scanner-3.5.5/lib/src/web/zxing.dart:106:11: Error: A non-null value must be returned since the return type 'int' doesn't allow null.
  int get zxingBarcodeFormat {
          ^
Failed to compile application.
```

I traced the error and realized that the switch case inside that method has not a `default` statement, so Dart thinks that a `null` value might be returned.

[Here is the PR](https://github.com/juliansteenbakker/mobile_scanner/pull/913) that fix this, i'll be using my forked version meanwhile.

**Comment by navaronbracke** [comment]
@hazzo Sorry for the delay, but this is now available on Pub.dev in version 3.5.6
