### ISSUE TITLE
Version 3.5.6 does not specify the right Flutter SDK constraint

### ISSUE THREAD

**Issue by banderson0827** [juliansteenbakker/mobile_scanner#929]
![image](https://github.com/juliansteenbakker/mobile_scanner/assets/67702118/0c3dd33f-9fae-473c-93d0-fc5aaa047dfa)
I am getting this error when trying to build for web, tried edge and chrome with same result I have searched all over for any solutions but cannot find any. Hoping someone here may know what to do. Thanks!

**Comment by banderson0827** [comment]
![image](https://github.com/juliansteenbakker/mobile_scanner/assets/67702118/17a9fcef-7046-4194-b1c7-095f24b9804d)

**Comment by navaronbracke** [comment]
You should upgrade your Flutter version, the `dart:ui_web` library is a new addition to Flutter.

**Comment by banderson0827** [comment]
Thank you very much, I was unaware of that but suspicious that could also be the cause. Thank you for the confirmation.

**Comment by navaronbracke** [comment]
We should have specified the minimum Flutter version in the pubspec of `mobile_scanner`, this would make this kind of issue disappear (You'll instead get a version conflict with pub, which is more helpful in this case)

@banderson0827 If you want to submit a patch for this, go ahead. Just updating the `flutter: x.y.z` constraint in the pubspec of this package + a version bump to 3.5.7 and a changelog entry is sufficient.

If you don't have the time, I'll see if I can do this later today.

**Comment by juliansteenbakker** [comment]
I've fixed this in v4.0.0.

**Comment by navaronbracke** [comment]
Thanks for fixing that one :)
