### ISSUE TITLE
Can't build in Release Mode

### ISSUE THREAD

**Issue by ArturDias13** [juliansteenbakker/mobile_scanner#933]
The following exception is produced after trying to build on release mode (it's still possible to build on debug mode): 

```
Launching lib/main.dart on Android in release mode...
e: /home/artur/.pub-cache/hosted/pub.dev/mobile_scanner-3.5.2/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt: (31, 7): Redeclaration: MobileScanner
e: /home/artur/.pub-cache/hosted/pub.dev/mobile_scanner-3.5.2/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerPermissions.kt: (13, 7): Redeclaration: MobileScannerPermissions
e: /home/artur/.pub-cache/hosted/pub.dev/mobile_scanner-3.5.5/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt: (31, 7): Redeclaration: MobileScanner
e: /home/artur/.pub-cache/hosted/pub.dev/mobile_scanner-3.5.5/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerPermissions.kt: (13, 7): Redeclaration: MobileScannerPermissions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mobile_scanner:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Running Gradle task 'assembleRelease'...                           15,9s
Exception: Gradle task assembleRelease failed with exit code 1
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:512:9)
<asynchronous suspension>
#2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:242:5)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:578:7)
<asynchronous suspension>
#4      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:534:33)
<asynchronous suspension>
#5      ColdRunner.run (package:flutter_tools/src/run_cold.dart:57:28)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:753:27)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

Flutter doctor

```
[✓] Flutter (Channel stable, 3.13.7, on Ubuntu 22.04.3 LTS 6.5.0-14-generic, locale pt_BR.UTF-8)
    • Flutter version 3.13.7 on channel stable at /home/artur/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (3 months ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/artur/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/artur/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 75.0.1
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/artur/android-studio
    • Flutter plugin version 74.0.4
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.79.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • Android (mobile) • RMXT88230300002 • android-arm64  • Android 12 (API 31)
    • Linux (desktop)  • linux           • linux-x64      • Ubuntu 22.04.3 LTS 6.5.0-14-generic
    • Chrome (web)     • chrome          • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

EDIT: I'm using version 3.5.5, since 3.5.6 requires me to change my compile sdk to 34, which produces more exceptions.

**Comment by ridwanulhoquejr** [comment]
I also get the same errors, after upgrading the mobile_scanner to the latest version.

Mine is:
Execution failed for task ':mobile_scanner:compileReleaseJavaWithJavac'.
error: invalid source release: 17

> The following exception is produced after trying to build on release mode (it's still possible to build on debug mode):
> 
> ```
> Launching lib/main.dart on Android in release mode...
> e: /home/artur/.pub-cache/hosted/pub.dev/mobile_scanner-3.5.2/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt: (31, 7): Redeclaration: MobileScanner
> e: /home/artur/.pub-cache/hosted/pub.dev/mobile_scanner-3.5.2/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerPermissions.kt: (13, 7): Redeclaration: MobileScannerPermissions
> e: /home/artur/.pub-cache/hosted/pub.dev/mobile_scanner-3.5.5/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt: (31, 7): Redeclaration: MobileScanner
> e: /home/artur/.pub-cache/hosted/pub.dev/mobile_scanner-3.5.5/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerPermissions.kt: (13, 7): Redeclaration: MobileScannerPermissions
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':mobile_scanner:compileReleaseKotlin'.
> > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
>    > Compilation error. See log for more details
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 15s
> Running Gradle task 'assembleRelease'...                           15,9s
> Exception: Gradle task assembleRelease failed with exit code 1
> #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
> #1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:512:9)
> <asynchronous suspension>
> #2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:242:5)
> <asynchronous suspension>
> #3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:578:7)
> <asynchronous suspension>
> #4      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:534:33)
> <asynchronous suspension>
> #5      ColdRunner.run (package:flutter_tools/src/run_cold.dart:57:28)
> <asynchronous suspension>
> #6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:753:27)
> <asynchronous suspension>
> #7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
> <asynchronous suspension>
> #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> <asynchronous suspension>
> #9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
> <asynchronous suspension>
> #10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
> <asynchronous suspension>
> #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> <asynchronous suspension>
> #12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
> <asynchronous suspension>
> #13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
> <asynchronous suspension>
> #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> <asynchronous suspension>
> #15     main (package:flutter_tools/executable.dart:90:3)
> <asynchronous suspension>
> ```
> 
> Flutter doctor
> 
> ```
> [✓] Flutter (Channel stable, 3.13.7, on Ubuntu 22.04.3 LTS 6.5.0-14-generic, locale pt_BR.UTF-8)
>     • Flutter version 3.13.7 on channel stable at /home/artur/snap/flutter/common/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 2f708eb839 (3 months ago), 2023-10-09 09:58:08 -0500
>     • Engine revision a794cf2681
>     • Dart version 3.1.3
>     • DevTools version 2.25.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
>     • Android SDK at /home/artur/Android/Sdk
>     • Platform android-34, build-tools 34.0.0
>     • Java binary at: /home/artur/android-studio/jbr/bin/java
>     • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
>     • All Android licenses accepted.
> 
> [✓] Chrome - develop for the web
>     • Chrome at google-chrome
> 
> [✓] Linux toolchain - develop for Linux desktop
>     • clang version 10.0.0-4ubuntu1
>     • cmake version 3.16.3
>     • ninja version 1.10.0
>     • pkg-config version 0.29.1
> 
> [✓] Android Studio (version 2022.2)
>     • Android Studio at /usr/local/android-studio
>     • Flutter plugin version 75.0.1
>     • Dart plugin version 222.4582
>     • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
> 
> [✓] Android Studio (version 2023.1)
>     • Android Studio at /home/artur/android-studio
>     • Flutter plugin version 74.0.4
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
> 
> [✓] VS Code (version 1.79.0)
>     • VS Code at /usr/share/code
>     • Flutter extension version 3.80.0
> 
> [✓] Connected device (3 available)
>     • Android (mobile) • RMXT88230300002 • android-arm64  • Android 12 (API 31)
>     • Linux (desktop)  • linux           • linux-x64      • Ubuntu 22.04.3 LTS 6.5.0-14-generic
>     • Chrome (web)     • chrome          • web-javascript • Google Chrome 114.0.5735.106
> 
> [✓] Network resources
>     • All expected network resources are available.
> 
> • No issues found!
> ```

**Comment by ArturDias13** [comment]
> > I also get the similar error as @ArturDias13 i guess. In my case, this issue arrived after upgrading the mobile_scanner to the latest version.
> > Mine is: Execution failed for task ':mobile_scanner:compileReleaseJavaWithJavac'. error: invalid source release: 17
> 
> My issue is resolved by rollbacking to the exact version of 3.5.5 as suggested in #922
> 
> ![image](https://private-user-images.githubusercontent.com/52696988/297157932-b247690c-ab04-497f-a767-663c4c46157e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MzMyNzEsIm5iZiI6MTcwNTQzMjk3MSwicGF0aCI6Ii81MjY5Njk4OC8yOTcxNTc5MzItYjI0NzY5MGMtYWIwNC00OTdmLWE3NjctNjYzYzRjNDYxNTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDE5MjI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNzEwZGJlMzZjNjRiODExYjg1MzcxNjg1NGU2OTAwNjU3YTIyODZjMTk5MmNkNWQ3MTVmZGU0YjYwYjgxYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JwyeRKmSJbtECrHsv2pPSA3LvVmU2peMWrnq6iqeRUs)

Done that, but the error persists

**Comment by ArturDias13** [comment]
I managed to solve it, I don't know the exactly what I did, but after removing, adding, changing versions, cleaning, etc, it's working again. Currently, I'm on 3.5.5

**Comment by marcobraghim** [comment]
Same here, this solution worked too

**Comment by pierre-juarez** [comment]
Problem solved, here:
https://github.com/juliansteenbakker/mobile_scanner/issues/876#issuecomment-1822721253
