### ISSUE TITLE
Scanner can't detect anymore after it has been hide

### ISSUE THREAD

**Issue by fikurniawan** [juliansteenbakker/mobile_scanner#938]
Prevously i can do this with qr_code_scanner, but i cannot do it again with this package.

This is just sample code:
body: Column(
        children: [
          isStarted == true ? Expanded(child: scanWidget()) : SizedBox.shrink(),
          Expanded(
            child: ListView.builder(
              itemCount: listData.length,
              itemBuilder: (context, index) => Text(listData[index]),
            ),
          )
        ],
      ),
floatingActionButton: FloatingActionButton(
        onPressed: _startOrStop,
        child: const Icon(Icons.camera_alt),
      ),

But it works if i don't do switch between scanWidget and SizeBox.shrink.

**Comment by navaronbracke** [comment]
Could you provide a minimal reproducible sample that we can run? Ideally if you could modify the example app, to illustrate your issue that would help a lot.

**Comment by fikurniawan** [comment]
`import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

import 'scanner_error_widget.dart';

class BarcodeScannerWithController3 extends StatefulWidget {
  const BarcodeScannerWithController3({super.key});

  @override
  State<BarcodeScannerWithController3> createState() =>
      _BarcodeScannerWithController3State();
}

class _BarcodeScannerWithController3State
    extends State<BarcodeScannerWithController3>
    with SingleTickerProviderStateMixin {
  BarcodeCapture? barcode;

  final MobileScannerController controller = MobileScannerController(
      torchEnabled: false, useNewCameraSelector: true, autoStart: false
      // formats: [BarcodeFormat.qrCode]
      // facing: CameraFacing.front,
      // detectionSpeed: DetectionSpeed.normal
      // detectionTimeoutMs: 1000,
      // returnImage: false,
      );

  List<String> listData = [];

  bool isStarted = false;

  bool isScan = false;

  void _startOrStop() {
    try {
      if (isStarted) {
        controller.stop();
        isScan = false;
      } else {
        controller.start();
        isScan = true;
      }
      setState(() {
        isStarted = !isStarted;
      });
    } on Exception catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Something went wrong! $e'),
          backgroundColor: Colors.red,
        ),
      );
    }
  }

  int? numberOfCameras;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Test With controller'),
        actions: [
          IconButton(
              onPressed: () {
                setState(() {
                  listData.clear();
                });
              },
              icon: Icon(Icons.delete))
        ],
      ),
      body: Column(
        children: [
          isStarted == true ? Expanded(child: scanWidget()) : SizedBox.shrink(),
          Expanded(
            child: ListView.builder(
              itemCount: listData.length,
              itemBuilder: (context, index) => Text(listData[index]),
            ),
          )
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _startOrStop,
        child: const Icon(Icons.camera_alt),
      ),
    );
  }

  Builder scanWidget() {
    return Builder(
      builder: (context) {
        return Stack(
          children: [
            MobileScanner(
              onScannerStarted: (arguments) {
                if (mounted && arguments?.numberOfCameras != null) {
                  numberOfCameras = arguments!.numberOfCameras;
                  setState(() {});
                }
              },
              controller: controller,
              errorBuilder: (context, error, child) {
                return ScannerErrorWidget(error: error);
              },
              fit: BoxFit.cover,
              onDetect: (barcode) {
                setState(() {
                  this.barcode = barcode;

                  listData.add(barcode.barcodes.first.rawValue ?? "");
                });
              },
            ),
            Align(
              alignment: Alignment.bottomCenter,
              child: Container(
                alignment: Alignment.bottomCenter,
                height: 100,
                color: Colors.black.withOpacity(0.4),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: [
                    ValueListenableBuilder(
                      valueListenable: controller.hasTorchState,
                      builder: (context, state, child) {
                        if (state != true) {
                          return const SizedBox.shrink();
                        }
                        return IconButton(
                          color: Colors.white,
                          icon: ValueListenableBuilder<TorchState>(
                            valueListenable: controller.torchState,
                            builder: (context, state, child) {
                              switch (state) {
                                case TorchState.off:
                                  return const Icon(
                                    Icons.flash_off,
                                    color: Colors.grey,
                                  );
                                case TorchState.on:
                                  return const Icon(
                                    Icons.flash_on,
                                    color: Colors.yellow,
                                  );
                              }
                            },
                          ),
                          iconSize: 32.0,
                          onPressed: () => controller.toggleTorch(),
                        );
                      },
                    ),
                    IconButton(
                      color: Colors.white,
                      icon: isStarted
                          ? const Icon(Icons.stop)
                          : const Icon(Icons.play_arrow),
                      iconSize: 32.0,
                      onPressed: _startOrStop,
                    ),
                    Center(
                      child: SizedBox(
                        width: MediaQuery.of(context).size.width - 200,
                        height: 50,
                        child: FittedBox(
                          child: Text(
                            barcode?.barcodes.first.rawValue ??
                                'Scan something!',
                            overflow: TextOverflow.fade,
                            style: Theme.of(context)
                                .textTheme
                                .headlineMedium!
                                .copyWith(color: Colors.white),
                          ),
                        ),
                      ),
                    ),
                    IconButton(
                      color: Colors.white,
                      icon: ValueListenableBuilder<CameraFacing>(
                        valueListenable: controller.cameraFacingState,
                        builder: (context, state, child) {
                          switch (state) {
                            case CameraFacing.front:
                              return const Icon(Icons.camera_front);
                            case CameraFacing.back:
                              return const Icon(Icons.camera_rear);
                          }
                        },
                      ),
                      iconSize: 32.0,
                      onPressed: (numberOfCameras ?? 0) < 2
                          ? null
                          : () => controller.switchCamera(),
                    ),
                  ],
                ),
              ),
            ),
          ],
        );
      },
    );
  }
}
`

**Comment by fikurniawan** [comment]
This is my link code:
[https://pastecode.io/s/33xzgcz7](url)

**Comment by fikurniawan** [comment]
> Could you provide a minimal reproducible sample that we can run? Ideally if you could modify the example app, to illustrate your issue that would help a lot.

Ok thanks before, and this is my link code: [https://pastecode.io/s/33xzgcz7](url)

**Comment by navaronbracke** [comment]
I will have a look, but this seems to be a side effect of the `auto start` bug, where the scanner is automatically started.

**Comment by fikurniawan** [comment]
> if you put the MobileScanner behind an if statement and change the condition or in case the screen rotates, the state changes will rebuild the UI and the onDetect method will no longer fire. As a workaround, dispose and assign a new MobileScannerController when you change the if state:
> 
> ```
> /// Controller for the MobileScanner Widget
> MobileScannerController? mobileScannerController;
> 
> void toggleIsStarted() {
>   if (!isStarted) {
>     // you will show the MobileScanner Widget
>     // dispose mobileScannerController (just in case) and instantiate a new one
>     mobileScannerController?.dispose();
>     mobileScannerController = MobileScannerController();   
> } else {
>    // you will hide the MobileScanner Widget
>    // dispose mobileScannerController
>    mobileScannerController?.dispose();
>   }
> 
>   setState((){
>     isStarted = !isStarted;
>   })
> }
> ```

Thank you for your answer sir, the problem is solve. Now i can use mobilescanner package for my next project. And thank you for the great package.
