### ISSUE TITLE
Push Pop Push Leading to multiple screens

### ISSUE THREAD

**Issue by seobioh** [juliansteenbakker/mobile_scanner#942]
Hi, I have some problems while dealing with mobile_scanner 
At first Time, I scan a barcode A and it pushes to next_page correctly.
but after i pop from next_page (works nicely until here)
and scans a barcode B(or A) it pushes two screens
and both are about barcde B ( if I scan A, both are A )
What is the problem?

https://github.com/juliansteenbakker/mobile_scanner/assets/86091293/75a967db-c1c0-429c-a914-e34c6632b217

`
  class _QRcodeScanPageState extends State<QRcodeScanPage> {
  final MobileScannerController _controller = MobileScannerController();

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
  
    Future<void> pickAndAnalyzeImage() async {
    final XFile? file = await ImagePicker().pickImage(source: ImageSource.gallery);
    if (file != null) {
      // Directly analyze the image without setting up a new listener
      print("file_not_null");
      final result = await _controller.analyzeImage(file.path);
      print("result: $result");
    }
  }

  ...
  
                      child: MobileScanner(
                      fit: BoxFit.cover,
                      controller: _controller,
                      onDetect: (barcode, args) async {
                        if (barcode.rawValue != null){
                          _controller.stop();
                          await Navigator.push(
                            context, 
                            MaterialPageRoute(builder: (_) => QRcodeVerifyPage(barcode: barcode))
                          ).then((_) => _controller.start());
                        }
                      },
                    ),
...
                  RoundButton(text: Text("사진 불러오기", style: TextStyle(color: 
  Colors.white),), width: 144, onPressed: () {
                  pickAndAnalyzeImage();
                  }),
                SizedBox(height: 90,),

  `

  this is my code and  in nextpage, 
  I return by pressing 'onPressed: () {Navigator.pop(context);}'
  
  
  also the second problem is that _controller.analyzeImage is keep returning there is no barcode

**Comment by navaronbracke** [comment]
This seems to be a user error? In the code you provided, you start with a `MobileScanner` widget, but then in the `onDetect` method, you push another screen called `QRcodeVerifyPage`. 

Is the `QRcodeVerifyPage` also including a `MobileScanner` widget?

I also wonder why you use push, instead of  `replace` ? (if you go back with `push`, you end up back on the `MobileScanner` page, which you probably do not want?)

**Comment by seobioh** [comment]
> This seems to be a user error? In the code you provided, you start with a `MobileScanner` widget, but then in the `onDetect` method, you push another screen called `QRcodeVerifyPage`.
> 
> Is the `QRcodeVerifyPage` also including a `MobileScanner` widget?
> 
> I also wonder why you use push, instead of `replace` ? (if you go back with `push`, you end up back on the `MobileScanner` page, which you probably do not want?)

Thanks for your response. 
First, I want to push because after scanning, 
he might remind that he should have scanned another QRcode. 
So I want it to be able to pop to current page.

Second, I do not use Mobile scanner at next page. I'm just passing the url data to get preview

**Comment by navaronbracke** [comment]
Then I would need a minimal reproducible sample (one that only includes the mobile scanner + a push to the next route).

Maybe it has to do with the route transition and not mobile_scanner itself? This is a widget issue I think.
Could you inspect the ModalRoute with the Devtools to see which widgets are pushed / popped?

**Comment by seobioh** [comment]
> If you put a print statement in "onDetect" for a) the scanned barcode b) just before the Navigator.push()
> 
> does it say the same barcode multiple times + multiple pushes?
> 
> Unless you configure the scanner with the "noDuplicates" option, then onDetect probably triggers multiple times

thanks :) The Problem was async and await I think 
by the way, why isn't mobile_scanner getting latest if i do pub get without any dependencies? e.g) mobile_scanner :
