### ISSUE TITLE
rawBytes is missing data

### ISSUE THREAD

**Issue by yutaro47** [juliansteenbakker/mobile_scanner#947]
Hi, I was trying to read split QR codes with this package. 
But, rawBytes does not include the header infomation of QR code such as number of splits, parity, or something like that.
Is it possible to fix this issue? as `qr_scanner` would be deprecated in the future and so we would like to stick to this package.

Thank you for your supports.

**Comment by navaronbracke** [comment]
The `rawBytes` value is only intended for the use case where the display value of the QR code is not a UTF-8 string (I.e. a UTF-16 string). It does not include the entire input of the QR code, as that is not exposed either by MLKit or by the Vision API on MacOS.

**Comment by yutaro47** [comment]
Thank you for your reply. I will use `qr_scanner`  instead as this package can provide this information.
