### ISSUE TITLE
Wrong rawValue on scan

### ISSUE THREAD

**Issue by LorenzoGuerriniSTEB** [juliansteenbakker/mobile_scanner#95]
Using the latest version of mobile_scanner often the value returned from rawValue is not the expected value.

Use with BAR CODE.

The best way to reproduce the problem is to start the MobileScanner with a barcode already in front of the camera.

My code:

``` dart
class ScanTicketPage extends StatefulWidget {
  const ScanTicketPage({Key? key}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".
  @override
  State<ScanTicketPage> createState() => _ScanTicketPageState();
}

class _ScanTicketPageState extends TranslateState<ScanTicketPage> {
  late MobileScannerController _scannerController;
  bool _submitted = false;
  TicketData? _ticketData;

  @override
  initState() {
    super.initState();
    _scannerController = MobileScannerController(
      facing: CameraFacing.back,
      torchEnabled: false,
    );
  }

  // ...

  getTicketInfo(String barcode) {
    // ... Check if exist ticket with given barcode
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: SingleChildScrollView(
        child: Column(
          children: [
            Column(
              children: [
                // ...
                Container(
                  margin: const EdgeInsets.symmetric(vertical: 20),
                  height: MediaQuery.of(context).size.height * 0.5,
                  child: MobileScanner(
                    allowDuplicates: false,
                    fit: BoxFit.cover,
                    controller: _scannerController,
                    onDetect: (barcode, args) {
                      if (barcode.rawValue != null && !_submitted) {
                        getTicketInfo(barcode.rawValue!);
                      }
                    },
                  ),
                ),
                // ...
              ],
            ),
          ],
        ),
      ),
    );
  }
}
```

Expected value: 477230307788446333

Here are the results of some attempts: 4777376733416333, 477130307788446333, 3631903333, **477230307788446333**, 477230307785446333, 3077230307723030772303077230307788446333, 477230307785446333

**Comment by asimappdev** [comment]
Did you find any solution?

**Comment by ahmadrana24** [comment]
facing same issue.

**Comment by LorenzoGuerriniSTEB** [comment]
> Did you find any solution or any other package? I am also getting the wrong raw values. Thanks

I haven't found any solutions yet.
There are other plugins for reading barcodes and QR Codes but they all open the camera in a new page.

**Comment by quiquegarcia** [comment]
is this related to ```allowDuplicates``` option?

**Comment by LorenzoGuerriniSTEB** [comment]
> is this related to `allowDuplicates` option?

@quiquegarcia  No, the problem occurs with both allowDuplicates true and allowDuplicates false.

**Comment by dewbambs** [comment]
Tried reading [this](https://barcode.tec-it.com/en/Code128?data=2) barcode which should return raw value 2. But it returned 13, 17, 16300604, 16494531. 

version: 1.1.1

**Comment by yuchan2215** [comment]
Since this library uses MLKit, I think it needs to be supported by Google.
It seems to be a known bug on the MLKit side.
(I am using Deepl)

https://github.com/googlesamples/mlkit/issues/367
https://issuetracker.google.com/u/1/issues/207732702

**Comment by 2e2ee95304418f96** [comment]
same problem.

**Comment by juliansteenbakker** [comment]
Unfortunately this is not a problem of this plugin but MLKit.
