### ISSUE TITLE
Named parameters not defined 

### ISSUE THREAD

**Issue by axelasa** [juliansteenbakker/mobile_scanner#962]
Hello, when I was trying to code this part. 
 child: MobileScanner(
              allowDuplicates: true,
              onDetect: (barcode, args) {},
            ),

I have imported the package but the error was saying that 
'The argument type 'void Function(BarcodeCapture, dynamic)' can't be assigned to the parameter type 'void Function(BarcodeCapture)'.' 
The named parameter 'allowDuplicates' isn't defined.

![image](https://github.com/juliansteenbakker/mobile_scanner/assets/30687283/dad8ad94-d539-4413-87a5-5f883f3353fd)

**Comment by ShreyashKore** [comment]
Seems like you are using the newer version of the library while the code that you are trying to use is from the older version.

Old version (v2)
```dart
MobileScanner(
  controller: controller,
  fit: BoxFit.contain,
  allowDuplicates: true,
  controller: MobileScannerController(
     torchEnabled: true,
     facing: CameraFacing.front,
  ),
  onDetect: (barcode, args) {
    setState(() {
      this.barcode = barcode.rawValue;
    });
  },
),
```

New Versions (v4)

```dart
MobileScannerController controller = MobileScannerController(
  torchEnabled: true,
  // formats: [BarcodeFormat.qrCode]
  // facing: CameraFacing.front,
);

// in build method
MobileScanner(
  onScannerStarted: (arguments) {},
  controller: controller,
  errorBuilder: (context, error, child) {
    return ScannerErrorWidget(error: error);
  },
  fit: BoxFit.contain,
  onDetect: (barcode) {},
),
```

For these kinds of issues documentation is your best friend.

**Comment by axelasa** [comment]
Thank you for your help.
